### ISSUE TITLE
Network connectivity？

### ISSUE THREAD

**Issue by djhons** [volatilityfoundation/volatility3#1007]
When I use pyinstaller to package my code into vol.exe, it cannot be run without an internet connection. However, when connected to the internet, the program accesses [blob.satxxxxa.trafficmanager.net](http://blob.satxxxxa.trafficmanager.net/) and [a-0016.a-msedge.net](http://a-0016.a-msedge.net/), and downloads some files. What is the purpose of these two addresses, and I couldn't find them in the source code? Where are the downloaded files stored?
![image](https://github.com/volatilityfoundation/volatility3/assets/102639729/5a7d0ee0-c86e-4730-833a-7d72fb6c97ad)
![image](https://github.com/volatilityfoundation/volatility3/assets/102639729/7ee25291-be17-417d-aeff-f9a7f10b3b80)

**Comment by eve-mem** [comment]
Interesting. If it is anything from vol itself, I'd image it will be related to automatically attempting to download windows symbols from Microsoft. Does this happen when you try and use a linux plugin?

**Comment by ikelos** [comment]
Also, are you making use of the `--offline` flag to ensure volatility does
not attempt to contact the internet?

The only time volatility will connect to the internet is when analysing a
Windows image that it does not already have a suitable JSON ISF file for
(or when the URL you provide for an image is on the internet).  The servers
it accesses should only be Microsoft debug servers, although these may be
spread across a Content Delivery Network (hence the unusual addresses)...

**Comment by djhons** [comment]
> Interesting. If it is anything from vol itself, I'd image it will be related to automatically attempting to download windows symbols from Microsoft. Does this happen when you try and use a linux plugin?

Yes, it is indeed a download of Windows symbol files, and the traffic initiated by the downloaded file again is only 50kb, but it was 4.5MB before, maybe it was downloaded many times

**Comment by eve-mem** [comment]
I wouldn't expect vol to download symbols more than once, it should use the local JSON it's downloaded. 

Don't forget thr offline option that @ikelos highlighted too. 

Now you know what's happening do you still think this is an issue or can this one be closed now?
