### ISSUE TITLE
How to use volatility3 to export the contents of a specified memory address

### ISSUE THREAD

**Issue by 131A3D7** [volatilityfoundation/volatility3#1033]
As I mentioned in the title, I am trying to do forensic analysis of a live chat program. The aes key that decrypts the chat database is loaded in a dll. I temporarily call this dll 114514.dll, because the address of the aes key is the 114514.dll base address + offset value, so how can I use volatility to extract this key? I couldn't find the printed information on the Internet.

**Comment by eve-mem** [comment]
Hello, you can use volshell to dump any parts of a processes memory you like. You would run volshell on your memory image, use `cp(<pid of process>)` to change to the process you want, then use `db(<addrress you data you want to see>)` to display the bytes at the address you are interested in. There are some docs here that may help: https://volatility3.readthedocs.io/en/latest/volshell.html

You could also use the windows `vadinfo` plugin with the `--dump` option to save out all the memory for a process and then find the address you want that way. 

You may like to use the slack channel for questions like this, you'll probably get a quicker answer.

**Comment by 131A3D7** [comment]
Hello, I have one more question for you: when I call dlllist to get the address of a dll, is the address I get is the base address when the dll file is running?

**Comment by eve-mem** [comment]
I'm not the best with windows, but that is my understanding yes. The address returned is the base address of the running dll.

**Comment by 131A3D7** [comment]
Thank you very much for your answer.
