### ISSUE TITLE
Progress stuff should go to stderr

### ISSUE THREAD

**Issue by clausing** [volatilityfoundation/volatility3#104]
Any chance we can get the progress messages sent to stderr rather than stdout? If I redirect the the output to a file, the progress indicator also goes to the file which is not helpful (and clutters the output file).  To reproduce (on linux in this case):

$ ./vol.py -f image windows.pslist.PsList > pslist.txt

**Comment by ikelos** [comment]
Thanks for your report!  5:)  As an immediate work around, you can use `-q` to silence all progress meters.  We'll think through the implications of moving the progress output to stderr and then if we can't see any problems with it, we'll try to implement it.  I dunno how long it will take to get to that though...

**Comment by ikelos** [comment]
Hiya, this should be fixed now in master.  Please feel free to reopen if it doesn't seem fixed.  5:)
