### ISSUE TITLE
Missing plugins from blog posts from volatility labs

### ISSUE THREAD

**Issue by 2609-sabo** [volatilityfoundation/volatility3#1058]
Hello!
I read the amazing blog posts from volatility labs and was excited to try the plugins created there for myself

I found the skeleton_key_check plugin for the skeleton key page however I failed to find plugins like svcdiff, svclist (From the hidden services post) and rawsocket (from the recovering raw sockets post)

Have I missed something or are these plugins just not commited to this repo? I saw skeleton_key_check was added to a release after 3.2. and is similar in creation.

Any help is greatly appreciated!

**Comment by ikelos** [comment]
Could one of @atcuno and @iMHLv2 (or maybe even @awalters) provide an answer for this?  I thought they might be vol2 plugins but they seem pretty recent?

**Comment by ikelos** [comment]
I believe all of these have made their way into the codebase now.
