### ISSUE TITLE
Not able to download requirements.txt for Volatility 3-1.0.0

### ISSUE THREAD

**Issue by btxrrr** [volatilityfoundation/volatility3#1086]
<img width="787" alt="image" src="https://github.com/volatilityfoundation/volatility3/assets/108215843/8d303865-f4f6-462e-a218-664d1d2428f9">

**Comment by ikelos** [comment]
Hi, volatility 3 version 1.0.0 is quite old, and there wasn't a requirements.txt back when that was made.  Please try downloading the latest version (2.5.0) which does contain a requirements.txt, or if you require version 1.0.0, then you can check the setup.py file (https://github.com/volatilityfoundation/volatility3/blob/0e372b3ba27d386eb8eac1898aef7f80b8177b2d/setup.py#L35) to find the requirements listed there.  Feel free to reopen this issue if you're still facing difficulties.
