### ISSUE TITLE
Standardize debug log messages for smear and ensure used in existing code places

### ISSUE THREAD

**Issue by atcuno** [volatilityfoundation/volatility3#109]
To fufill this issue requires two tasks:

- [ ] Create a standardized debug log message format for issues where smear is encountered. Ideally this message would include the address (offset) and attempted operation that encountered the smear

- [ ] Go through the currently written plugins and extensions to use this template and ensure all needed places have the debug messages emitted

**Comment by ikelos** [comment]
Actually, the plugins should still be raising exceptions that would cause them to stop, the UI should catch the exception message and raise it more diplomatically.  This is important in case volshell and/or another application wants to do something different based on the exceptions.

Going through the plugins/extensions is only necessary where they *can* continue on an error but currently don't (which should be rare), so it's really the first issue we'll be concentrating on...

**Comment by ikelos** [comment]
Ok, there's a mock-up of improved exception responses, in the branch called issue109-standardized-exceptions.  If it looks ok, I'll make it a PR, we can review it and go from there.  If there's issues with the way forward then we can just ditch the branch.  5:)

**Comment by ikelos** [comment]
Ok, the resolution for this was merged, so I'm gonna close it off.  5:)
