### ISSUE TITLE
Expose procdump and vaddump functions

### ISSUE THREAD

**Issue by doomedraven** [volatilityfoundation/volatility3#111]
Hello would it be possible to expose vaddump and procdump and similars so they could be used in different plugins

maybe you pass an offset or pid and you get the vad/processmemory

thanks in advance

**Comment by ikelos** [comment]
Half done now, due to #115.  Thanks!  5:)

**Comment by ikelos** [comment]
Did you want to submit a procdump change now or would you like us to look into it?

**Comment by doomedraven** [comment]
i will look into that next week, i still on vacations till next tuesday

**Comment by ikelos** [comment]
No problem, enjoy your holidays!  I just didn't want it to get forgotten...  5;)

**Comment by doomedraven** [comment]
done, https://github.com/volatilityfoundation/volatility3/pull/174

**Comment by doomedraven** [comment]
thanks <3

**Comment by ikelos** [comment]
Great work, thanks @doomedraven!  5:)

**Comment by doomedraven** [comment]
thanks, still need to learn how to correctly specify types in func declaration

**Comment by doomedraven** [comment]
i also will update later my public example of vol3 plugin to use procdump
