### ISSUE TITLE
A symbol table requirement was not fulfilled.

### ISSUE THREAD

**Issue by RubaAlsmadi** [volatilityfoundation/volatility3#1125]
Hi, 
I'm trying to dump an Archlinux memory dump (I used Lime to acquire it ) Using Volatility 3. I was getting this error 
`PS C:\volatility3-develop> py .\volatility3-develop\vol.py -f .\dump.mem linux.pslist.PsList
Volatility 3 Framework 2.7.0
Progress:  100.00               Stacking attempts finished
Unsatisfied requirement plugins.PsList.kernel.layer_name:
Unsatisfied requirement plugins.PsList.kernel.symbol_table_name:

A translation layer requirement was not fulfilled.  Please verify that:
        A file was provided to create this layer (by -f, --single-location or by config)
        The file exists and is readable
        The file is a valid memory image and was acquired cleanly

A symbol table requirement was not fulfilled.  Please verify that:
        The associated translation layer requirement was fulfilled
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.PsList.kernel.layer_name', 'plugins.PsList.kernel.symbol_table_name']`

Then I was able to get the vmlinux and the System.map from the Archlinux device then I used this command `y\Desktop\dwarf2json> .\dwarf2json.exe linux --elf C:\volatility3-develop\vmlinux --system-map C:\volatility3-develop\System.map > output.json
` to get the output.json file. 

I took the file and I place it `"C:\volatility3-develop\volatility3-develop\volatility3\symbols\linux\output.json"` 

When I run the  I got this error again 
`PS C:\volatility3-develop> py .\volatility3-develop\vol.py -f .\dump.mem linux.pslist.PsList
Volatility 3 Framework 2.7.0
Progress:  100.00               Stacking attempts finished
Unsatisfied requirement plugins.PsList.kernel.layer_name:
Unsatisfied requirement plugins.PsList.kernel.symbol_table_name:

A translation layer requirement was not fulfilled.  Please verify that:
        A file was provided to create this layer (by -f, --single-location or by config)
        The file exists and is readable
        The file is a valid memory image and was acquired cleanly

A symbol table requirement was not fulfilled.  Please verify that:
        The associated translation layer requirement was fulfilled
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.PsList.kernel.layer_name', 'plugins.PsList.kernel.symbol_table_name']
PS C:\volatility3-develop>` 

I have also tried ```isfInfo``` plugin and ```banners``` plugin but I Vol3 is still unable to read the symbols:
```
PS C:\volatility3-develop> py .\volatility3-develop\vol.py -f .\arch-memory.lime isfinfo.IsfInfo
Volatility 3 Framework 2.7.0
Progress:  100.00               PDB scanning finished
URI     Valid   Number of base_types    Number of types Number of symbols       Number of enums Identifying information

file:///C:/volatility3-develop/volatility3-develop/volatility3/symbols/linux/6.1.52-valve16-1-neptune-61/6.1.52-valve16-1-neptune-61.json    Unknown 19      11251   169673  2079    b'Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 14:47:15 +0000\n\x00'
PS C:\volatility3-develop> py .\volatility3-develop\vol.py -f .\arch-memory.lime banners.Banners
Volatility 3 Framework 2.7.0
Progress:  100.00               PDB scanning finished
Offset  Banner

0x110ed7060     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
0x11545da58     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
0x1158ae060     Linux version 6.1.52-valve9-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Wed, 22 Nov 2023 23:43:34 +0000
0x2220009e0     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) # SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
0x22223b600     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
0x2234e7180     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +000000
```
Thanks 
Ruba

**Comment by Abyss-W4tcher** [comment]
Hello, you can notice the following difference, between `isfinfo` and `banners` :

`Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 14:47:15 +0000\n`
!=
`Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000`

What's is the result of `cat /proc/version` on your ArchLinux machine, from which the sample was made ?

**Comment by RubaAlsmadi** [comment]
> Hello, you can notice the following difference, between `isfinfo` and `banners` :
> 
> `Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 14:47:15 +0000\n` != `Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000`
> 
> What's is the result of `cat /proc/version` on your ArchLinux machine, from which the sample was made ?

I didn't find the headers of this system to be publicly available. The packaged vmlinux file was stripped, so I had to build the package myself as shown in the link below:
```
https://gitlab.com/evlaV/jupiter-PKGBUILD/-/blob/master/linux-neptune-61/PKGBUILD
```
From the above package I commented out the strip command to keep the headers then I used dwarf2json to use with vmlinux and system.map to correct any errors.
That's why the timestamp is different. Your request result:
```
cat /proc/version
Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
```
Btw when I started I checked your github to find the symobls for vol3 but I couldn't find it.

**Comment by Abyss-W4tcher** [comment]
My repositories does not contain symbols for ArchLinux, as debug symbols aren't consistently available (or even available at all). 

Unfortunately, it seems the `vmlinux` file for this exact kernel seems missing. Even if you recompile another `vmlinux` with the correct source, debug symbols addresses will differ. 

Can you check if you have access to the System.map file on your system (`/boot/System.map`) ?

**Comment by RubaAlsmadi** [comment]
Yeah, we have access to the system.map for the same system 
Is it enough to generate a symbol table?

**Comment by Abyss-W4tcher** [comment]
If you specified the `--system-map` argument to `dwarf2json`, then the `System.map` of the target system should have taken precedence over the symbols contained in `vmlinux`. However, the banner still needs to be updated in the resulting JSON file. 

Here is an experimental way to do it (with values related to your context) :

```sh
sudo apt-get install jq
JSON_SYMBOLS_FILE="output.json"
NEW_LINUX_BANNER="Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000"
# Override the linux banner of the existing JSON, and write the results in a new file
jq ".symbols.linux_banner.constant_data = \"$(printf "%s\0" $NEW_LINUX_BANNER | base64 -w0)\"" $JSON_SYMBOLS_FILE > $JSON_SYMBOLS_FILE.patched_banner

# Verify new banner has been applied
cat $JSON_SYMBOLS_FILE.patched_banner | jq -r ".symbols.linux_banner.constant_data" | base64 -d | xxd
```

Keep us updated on the outcome of this manipulation 👍.

**Comment by RubaAlsmadi** [comment]
Thank you for your response. I tested it  with a patched profile, but it was broken and didn’t work 
Some memory layers it was unable to read 

Then, I installed the files of the kernel that we built on the device 
Then I took a memory dump 

Volatility: It worked, but it only outputs empty lines. 

For some reason, it doesn’t print any data. How can I fix this issue?

**Comment by Abyss-W4tcher** [comment]
Indeed, using your custom kernel will be easier, to control debug symbols 👍.

How was the memory dump taken ? Could you provide the exact procedure ?

**Comment by RubaAlsmadi** [comment]
Hello, 
1. After building the new kernel, I saved this folder to install the new headers later.  This folder has the following files 
`(deck@steamdeck test)$ ls
archlinux-linux-neptune  linux-neptune-61-1.1.52.valve16-1-x86_64.pkg.tar.zst
config                   linux-neptune-61-headers-6.1.52.valve16-1-x86_64.pkg.tar.zst
config-neptune           pkg
PKGBUILD                 src
(deck@steamdeck test)$
`
2. I factory reset the arch Linux device. To dump the memory, I attempted the following steps 
2.1. git clone https://github.com/504ensicsLabs/LiME.git
2.2. when I tried to use **make** in the src of the LiME folder, I got this 
`(deck@steamdeck LiME)$ cd src
(deck@steamdeck src)$ make
make -C /lib/modules/6.1.52-valve16-1-neptune-61/build M="/home/deck/LiME/src" modules
make[1]: Entering directory '/home/deck/LiME/src'
make[1]: *** /lib/modules/6.1.52-valve16-1-neptune-61/build: No such file or directory.  Stop.
make[1]: Leaving directory '/home/deck/LiME/src'
make: *** [Makefile:35: default] Error 2`
3.So I uploaded the folder in step 1 to the arch linux device, then I unzipped it, then  I install the new headers by using the following command `sudo pacman -U linux-neptune-61-headers-6.1.52.valve16-1-x86_64.pkg.tar.zst
`
4. Back to the LiME/scr I prompt the make command 
`(deck@steamdeck ~)$ cd LiME/
(deck@steamdeck LiME)$ cd src/
(deck@steamdeck src)$ ls
deflate.c  disk.c  hash.c  lime.h  main.c  Makefile  Makefile.sample  tcp.c
(deck@steamdeck src)$ make
make -C /lib/modules/6.1.52-valve16-1-neptune-61/build M="/home/deck/LiME/src" modules
  CC [M]  /home/deck/LiME/src/tcp.o
  CC [M]  /home/deck/LiME/src/disk.o
  CC [M]  /home/deck/LiME/src/main.o
  CC [M]  /home/deck/LiME/src/hash.o
  CC [M]  /home/deck/LiME/src/deflate.o
  LD [M]  /home/deck/LiME/src/lime.o
  MODPOST /home/deck/LiME/src/Module.symvers
  CC [M]  /home/deck/LiME/src/lime.mod.o
  LD [M]  /home/deck/LiME/src/lime.ko
  BTF [M] /home/deck/LiME/src/lime.ko
strip --strip-unneeded lime.ko
mv lime.ko lime-6.1.52-valve16-1-neptune-61.ko
`
5. Dump the memory `sudo insmod lime-6.1.52-valve16-1-neptune-61.ko "path=/root/dump.mem format=lime"
` 
6. Get Volatility 3 ` git clone https://github.com/volatilityfoundation/volatility3.git
` 
**7. Then when I checked the banners** 
`python volatility3/vol.py -f /root/dump.mem banners.Banners
`
8. I got this 

`0x16d57d600     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 14:47:15 +0000
0x263c009e0     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) # SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
0x263e3b600     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
0x2650e7180     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +000000
0x29eed5060     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
0x323f7f740     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 14:47:15 +0000
0x32b616060     Linux version 6.1.52-valve9-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Wed, 22 Nov 2023 23:43:34 +0000
0x34fbb5880     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 14:47:15 +0000
0x37b49d1a0     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
0x3c4909b20     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) # SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
0x3c6e04740     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
0x415a3a738     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
0x43ef80008     Linux version 6.1.52-valve16-1-neptune-61 (linux-neptune-61@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000
`  
If you can notice : Three of them created in April(my new kernel ) and the rest are in February (which is the old kernel) which I belive has four banners . 

How can we make them all in April, so we can have the control over the system ? it looks like they are mixed with each other ! 
The issue is Volatility Is not giving the complete results which the mixed banner could be the issue !! 
Thank you.

**Comment by Abyss-W4tcher** [comment]
The `banners` plugin will scan for every string matching a Linux banner. However, some of them might be totally unrelated to the current kernel, or leftovers from the previous kernel. Even if Volatility tries to instantiate every banner it found, it will eventually reject inadequate ones. You can remove the ISF with the february kernel from your local installation, to avoid any confusion. 

Could you provide a run of Volatility3, with the option `-vvvvvvv` set, of the plugin resulting in empty lines ?

**Comment by RubaAlsmadi** [comment]
Thank you. It works :)
