### ISSUE TITLE
Missing stable branch?

### ISSUE THREAD

**Issue by mischw** [volatilityfoundation/volatility3#1148]
Hi. The Readme mentions the following:
https://github.com/volatilityfoundation/volatility3/blob/1b3ba6ab2ef6f086993ad382f68d9f01a4ae7bdf/README.md?plain=1#L44

It seems like the repository does not have a stable branch, but did at some point if I remember correctly. Is that some kind of transition where the stable branch may come back? I am wondering if I should adapt my build scripts. Thanks!

**Comment by ikelos** [comment]
Yep, there was a slight snafu yesterday where I push hundreds of old branches to github, and so had to clean them up.  Looks like stable went with them too, but it's now restored.  Thanks for letting us know!
