### ISSUE TITLE
Linux ISF Server Down

### ISSUE THREAD

**Issue by Dimefront-5** [volatilityfoundation/volatility3#1161]
I was reading the documentation at https://volatility3.readthedocs.io/en/latest/getting-started-linux-tutorial.html and went to the ISF server URL at https://isf-server.techanarchy.net/ and it didn't respond. Is this no longer up?

**Comment by eve-mem** [comment]
I'm not sure about isf server, however this repo by @Abyss-W4tcher has lots of symbols in. Worth a look: https://github.com/Abyss-W4tcher/volatility3-symbols

**Comment by ikelos** [comment]
Thanks, this is a third party service which we mention, we're not sure why it's not working, but you may also find that https://github.com/Abyss-W4tcher/volatility3-symbols works as a ISF server that can be integrated with volatility.  We're trying to track down why the service may have been affected, and hopefully resolve it, or if not we'll remove references to it from the documentation.  I hope that helps...

**Comment by Dimefront-5** [comment]
I'll check it out, thank you!

**Comment by ikelos** [comment]
@kevthehermit Is the ISF server still going, or should we change the documentation to point to Abyss-W4tcher's repo?

**Comment by kevthehermit** [comment]
It should be up in away today will check tomorrow see why it's offline

**Comment by kevthehermit** [comment]
Back up and running

**Comment by IreAlMar** [comment]
@kevthehermit  Is the server still going on? I've tried the page a couple of times but is seems down.
Thank you :)

**Comment by kevthehermit** [comment]
OK Im going to spend tonight refactoring the server looks like a python library update has broken it. 

Need to pin some libraries 

Back Up and i have some alerts in place now to warn me if its down again

**Comment by IreAlMar** [comment]
Great! Thanks a lot!

**Comment by kinging123** [comment]
Seems like it's down again.

**Comment by theonlymosmos** [comment]
down i think?

**Comment by eve-mem** [comment]
I'd recommend this now. https://github.com/Abyss-W4tcher/volatility3-symbols
