### ISSUE TITLE
Linux Network Connection Analysis

### ISSUE THREAD

**Issue by Dimefront-5** [volatilityfoundation/volatility3#1163]
**Is your feature request related to a problem? Please describe.**
Being able to examine network connections in a linux memory file

**Describe the solution you'd like**
A plugin like netstat and netscan developed to work for linux memory files

**Describe alternatives you've considered**
N/A

Maybe I am missing it somewhere but I don't see a way to examine network connections for linux memory files, I think this is very needed.

**Comment by gcmoreira** [comment]
https://volatility3.readthedocs.io/en/stable/volatility3.plugins.linux.sockstat.html

[sockstat](https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/plugins/linux/sockstat.py)

:)

**Comment by ikelos** [comment]
I'm going to mark this as closed, but please feel free to reopen if the `linux.sockstat` plugin doesn't do what you're after...

**Comment by gcmoreira** [comment]
Hey @Dimefront-5 , forgot to mention, re: `netstat` there's also an amazing contribution from @eve-mem which is called [sockscan](https://github.com/volatilityfoundation/volatility3/pull/1120) and is built on top of `sockstat` ... it's awaiting review but I guess it will be available soon. 

Feel free to use the `sockscan` plugin from the pull request and provide @eve-mem with some feedback. It would be much appreciated . In doing so, you'll be supporting both the author and this project.
