### ISSUE TITLE
Missing Plugin -> threads

### ISSUE THREAD

**Issue by mrratherford** [volatilityfoundation/volatility3#118]
As of volatility version 2 there were the three plugins: threads, timers and devicetree. I didn't find these plugins in the new version. Do you have plans to bring them back in or are these plugins by community developers?

**Comment by mrratherford** [comment]
Thanks for your quick reply!

**Comment by digitalisx** [comment]
Hello @mrratherford,
This time, I developed DeviceTree Plugin, one of the requests covered in this issue.
It was finally merged in the `develop` branch, so I would appreciate it if you could give me feedback after using it. 🙌

**Comment by superponible** [comment]
@ikelos I submitted a PR for this.  

Some work based on original implementation at https://github.com/digitalisx/volatility3/tree/feature/timers. 

The byte manipulation functions from https://github.com/volatilityfoundation/volatility3/pull/718/files#diff-e13d09e5ccbff35e090d1c91ba6ba0d3d59548f89b38ce97025d2e203b130975 were brought over.  I put them in utility.py to be available for both if that other PR gets merged. Not sure if that's the right place.

**Comment by ikelos** [comment]
> The byte manipulation functions from https://github.com/volatilityfoundation/volatility3/pull/718/files#diff-e13d09e5ccbff35e090d1c91ba6ba0d3d59548f89b38ce97025d2e203b130975 were brought over. I put them in utility.py to be available for both if that other PR gets merged. Not sure if that's the right place.

Sounds good, but I'll take a look during the review.  Thanks for the heads-up about the prior code, that'll save me scratching my head trying to recall!  5;D

**Comment by digitalisx** [comment]
`Timers` plugin has been implemented well, I can happily close the existing draft PR. :)
Thanks @superponible
