### ISSUE TITLE
Beginner Question: support for linux coredumps?

### ISSUE THREAD

**Issue by juxeii** [volatilityfoundation/volatility3#1188]
Total beginner here.
Does v3 support linux coredumps?

**Comment by ikelos** [comment]
I don't believe it does, coredumps are just a single processes memory I think and volatility is only really configured to work on a complete kernel memory dump.  Sorry for the time it too to reply, the issue tracker isn't the best place to ask questions.  You'll likely get as much quicker response from the community if you head over to our [slack channel](http://slack.volatilityfoundation.org/) and ask there...  5:)

**Comment by juxeii** [comment]
Thx. The slack link is not working.

**Comment by ikelos** [comment]
You're quite right, sorry about that.  I'll try to get that fixed and let you know once it's working...

**Comment by ikelos** [comment]
Sorry, my bad, it's not a separate domain, it's just https://www.volatilityfoundation.org/slack
