### ISSUE TITLE
Critical bug in VADs Yara scanning due to scanning only one page at a time

### ISSUE THREAD

**Issue by atcuno** [volatilityfoundation/volatility3#1189]
I was putting together a lab guide for an upcoming workshop and ran into a critical bug in the way Volatility processes Yara searches inside of VADs. In particular, we are scanning one page at a time, even for VADs that are beyond a page size. 

I am filing this as a ticket instead of me just fixing it as I am not comfortable enough with changing all the scanning internals. Also, scanning one page at a time is the best way in the physical/file layer since RAM has the pages scattered, but it needs to be scanning entire VADs at a time in process memory as otherwise we will miss valid hits as I will detail here in the ticket. Obviously, that will require skipping VADs over a certain size (1GB is probably a good boundary), since the yara library will need a string holding the entire VAD's contents at once.

Details of the bug are below:

This is a yara rule we have that students use in training against a sample infected with stuxnet:

```
rule s {
    strings:
        $b = "SeLoadDriverPrivilege" wide
        $a = "Realtek Semiconductor" wide
    condition:
        all of them
}
```

"all of them" means both strings have to be present.

I noticed that Volatility 3 did not report any hits with this rule even though Vol2 always has. Digging in, if I made the rule "any of them", which means if either are present, then we got hits:

```
 |   Offset |  PID | Rule | Component |                                                                                                                         Value
* | 0x8cda8c | 1928 | stux |        $a |                                                       53 00 65 00 4c 00 6f 00 61 00 64 00 44 00 72 00 69 00 76 00 65 00 72 00
* | 0x988424 | 1928 | stux |        $b |                                                                52 65 61 6c 74 65 6b 20 53 65 6d 69 63 6f 6e 64 75 63 74 6f 72
* | 0x988498 | 1928 | stux |        $b |                                                                52 65 61 6c 74 65 6b 20 53 65 6d 69 63 6f 6e 64 75 63 74 6f 72
* | 0x988945 | 1928 | stux |        $b | 52 00 65 00 61 00 6c 00 74 00 65 00 6b 00 20 00 53 00 65 00 6d 00 69 00 63 00 6f 00 6e 00 64 00 75 00 63 00 74 00 6f 00 72 00
```

```
>>> binascii.unhexlify("52 65 61 6c 74 65 6b 20 53 65 6d 69 63 6f 6e 64 75 63 74 6f 72".replace(" ",""))
'Realtek Semiconductor'

>>> binascii.unhexlify("53 00 65 00 4c 00 6f 00 61 00 64 00 44 00 72 00 69 00 76 00 65 00 72 00".replace(" ","").replace("00",""))
'SeLoadDriver'
```

But notice that the two strings are on different pages - 0x8cda8c for one and then the 0x98... for the others, but that those pages are inside the same VAD:

```
$ python3 vol.py -q -f stux.raw windows.vadinfo --pid 1928 --address 0x8cda8c
Volatility 3 Framework 2.7.1
PID	Process	Offset	Start VPN	End VPN	Tag	Protection	CommitCharge	PrivateMemory	Parent	File	File output

1928	lsass.exe	0x82232950	0x870000	0x9a7fff	Vad 	PAGE_EXECUTE_READWRITE	0	0	0x82386728	N/A	Disabled

$ python3 vol.py -q -f stux.raw windows.vadinfo --pid 1928 --address 0x988945
Volatility 3 Framework 2.7.1
PID	Process	Offset	Start VPN	End VPN	Tag	Protection	CommitCharge	PrivateMemory	Parent	File	File output

1928	lsass.exe	0x82232950	0x870000	0x9a7fff	Vad 	PAGE_EXECUTE_READWRITE	0	0	0x82386728	N/A	Disabled
```

For Vadyarascan to be usable in real investigations it needs to be sending an entire VADs worth of data to the yara library to scan, otherwise we will constantly have issues like this, and the vast majority of production rules have where more than one string must match for the rule to match. File/Physical layer scanning should stay on the 4096 boundary though so I am hoping there is some easy way to parameterize the chunk sizes.

This is where I verified the address being scanned and the amount of data per call:

https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/plugins/yarascan.py#L45

**Comment by eve-mem** [comment]
Yes, this is one that would be good to fix. It's also mentioned here https://github.com/volatilityfoundation/volatility3/issues/1155
