### ISSUE TITLE
Unable to validate the plugin requirements: ['plugins.SSDT.modules']

### ISSUE THREAD

**Issue by hodenkobold99** [volatilityfoundation/volatility3#1244]
**Describe the bug**
SSDT Plugin not working. I cloned the development branch today and since that the SSDT Plugin command doesn't work anymore.
I also tried the SSDT Plugin with a clean Volatility3 2.7.0 from May 29 and it works fine.

**Context**
Volatility Version:  2.7.0 - dev branch
Operating System: Windows 10  
Python Version:  3.12.4
Suspected Operating System:  Windows 10
Command:  SSDT Plugin

**To Reproduce**
See Output

**Example output**
PS C:\Users\michael\Desktop\volatilityfoundation-volatility3-c524d8a> python .\vol.py -f "C:\Users\michael\Desktop\RAM Analyse\20240716.mem" -vvv windows.ssdt.SSDT
Volatility 3 Framework 2.9.0
INFO     volatility3.cli: Volatility plugins path: ['C:\\Users\\michael\\Desktop\\volatilityfoundation-volatility3-c524d8a\\volatility3\\plugins', 'C:\\Users\\michael\\Desktop\\volatilityfoundation-volatility3-c524d8a\\volatility3\\framework\\plugins']
INFO     volatility3.cli: Volatility symbols path: ['C:\\Users\\michael\\Desktop\\volatilityfoundation-volatility3-c524d8a\\volatility3\\symbols', 'C:\\Users\\michael\\Desktop\\volatilityfoundation-volatility3-c524d8a\\volatility3\\framework\\symbols']
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT.kernel
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.kernel.layer_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.kernel.layer_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT.kernel
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT.kernel
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT
INFO     volatility3.framework.automagic: Running automagic: SymbolCacheMagic
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DEBUG    volatility3.framework.automagic.windows: Detecting Self-referential pointer for recent windows
DEBUG    volatility3.framework.automagic.windows: DtbSelfRef64bit test succeeded at 0x1aa000
DEBUG    volatility3.framework.automagic.windows: DTB was found at: 0x1aa000
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT.kernel
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.kernel.layer_name.memory_layer
DETAIL 1 volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
DETAIL 1 volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
DETAIL 1 volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
DETAIL 1 volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT.kernel
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT
DEBUG    volatility3.framework.automagic.stacker: physical_layer maximum_address: 4831838207
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.kernel.symbol_table_name
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf80046600000
DEBUG    volatility3.framework.symbols.windows.pdbutil: Using symbol library: ntkrnlmp.pdb\2F5ADEE106E341E8FE0539A8EEA780C1-1
INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
DEBUG    volatility3.schemas: All validations will report success, even with malformed input
INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
INFO     volatility3.framework.automagic: Running automagic: KernelModule

Unsatisfied requirement plugins.SSDT.modules:
Unable to validate the plugin requirements: ['plugins.SSDT.modules']

**Comment by Abyss-W4tcher** [comment]
Hello, following a recent upgrade in the `modules` plugin, it seems that some depending plugins weren't updated accordingly : 

https://github.com/volatilityfoundation/volatility3/blob/c524d8a3d1305c3abef499a9e0af8844d956d69f/volatility3/framework/plugins/windows/ssdt.py#L33

https://github.com/volatilityfoundation/volatility3/blob/c524d8a3d1305c3abef499a9e0af8844d956d69f/volatility3/framework/plugins/windows/verinfo.py#L49

To fix this issue on your side, please bump the version to `(2, 0, 0)`. If any error occurs, please follow up on this issue.

**Comment by hodenkobold99** [comment]
Thank you very much, it works now as expected!
