### ISSUE TITLE
IndexError: Member not present in template: PrcbData

### ISSUE THREAD

**Issue by Balaji2520** [volatilityfoundation/volatility3#1275]
![Screenshot (1)](https://github.com/user-attachments/assets/7046af4c-4398-4328-94d4-094a7b7c7983)

**Comment by ikelos** [comment]
When reporting an issue, we ask you to fill out the template and provide the requested information and include a *text* version of the response you're getting.  Including just a screenshot does not allow searching or indexing, making your issue harder for people to search for and more difficult for the developers to work on.

The template explicitly requests that you run volatility with at least `-vvv` to save us having to ask people to resubmit their bug request with the required information.  We cannot diagnose an issue that doesn't contain enough information, particularly when the information is does contain is just a screenshot.

Closing this until more usable information is provided, feel free to reopen it with a text based response that includes the requested information.
