### ISSUE TITLE
Sort volshell methods alphabetically

### ISSUE THREAD

**Issue by iMHLv2** [volatilityfoundation/volatility3#1296]
By default, the volshell methods (`hh()` output) are not sorted alphabetically. In this case, I knew `cp` was a method and wanted to read the description, but couldn't it find it anywhere near `cl` or `cs`. 

<img width="1091" alt="image (1)" src="https://github.com/user-attachments/assets/2031f28d-ee8d-4af7-be1b-2953b2238540">

**Comment by ikelos** [comment]
Cool, thanks for logging a ticket again the change.  I'm not sure why I did them in such a weird order or why I didn't think to sort them, but thanks for getting it fixed!  5:)
