### ISSUE TITLE
windows.pstree output too much data.  Support hiding columns

### ISSUE THREAD

**Issue by atcuno** [volatilityfoundation/volatility3#1302]
The existing windows.pstree plugin is currently unusable from the command line as it reports the path multiple times and line wraps (even multiple wraps in many instances) for every single process. Even with the smallest of fonts, it still wraps each process at least once to a new line.

The main intended purpose of pstree is to let users visually see the parent/child relationship, which right now does not work at all.

Since pstree has been merged in this form for a while, we want to know what the best way forward is to get a reasonable output that users can visually see the parent/child relationship.

Potential options:

1) Remove all the unneeded columns from the existing pstree, and then version bump as needed.

2) Make something like a `--minimal` flag to pstree that only reports necessary columns and that won't wrap. But from the past, I don't think these options were viewed well.

3) Make a windows.pstree_minimal new plugin that reports the tree with just the columns needed for further analysis and that won't wrap. Implementing this would be very trivial.

Thoughts @ikelos ? I am leaning towards 3 in terms of not breaking existing flows, but even with that, the current pstree is completely unusable, and we would have to teach students not to use it and always run `pstree_minimal` instead to get usable results.

**Comment by ikelos** [comment]
Sounds like we just need to get #1085 across the line?

**Comment by ikelos** [comment]
I clearly had my hesitations about the tack I took, so I'll need to revisit it and see if I can figure out what made me uneasy about it.  I think it was the request to allow plugins to define what their own default columns to display was...  I should be able to rip it down to just the user deciding though, that should be straightforward and problem free.

**Comment by atcuno** [comment]
Yes, that would solve it all. Perfect
