### ISSUE TITLE
Volatility can't load a single process dump from Process Explorer

### ISSUE THREAD

**Issue by itsallmathematics** [volatilityfoundation/volatility3#1322]
**Describe the bug**
I honestly don't understand what this bug is about due to lack of experience with this project. I searched the text of this error and have gotten several other bugs with the same error text but which seems to have been entirely different issues. For example, one issue the root problem is that `yara-python` or `yara` wasn't installed. In other cases, it seems that the Windows symbols need to be updated, but in this case I'm running a pretty recent version of Volatility3, plus from what I understand, Volatility3 should be fetching them automatically from the Internet anyway, so I suppose that's not the issue, as the work computer is happily connected to the Internet.

What I can also tell you is that when I run the command `vol --cache-path ~/volatility_cache -f ~/Downloads/conhost_DUMP.dmp banners`, this is what I get (nothing):

```
Volatility 3 Framework 2.8.0
Progress:  100.00		PDB scanning finished                  
Offset	Banner

```

Lastly, the reason I put `--cache-path ~/volatility_cache` is because I saw yet another closed issue on here with these error messages in which the solution in that case was to specify a `--cache-path`, but evidently that is also not the problem in my case. I was almost going to try the whole dance of trying to fetch the Windows symbols myself manually, convert them to json etc... But I decided to post this first as it would still be a bug and as aforementioned, I Believe that Volatility3 should be doing this anyway.
**Context**
Volatility Version:  2.8.0
Operating System:  Fedora 40
Python Version:  3.12.4
Suspected Operating System:  Windows 11 (exact build unknown)
Command:  `/home/itsallmathematics/.local/bin/vol -vvv --cache-path ~/volatility_cache  -f ~/Downloads/conhost_DUMP.dmp windows.info`
`file ./conhost_DUMP.dmp: Mini DuMP crash report, 16 streams, Fri Oct 25 03:43:06 2024, 0x201806 type`

**NOTE:** I also tried it with other commands, such as `windows.info.Info`, `windows.pslist`, and `imageinfo` seems to also not be a command at all anymore, or at least is unrecognized.

**To Reproduce**

1. Dump a running `conhost.exe` on Windows 11 using Process Explorer; mine is around 85MB.
2. Try to load it with the above command, see errors.

**Expected behavior**
Volatility3 successfully parses the `.dmp` file.

**Example output**
```
itsallmathematics@localhost ~/.l/l/p/s/v/f/s/windows [1]> /home/itsallmathematics/.local/bin/vol -vvv --cache-path ~/volatility_cache  -f ~/Downloads/conhost_DUMP.dmp windows.info
Volatility 3 Framework 2.8.0
INFO     volatility3.cli: Volatility plugins path: ['/home/itsallmathematics/.local/lib/python3.12/site-packages/volatility3/plugins', '/home/itsallmathematics/.local/lib/python3.12/site-packages/volatility3/framework/plugins']
INFO     volatility3.cli: Volatility symbols path: ['/home/itsallmathematics/.local/lib/python3.12/site-packages/volatility3/symbols', '/home/itsallmathematics/.local/lib/python3.12/site-packages/volatility3/framework/symbols']
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info
INFO     volatility3.framework.automagic: Running automagic: SymbolCacheMagic
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DEBUG    volatility3.framework.automagic.windows: Detecting Self-referential pointer for recent windows
DEBUG    volatility3.framework.automagic.windows: Older windows fixed location self-referential pointers
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: TypeError - Layer is not the required Architecture: FileLayer
DEBUG    volatility3.framework.automagic.stacker: physical_layer maximum_address: 88678274
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
INFO     volatility3.framework.automagic.pdbscan: No suitable kernels found during pdbscan
INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
INFO     volatility3.framework.automagic: Running automagic: KernelModule
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name

Unsatisfied requirement plugins.Info.kernel.layer_name: 
Unsatisfied requirement plugins.Info.kernel.symbol_table_name: 

A translation layer requirement was not fulfilled.  Please verify that:
	A file was provided to create this layer (by -f, --single-location or by config)
	The file exists and is readable
	The file is a valid memory image and was acquired cleanly

A symbol table requirement was not fulfilled.  Please verify that:
	The associated translation layer requirement was fulfilled
	You have the correct symbol file for the requirement
	The symbol file is under the correct directory or zip file
	The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.kernel.layer_name', 'plugins.Info.kernel.symbol_table_name']
```

**Additional information**
I actually tried this file on 2 machines, both running Fedora and Python of different versions (the old one, I won't bother to mention as it's outdated and unsupported anyway), it happened on both, so I think it's safe to say this isn't just a fluke issue specific to one machine. **I am sorry to say that I cannot provide the exact `.DMP` file as it is confidential information... But there should be nothing super crazy about it, I collected it as aforementioned.**

**Comment by 9x14S** [comment]
I'm having the same issue on Fedora 40, using Python 3.12.7 on both the latest stable branch version (2.8.0) and the latest develop branch version (2.11.0)

**Comment by ikelos** [comment]
Hi there, it sounds like you've only dumped an individual process, not a complete memory dump.  Volatility can't operate on just a single process, it requires a full and complete memory image where it then tries to locate a kernel.  The kernel requirement is a set of symbols and a layer (at the moment, an intel layer).  Volatility tries several heuristics to determine whether there's an intel layer, then locate the kernel within it and then use that information to determine what symbols it may need (which for windows it can then go and recover the information it needs from the internet).

A single process isn't an Intel layer (it's from the virtual space, so there's no mapping recorded) and there's no kernel to find there, because the kernel process isn't included in a single process dump.  Volatility plugins work based on requirements, and the main requirement for the plugin you tried couldn't be satisified for those two reasons.

Hopefully that clarifies some of the issues you were having.  If you manage to acquire a complete memory image the following line:
 ```
 DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['FileLayer']
 ```
 Will likely include an `IntelLayer` at the start of the list.  I'm going to close this off because there isn't a great deal more we can do with a single process dump, but feel free to reopen it if you feel there's still an underlying issue with Volatility.

**Comment by itsallmathematics** [comment]
@ikelos I'm wondering if I couldn't make a PR of some code that recognizes this and warns the user.

**Comment by ikelos** [comment]
You're welcome to try, but it won't be easy?  There are no markers to differentiate "raw memory from just a process" from "raw memory from a whole kernel".  If there's a fixed format for minidumps you might be able to warn on that, otherwise it'd be warning on the memory layer being small, so you'd need to pick an arbitrary size for when to warn over.  Virtual machines can make their memory images quite small (a few 100 Mbs) so it's doable but might catch false positives/true negatives depending on the limit you set...

**Comment by itsallmathematics** [comment]
> You're welcome to try, but it won't be easy? There are no markers to differentiate "raw memory from just a process" from "raw memory from a whole kernel". If there's a fixed format for minidumps you might be able to warn on that, otherwise it'd be warning on the memory layer being small, so you'd need to pick an arbitrary size for when to warn over. Virtual machines can make their memory images quite small (a few 100 Mbs) so it's doable but might catch false positives/true negatives depending on the limit you set...

There actually is a fixed format for minidumps AFAIK. That might work, thanks!
