### ISSUE TITLE
Missing Vol3 plugins

### ISSUE THREAD

**Issue by wilsq36** [volatilityfoundation/volatility3#1355]
Two questions:

Where is an actual list of all the plugins available?

Where is the windows.hivedump.Hivedump plugin?

Thank you,

Emily

**Comment by eve-mem** [comment]
If you run --help you'll get a complete list. 

Make sure you've installed the requirements in order to see all plugins.

**Comment by eve-mem** [comment]
Is it hivelist with the --dump option you're after?

https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3%2Fframework%2Fplugins%2Fwindows%2Fregistry%2Fhivelist.py#L41-L70

**Comment by wilsq36** [comment]
> Is it hivelist with the --dump option you're after?
> 
> https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3%2Fframework%2Fplugins%2Fwindows%2Fregistry%2Fhivelist.py#L41-L70

That does not contain any dump commands.

The plugin is windows.registry.hivedump.Hivedump but doesn't appear anywhere.



> If you run --help you'll get a complete list.
> 
> Make sure you've installed the requirements in order to see all plugins.

Not listed in there. Must not be an option in Vol3 as in Vol2

**Comment by eve-mem** [comment]
You should see the dump option here: https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3%2Fframework%2Fplugins%2Fwindows%2Fregistry%2Fhivelist.py#L64-L68

**Comment by ikelos** [comment]
Hivelist is one of the default plugins available with volatility3, please verify your installation (or redownload it from github to get the latest version).  If volatility cannot load one of the plugins it should print a warning at the start of the `--help` output.  I don't believe that the registry plugins require any additional modules though, so there's no obvious reason why this shouldn't work for you...  Please note that plugin parameters have to be placed *after* the plugin name and global parameters have to be placed before it (so `vol.py -f mem.img --dump registry.hivelist` won't work, but `vol.py -f mem.img registry.hivelist --dump` should work.

**Comment by wilsq36** [comment]
I'm not talking about hivelist.

**Comment by atcuno** [comment]
> I'm not talking about hivelist.

`hivelist` with `--dump` set is the equivalent replacement in Volatility 3

**Comment by wilsq36** [comment]
Ok, thanks for the clarification.
