### ISSUE TITLE
Error: Unable to validate the plugin requirements: ['plugins.Info.kernel.symbol_table_name']

### ISSUE THREAD

**Issue by ShanikaCPerera** [volatilityfoundation/volatility3#1372]
I'm trying to analyze a Windows 11 memory dump file and getting this error after "Scanning memory layer using ByteScanner". I have attached the full output in a text doc.

[Full output.txt](https://github.com/user-attachments/files/17962486/Full.output.txt)

I see similar errors like below for many jsons. "volatility3.framework.automagic.symbol_cache: No identifier found for file:///C:/Users/wadduwage/volatility3/volatility3/framework/symbols/windows/poolheader-x64.json"

Also errors related to age fault: "DEBUG volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset caused a page fault: 0xf80359717000"

Below is the last part of the output:

DEBUG volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG volatility3.framework.automagic.pdbscan: Kernel base determination - testing fixed base address
DETAIL 4 volatility3.framework.automagic.pdbscan: Testing potential kernel for ntkrnlmp.pdb at 4907653136 with MZ offset at 4907335680
DEBUG volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset caused a page fault: 0xf80124800000
DETAIL 4 volatility3.framework.automagic.pdbscan: Testing potential kernel for ntoskrnl.pdb at 11477683072 with MZ offset at 11473076224
DEBUG volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset caused a page fault: 0xf802abd94000
DETAIL 4 volatility3.framework.automagic.pdbscan: Testing potential kernel for ntoskrnl.pdb at 14386382868 with MZ offset at 14385508352
DEBUG volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset caused a page fault: 0xf80359717000
DETAIL 4 volatility3.framework.automagic.pdbscan: Testing potential kernel for ntkrnlmp.pdb at 23000061968 with MZ offset at 22998695936
DEBUG volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset caused a page fault: 0xf8055ad44000
DETAIL 4 volatility3.framework.automagic.pdbscan: Testing potential kernel for ntoskrnl.pdb at 34013219712 with MZ offset at 34008604672
DEBUG volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset caused a page fault: 0xf807eb122000
DEBUG volatility3.framework.automagic.pdbscan: Kernel base determination - optimized scan virtual layer
DEBUG volatility3.framework.automagic.pdbscan: Kernel base determination - slow scan virtual layer
INFO volatility3.framework.automagic.pdbscan: No suitable kernels found during pdbscan
INFO volatility3.framework.automagic: Running automagic: SymbolFinder
INFO volatility3.framework.automagic: Running automagic: KernelModule
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name

Unsatisfied requirement plugins.Info.kernel.symbol_table_name:

A symbol table requirement was not fulfilled. Please verify that:
The associated translation layer requirement was fulfilled
You have the correct symbol file for the requirement
The symbol file is under the correct directory or zip file
The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.kernel.symbol_table_name']

What could be the reason for this issue?

**Comment by ikelos** [comment]
This message:
```
volatility3.framework.automagic.symbol_cache: No identifier found for file:///C:/Users/wadduwage/volatility3/volatility3/framework/symbols/windows/poolheader-x64.json
```
Is perfectly normal and not an error, the poolheader-x64.json is a (and others are) handcrafted JSON file for a specific purpose, rather than containing all the data for a kernel (including an identifier).  You can safely ignore those messages for any file under `volatility/framework`.

The page faults are a bigger problem.  It's attempting to locate the MZ header from a possible kernel it found but during reading that, it hit a page fault (it tried to read from memory that wasn't mapped) and so it wasn't able to find the information about the kernel it needed in order to download and create the symbols for it.

We're seeing quite a few of these, these days so it could be that volatility's heuristics aren't working, or the memory is getting more spreadout and our attempted to find the matching MZ header aren't working, but at the moment that image looks like it can't be scanned I'm afraid...

**Comment by derekeiri** [comment]
Good day.

I believe I'm observing a similar issue. Pulled a clone today and noted the message: 
`Unable to validate the plugin requirements: ['plugins.Info.kernel.symbol_table_name']`

[fulloutput-20241213.txt.txt](https://github.com/user-attachments/files/18134819/fulloutput-20241213.txt.txt)

Certainly not as many page faults as ShanikaCPerera's sample, though:
`DEBUG    volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset caused a page fault: 0xf80002800000`

On the other hand, using the release Volatility 3 2.8.0, it works as expected.
[fulloutput-20241213_Volatility3v2.8.0.txt](https://github.com/user-attachments/files/18134825/fulloutput-20241213_Volatility3v2.8.0.txt)

**Comment by ikelos** [comment]
Hmmm, so `= 2.8.0` found it during the layer module list structure, but `> 2.8.0` missed it?  @derekeiri would you be able to share your memory image so that we can examine it please?  The slow finder should have found it if it were present, so that's potentially quite a significant issue...  5:S

**Comment by derekeiri** [comment]
Thanks, @ikelos.

The owner of the image suggests it's not a Volatility issue as he wasn't able to reproduce it for > 2.8.0. He was able to successfully run it using 2.12.0. Based on this, I suspect it's something specific with my machines, my process for cloning the repo, or _me_. Running through the same process with another sample to be sure:

I replicated my issue using a different image here:
https://github.com/teambi0s/InCTFi/tree/master/2020/Forensics/Investigation

Using a fresh install of WSL 2 (v2.3.26.0) with Ubuntu 22.04 LTS running on a Win11 Pro machine. I did the same test on a separate machine running Ubuntu 22.04 LTS with similar results. The text files below are from the Win11 Pro machine.

Reviewing the branches, I can successfully run the plugin windows.info for v2.11.0.
[20241216_vol3_branch_release_v2110.txt](https://github.com/user-attachments/files/18161282/20241216_vol3_branch_release_v2110.txt)

I was able to replicate the ['plugins.Info.kernel.symbol_table_name'] for the following branches:
volatility3-issues-issue1367 
[20241216_vol3_branch_issue1367.txt](https://github.com/user-attachments/files/18161302/20241216_vol3_branch_issue1367.txt)

volatility3-feature-scan-one-layer-deep 
[20241216_vol3_branch_release_feat_scan_one_layer_deep.txt](https://github.com/user-attachments/files/18161307/20241216_vol3_branch_release_feat_scan_one_layer_deep.txt)

I get a new error with the development release as of approximately 06:00:00 on 2024-12-17 UTC. 
[20241216_vol3_dev.txt](https://github.com/user-attachments/files/18161326/20241216_vol3_dev.txt)

 Thank you for your time and attention.

Edit: Made several edits to include more information.

**Comment by ikelos** [comment]
Yep, that last issue has been fixed (as soon as I ran into it too).  5;P  The latest commit should take care of it.  As for the other issues, it's hard to tell, but at least it's not longer happening.  The fact that it happens on two unrelated branches, means it should get fixed up when they're rebased for merge.

Thanks very much for your investigative work!  Since you don't seem to be experiencing the problem in the very latest version, I'm going to mark this as closed, but feel free to reopen if you think the issue still exists.  5:)
