### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bittib010** [volatilityfoundation/volatility3#1379]
A simple typo found on a module: windows.**suspi**cious_threads.**Supsi**ciousThreads (Supsi... should be suspi...)

**Comment by ikelos** [comment]
Thanks very much for the report, I think someone beat you to it though.  It's already been fixed in main in commit b37ba26dd62a9cc85c89e174c20f1afe549eb753...  5:)

**Comment by ikelos** [comment]
It was only fixed last month though so it won't be in the official release until the next one (which is scheduled to come out before the end of the year).  5:)
