### ISSUE TITLE
File rename error with  windows.pslist.PsList --dump plugin on Windows (illegal character use)

### ISSUE THREAD

**Issue by mmcjcc** [volatilityfoundation/volatility3#1387]
**Describe the bug**
When using the windows.pslist.PsList --pid  --dump plugin on Windows, the .dmp file is not generated. It appears that a .tmp file of the dump is created, but then the program tries to rename it with an invalid character (?), which fails on Windows. 

**Context**
Volatility Version:  Volatility 3 Framework 2.12.0 (and latest stable)
Operating System:  Windows 10
Python Version:  3.8
Suspected Operating System:  
Command:  python vol.py   -f c:\Users\Administrator\Downloads\Win10-MalTest-ae85e0f6\Win10-MalTest-ae85e0f6.vmem windows.pslist.PsList --pid 3188 --dump

**To Reproduce**

1. Use command  use the pslist plugin to attempt to dump a process memory with the --pid and --dump switches
2. See error

**Expected behavior**
.dmp file created. However, I have a .tmp file because the rename of the file is failing because of the ? character not being valid on Windows.  The .tmp file is the process memory, it just is not being renamed as expected. 

**Example output**
python vol.py   -f c:\Users\Administrator\Downloads\Win10-MalTest-ae85e0f6\Win10-MalTest-ae85e0f6.vmem windows.pslist.PsList --pid 3188 --dump
Volatility 3 Framework 2.12.0
Progress:  100.00               PDB scanning finished
PID     PPID    ImageFileName   Offset(V)       Threads Handles SessionId       Wow64   CreateTime      ExitTime                File output
Traceback (most recent call last):
  File "vol.py", line 11, in <module>
    volatility3.cli.main()
  File "C:\Users\Administrator\volatility3\volatility3\cli\__init__.py", line 917, in main
    CommandLine().run()
  File "C:\Users\Administrator\volatility3\volatility3\cli\__init__.py", line 505, in run
    renderer.render(grid)
  File "C:\Users\Administrator\volatility3\volatility3\cli\text_renderer.py", line 232, in render
    grid.populate(visitor, outfd)
  File "C:\Users\Administrator\volatility3\volatility3\framework\renderers\__init__.py", line 245, in populate
    for level, item in self._generator:
  File "C:\Users\Administrator\volatility3\volatility3\framework\plugins\windows\pslist.py", line 283, in _generator
    file_handle.close()
  File "C:\Users\Administrator\volatility3\volatility3\cli\__init__.py", line 842, in close
    os.rename(self._name, output_filename)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\Administrator\\volatility3\\tmp_c4yb_gz6.vol3' -> 'C:\\Users\\Administrator\\volatility3\\3188.?WanaDecryptor.0x400000.dmp'

Text is preferred to screenshots for searching and to talk about specific parts of the output.

**Additional information**
Add any other information about the problem here.

Tried this on the latest stable and latest dev versions with same result. This worked in previous versions.

**Comment by eve-mem** [comment]
Hello 👋 

I may be completely wrong, but given the name of Wana Decryptor I'm thinking that perhaps windows defender might be getting involved? Maybe some kind of heuristic match on that part of memory?

Are you able to check those defender logs? (Or another antivirus)

**Comment by eve-mem** [comment]
Thank you for that report.

**Comment by ikelos** [comment]
So we do have a sanitization function:
https://github.com/volatilityfoundation/volatility3/pull/999#issuecomment-1766597355
But it looks like I was a little too forgiving, given windows filename.
https://github.com/volatilityfoundation/volatility3/blob/2ae723513abe12920f50bbe46b9ff3de44aafa74/volatility3/framework/interfaces/plugins.py#L63

@eve-mem If you've got a windows box there, could you please check through the list in the link above and let me know which characters in this list are allowed in a filename please?  I can trim the list pretty quickly and that should solve the issue...  5:)

**Comment by eve-mem** [comment]
It looks like Microsoft were kind enough to provide a list already:

https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

> Use any character in the current code page for a name, including Unicode characters and characters in the extended character set (128–255), except for the following:
> 
>     The following reserved characters:
>         < (less than)
>         > (greater than)
>         : (colon)
>         " (double quote)
>         / (forward slash)
>         \ (backslash)
>         | (vertical bar or pipe)
>         ? (question mark)
>         * (asterisk)


I'll verify this on an actual windows device and then submit the a PR with the fix.

**Comment by mmcjcc** [comment]
Thank you all for addressing this issue.

**Comment by eve-mem** [comment]
Things only get fixed if people report them. Thanks for reporting it, any more you find do post them here or the slack.
