### ISSUE TITLE
linux.pagecache plugins breaks dumping convention, needs to be converted

### ISSUE THREAD

**Issue by atcuno** [volatilityfoundation/volatility3#1392]
This plugin uses its own method to extract a file which really breaks the flow of people trying to learn Volatility 3 as well as trying to teach it to them. It also breaks the nice feature `-o` for an output directory.

https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/plugins/linux/pagecache.py#L521

```
Volatility 3 Framework 2.11.0
usage: volatility linux.pagecache.InodePages [-h] [--find FIND] [--inode INODE] [--dump DUMP]

optional arguments:
  -h, --help     show this help message and exit
  --find FIND    Filename (full path) to find
  --inode INODE  Inode address
  --dump DUMP    Output file path
```

So people send in a string as a `--dump` argument.

The plugin needs to use `--dump` like all the other plugins for consistency.

**Comment by atcuno** [comment]
@ikelos the code for this looks good but I am not sure what, if any, version bumps are required. Otherwise its ready

**Comment by gcmoreira** [comment]
@ikelos this can be closed, thanks
