### ISSUE TITLE
Linux pslist is missing uid and gid columns. Also missing from cred extension

### ISSUE THREAD

**Issue by atcuno** [volatilityfoundation/volatility3#1410]
The Linux pslist plugin has been missing the user and group ID since inception... this makes it really hard (often impossible) to determine which user and permissions a process is actually running as.

We had to work this into Volatility for a training as otherwise it was impossible to fully understand the malware incident, but this ticket is for getting added it properly.

@gcmoreira can you tackle this one? It makes sense to me to add the UID and GID after PPID.

You can take this code from a training branch to add the helpers for them:

https://github.com/volatilityfoundation/volatility3/commit/775daddbc3f203e2adb03ad8e68f8ca88f749bc0

**Comment by gcmoreira** [comment]
@atcuno Hm, I think we should display the `euid` and the `egid`. Even the `ps` command shows the effective IDs:
``` 
$ man 1 ps
...
       egid        EGID      effective group ID number of the process as a decimal integer.  (alias gid).
       euid        EUID      effective user ID (alias uid).
```
The real IDs only indicate the user and group that started the process.

Alternatively, we could show all four identifiers, real and effective, for full transparency.

**Comment by atcuno** [comment]
All four is good then... Right now its just extremely painful/impossible to track down user activity and processes spawned by them.

**Comment by gcmoreira** [comment]
@ikelos this can be closed, thanks
