### ISSUE TITLE
malfind has incorrect variable references

### ISSUE THREAD

**Issue by atcuno** [volatilityfoundation/volatility3#1444]
1) `proc_id` might not be set here if it is what causes the exception:

https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/plugins/windows/malfind.py#L109

2) The page variable is assigned way away from this error message and it might not even hold the value from the current loop iteration:

https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/plugins/windows/malfind.py#L158C105-L158C109

**Comment by Abyss-W4tcher** [comment]
Hi,

proc_id is declared before the for loop: 
https://github.com/volatilityfoundation/volatility3/blob/29485d6738c9966fc9ffd449830ae02a0bc4b1e6/volatility3/framework/plugins/windows/malfind.py#L103

I submitted a PR for the second small bug, which was introduced recently.

**Comment by atcuno** [comment]
It is the reference to `proc_id` here that is problematic:

https://github.com/volatilityfoundation/volatility3/blob/29485d6738c9966fc9ffd449830ae02a0bc4b1e6/volatility3/framework/plugins/windows/malfind.py#L158

**Comment by Abyss-W4tcher** [comment]
`proc_id` should at least be `Unknown` in this case ?
