### ISSUE TITLE
Demangle VC++ names from PDB

### ISSUE THREAD

**Issue by tklengyel** [volatilityfoundation/volatility3#157]
The Windows kernel PDBs contain a lot of constants that are currently saved in the json in their mangled format, such as:

```
"??_C@_1BM@FMDCFHKI@?$AAM?$AAe?$AAm?$AAo?$AAr?$AAy?$AAM?$AAa?$AAn?$AAa?$AAg?$AAe?$AAr@NNGAKEGL@": {
      "address": 7877184
    },
```

In the Rekall version of the JSON we can see the unmangled version of such strings:

```
  "str:MemoryManager": 7877184, 
```

Implementing something similar to [Rekall's Demangler](https://github.com/google/rekall/blob/8db49aa92439d4787023c1ea37561b6903cabf9b/rekall-core/rekall/plugins/overlays/windows/pe_vtypes.py#L1057) would improve the usefulness of the Volatility IST jsons.

**Comment by ikelos** [comment]
Thanks for the suggestion.  Do you have a specific scenario in mind where you'd make use of those names?  There are means to do proper demangling (which we've investigated) including shelling out to llvm to do it, but they've all been suboptimal for one reason or another.

I'd be more keen on creating a sanitzer that would allow the symbols to be more easily referenced within volatility, but I'm not sure including special symbols (such as the colon from your example) will make them easier to access from inside the code?

I'm not much of a C/C++ person myself though, so I'll pass this over to our symbols guy to see if he has any thoughts on the matter...  5:)

**Comment by tklengyel** [comment]
We are using these jsons outside Volatility (with [LibVMI](https://github.com/libvmi/libvmi)), so it would be preferred if the json itself has the demangled strings. There is no particular scenario (other then general reverse engineering stuff), but we would like to see feature parity betweet the Volatility jsons and the Rekall jsons. Since Rekall became unmaintained it has been a pain to get it working with newer versions of Python so we'd like to drop it as soon as possible.
