### ISSUE TITLE
Yara Plugin Error

### ISSUE THREAD

**Issue by Antonlovesdnb** [volatilityfoundation/volatility3#179]
I am getting the following error when using the Yara plugin: 

_ValueError: compile() missing a required argument_

**The full output:** 

> Volatility 3 Framework 1.0.0-beta.1
> INFO     root        : Volatility plugins path: ['/home/anton/Desktop/volatility3/volatility/plugins', '/home/anton/Desktop/volatility3/volatility/framework/plugins']
> INFO     root        : Volatility symbols path: ['/home/anton/Desktop/volatility3/volatility/symbols', '/home/anton/Desktop/volatility3/volatility/framework/symbols']
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.statistics
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.registry.certificates
> DEBUG    volatility.framework: Importing module: volatility.plugins.layerwriter
> DEBUG    volatility.framework: Importing module: volatility.plugins.frameworkinfo
> DEBUG    volatility.framework: Importing module: volatility.plugins.timeliner
> DEBUG    volatility.framework: Importing module: volatility.plugins.yarascan
> DEBUG    volatility.framework: Importing module: volatility.plugins.configwriter
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.check_syscall
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.tasks
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.proc_maps
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.bash
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.psaux
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.check_sysctl
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.netstat
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.trustedbsd
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.lsmod
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.ifconfig
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.malfind
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.pslist
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.lsof
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.pstree
> DEBUG    volatility.framework: Importing module: volatility.plugins.mac.check_trap_table
> DEBUG    volatility.framework: Importing module: volatility.plugins.linux.check_syscall
> DEBUG    volatility.framework: Importing module: volatility.plugins.linux.elfs
> DEBUG    volatility.framework: Importing module: volatility.plugins.linux.bash
> DEBUG    volatility.framework: Importing module: volatility.plugins.linux.proc
> DEBUG    volatility.framework: Importing module: volatility.plugins.linux.check_afinfo
> DEBUG    volatility.framework: Importing module: volatility.plugins.linux.lsmod
> DEBUG    volatility.framework: Importing module: volatility.plugins.linux.malfind
> DEBUG    volatility.framework: Importing module: volatility.plugins.linux.pslist
> DEBUG    volatility.framework: Importing module: volatility.plugins.linux.lsof
> DEBUG    volatility.framework: Importing module: volatility.plugins.linux.pstree
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.callbacks
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.poolscanner
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.verinfo
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.psscan
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.driverscan
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.dlldump
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.modscan
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.driverirp
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.procdump
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.vadyarascan
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.ssdt
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.handles
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.virtmap
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.strings
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.moddump
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.mutantscan
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.svcscan
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.cmdline
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.dlllist
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.modules
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.vadinfo
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.symlinkscan
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.info
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.filescan
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.malfind
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.pslist
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.vaddump
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.pstree
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.registry.printkey
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.registry.hivelist
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.registry.hivedump
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.registry.hivescan
> DEBUG    volatility.framework: Importing module: volatility.plugins.windows.registry.userassist
> DEBUG    volatility.framework: Importing module: volatility.framework.automagic.symbol_finder
> DEBUG    volatility.framework: Importing module: volatility.framework.automagic.windows
> DEBUG    volatility.framework: Importing module: volatility.framework.automagic.pdbscan
> DEBUG    volatility.framework: Importing module: volatility.framework.automagic.construct_layers
> DEBUG    volatility.framework: Importing module: volatility.framework.automagic.stacker
> DEBUG    volatility.framework: Importing module: volatility.framework.automagic.mac
> DEBUG    volatility.framework: Importing module: volatility.framework.automagic.symbol_cache
> DEBUG    volatility.framework: Importing module: volatility.framework.automagic.linux
> INFO     volatility.framework.automagic: No plugin category detected
> INFO     volatility.framework.automagic: Running automagic: SymbolBannerCache
> INFO     volatility.framework.automagic: Running automagic: MacBannerCache
> INFO     volatility.framework.automagic: Running automagic: LinuxBannerCache
> INFO     volatility.framework.automagic.symbol_cache: Building linux caches...
> INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
> Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.YaraScan.primary
> Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.YaraScan.primary
> Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.YaraScan.primary
> Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.YaraScan.primary
> Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.YaraScan
> Level 9  volatility.framework.interfaces.configuration: TypeError - yara_rules requirements only accept str type: None
> Level 9  volatility.framework.interfaces.configuration: TypeError - yara_rules requirements only accept str type: None
> INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
> INFO     volatility.framework.automagic: Running automagic: LayerStacker
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.intel
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.elf
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.vmware
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.linear
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.msf
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.registry
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.segmented
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.crash
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.physical
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.lime
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.resources
> DEBUG    volatility.framework: Importing module: volatility.framework.layers.scanners.multiregexp
> Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.YaraScan.primary
> Level 8  volatility.framework.automagic.stacker: Attempting to stack using Elf64Stacker
> Level 8  volatility.framework.automagic.stacker: Attempting to stack using LimeStacker
> Level 8  volatility.framework.automagic.stacker: Attempting to stack using WindowsCrashDump32Stacker
> Level 8  volatility.framework.automagic.stacker: Attempting to stack using VmwareStacker
> Level 8  volatility.framework.automagic.stacker: Attempting to stack using WintelStacker
> DEBUG    volatility.framework.automagic.windows: Self-referential pointer not in well-known location, moving to recent windows heuristic
> DEBUG    volatility.framework.automagic.windows: DTB was found at: 0x1aa000
> Level 8  volatility.framework.automagic.stacker: Stacked IntelLayer using WintelStacker
> Level 8  volatility.framework.automagic.stacker: Attempting to stack using Elf64Stacker
> Level 8  volatility.framework.automagic.stacker: Attempting to stack using LimeStacker
> Level 8  volatility.framework.automagic.stacker: Attempting to stack using WindowsCrashDump32Stacker
> Level 8  volatility.framework.automagic.stacker: Attempting to stack using VmwareStacker
> Level 8  volatility.framework.automagic.stacker: Attempting to stack using MacintelStacker
> Level 8  volatility.framework.automagic.stacker: Attempting to stack using LintelStacker
> Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.YaraScan.primary
> Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.YaraScan.primary
> Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.YaraScan.primary
> Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.YaraScan.primary.memory_layer
> Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
> Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
> Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
> Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
> Level 9  volatility.framework.interfaces.configuration: TypeError - yara_rules requirements only accept str type: None
> Level 9  volatility.framework.interfaces.configuration: TypeError - yara_rules requirements only accept str type: None
> DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
> INFO     volatility.framework.automagic: Running automagic: WintelHelper
> INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
> INFO     volatility.framework.automagic: Running automagic: SymbolFinder
> INFO     volatility.framework.automagic: Running automagic: MacSymbolFinder
> INFO     volatility.framework.automagic: Running automagic: LinuxSymbolFinder
> 
> Offset	Rule
> Traceback (most recent call last):
>   File "vol.py", line 10, in <module>
>     volatility.cli.main()
>   File "/home/anton/Desktop/volatility3/volatility/cli/__init__.py", line 523, in main
>     CommandLine().run()
>   File "/home/anton/Desktop/volatility3/volatility/cli/__init__.py", line 281, in run
>     renderers[args.renderer]().render(constructed.run())
>   File "/home/anton/Desktop/volatility3/volatility/cli/text_renderer.py", line 163, in render
>     grid.populate(visitor, outfd)
>   File "/home/anton/Desktop/volatility3/volatility/framework/renderers/__init__.py", line 196, in populate
>     for (level, item) in self._generator:
>   File "/home/anton/Desktop/volatility3/volatility/framework/plugins/yarascan.py", line 77, in _generator
>     rules = yara.compile(file = resources.ResourceAccessor().open(self.config['yara_file'], "rb"))
>   File "/usr/local/lib/python3.6/dist-packages/yara/rules.py", line 462, in compile
>     raise ValueError("compile() missing a required argument")
> ValueError: compile() missing a required argument

**Command Being Run:**

python3 vol.py -vvvv -f /home/anton/Desktop/20200120.mem yarascan.YaraScan --yara-file yara.yar

**Volatility Version:**

Volatility 3 Framework 1.0.0-beta.1

**Memory Image Info:** 

Volatility 3 Framework 1.0.0-beta.1
Progress:    0.00		Scanning primary2 using PdbSignatureScanner
Variable	Value

Kernel Base	0xf8062fa00000
DTB	0x1aa000
Symbols	file:///home/anton/Desktop/volatility3/volatility/symbols/windows/ntkrnlmp.pdb/F3A4F64B6F639A058AD6F33155ACA4F6-1.json.xz
primary	0 WindowsIntel32e
memory_layer	1 FileLayer
KdVersionBlock	0xf8062fe2a3c8
Major/Minor	15.18362
MachineType	34404
KeNumberProcessors	1
SystemTime	2020-01-20 18:07:04
NtSystemRoot	C:\Windows
NtProductType	NtProductWinNt
NtMajorVersion	10
NtMinorVersion	0
PE MajorOperatingSystemVersion	10
PE MinorOperatingSystemVersion	0
PE Machine	34404
PE TimeDateStamp	Tue Aug 22 00:24:00 1972

**Yara Rule:**

rule ExampleRule
{
    strings:
        $my_text_string = "Test1234"
    condition:
        $my_text_string
}

**Comment by ikelos** [comment]
Hmmm, what version of yara do you use/have installed?  I tried recreating this locally with yara 3.11 and got no errors...

**Comment by ikelos** [comment]
Hmmm, that's pretty strange, that's the same version I've got?  Could you try the following small snippet of python to check it works as it should please?

```
import yara
thing = yara.compile(file = open('yara.yar', 'rb'))
print(thing)
```
It should be run from the directory where yara.yar exists, or change the path to point to the right file.  I'm trying to figure out if it's a difference with the `yara.compile` method on your system, or if it's something to do with the `ResourceAccessor` class...

**Comment by Antonlovesdnb** [comment]
Interesting, that fails with the same error:

> root@vol:/home/anton/Desktop/volatility3# cat yara.yar 
> rule ExampleRule
> {
> 	strings:
> 		$my_text_string = "Test1234"
> 	condition:
> 		$my_text_string
> }
> 
> 
> root@vol:/home/anton/Desktop/volatility3# cat yaratest.py 
> import yara
> thing = yara.compile(file = open('yara.yar', 'rb'))
> print(thing)
> 
> root@vol:/home/anton/Desktop/volatility3# python3 yaratest.py 
> Traceback (most recent call last):
>   File "yaratest.py", line 2, in <module>
>     thing = yara.compile(file = open('yara.yar', 'rb'))
>   File "/usr/local/lib/python3.6/dist-packages/yara/rules.py", line 462, in compile
>     raise ValueError("compile() missing a required argument")
> ValueError: compile() missing a required argument

**Comment by ikelos** [comment]
Hiya, sorry I took so long getting back to you.  5:S  

The results suggest that this is some kind of issue with the version of yara being used on that system.  Could you please let me know what version of yara-python you've got installed, whether it was self-compiled and how it was installed (pip or operating system package management)?

**Comment by ikelos** [comment]
Hopefully you've identified the root cause, and this issue isn't a problem any more.  If it is, please feel free to reopen this...  5:)
