### ISSUE TITLE
pdbconv: include _imp_ functions in the JSON

### ISSUE THREAD

**Issue by tklengyel** [volatilityfoundation/volatility3#184]
Some internal Windows functions are currently missing from the JSON generated by pdbconv. For example, some syscall handlers in the SSDT on Windows 10 1903 point to functions whose address is not currently present in the JSON. These functions are effectively just stub functions that load the real syscall address into r10.

For example:
```
    "NtCommitTransaction": {
      "address": 5682416,
      "linkage_name": "__imp_NtCommitTransaction"
    },
```

The SSDT for this syscall doesn't point to this address.  This address is where the actual `implementation` of the function is located. Comparing the JSON to one generated by Rekall we see the following:
```
  "_imp_NtCommitTransaction": 5682416,
  "NtCommitTransaction": 1676048, 
```

The SSDT in fact points to stub function at kernel_base + 1676048, which then loads the address of kernel_base + 5682416 to r10. So pdbconv should include the address for both functions in the JSON and switch their naming so that it matches up with the SSDT.

**Comment by ikelos** [comment]
Hiya, sorry it's taken so long for me to get back to you.  The python based generation code in `pdbconv.py` is [here](https://github.com/volatilityfoundation/volatility3/blob/master/volatility/framework/symbols/windows/pdbconv.py#L523).  It should be easy to remove those lines.  Would you be able to test removing them and then let us know whether a) the `_imp_<blah>` entry points to the right place and b) whether there's a flat `<blah>` entry that also points to the place you'd expect it to?

I'll check with the rest of the team as to why that's in there, I suspect it's historical from the days of volatility 2 and vtypes, but I don't immediately see a good reason to keep it that way, so we should be able to fix that up for you.

So yeah, please just run those tests and let me know how they turn out and once I've checked with the team we should be able to get you a resolution...  5:)

**Comment by tklengyel** [comment]
@ikelos Yeap, that solved it. I'll open a PR.

**Comment by tklengyel** [comment]
With those lines removed pdbconv now produces the same (correct) output as Rekall.
