### ISSUE TITLE
More help when using a parameter without "parameters" ... 

### ISSUE THREAD

**Issue by Th4nat0s** [volatilityfoundation/volatility3#191]
Hello, 

I think's It's could be valuable for being able to use vol3 more quickly to have the possible choices or a more concise description of what is required after a parameter. It will avoid us to dig into the code or the "still early stage" documentation :) 

for example -r says it's need a parameter.  But you still don't know your choices.

```
$ ./vol.py -v -f cridex.vmem -r
usage: volatility [-h] [-c CONFIG] [--parallelism [{processes,threads,off}]]
                  [-e EXTEND] [-p PLUGIN_DIRS] [-s SYMBOL_DIRS] [-v] [-l LOG]
                  [-o OUTPUT_DIR] [-q] [-r RENDERER] [-f FILE]
                  [--write-config] [--clear-cache]
volatility: error: argument -r/--renderer: expected one argument
```

But -r garbage, gives the rights possible choices.

```
$ ./vol.py -v -f cridex.vmem -r garbage
usage: volatility [-h] [-c CONFIG] [--parallelism [{processes,threads,off}]]
                  [-e EXTEND] [-p PLUGIN_DIRS] [-s SYMBOL_DIRS] [-v] [-l LOG]
                  [-o OUTPUT_DIR] [-q] [-r RENDERER] [-f FILE]
                  [--write-config] [--clear-cache]
volatility: error: argument -r/--renderer: invalid choice: 'garbage' (choose from 'quick', 'csv', 'pretty', 'json', 'jsonl')
```

It could be nice to have directly "what do put" as parameter or a kind of "detailed help" option available .. like "-r help"  maybe.

Thank'you.

**Comment by ikelos** [comment]
Ok, so pretty doable, but a little nasty almost monkeypatching the private methods of argparse.  Still, should be all good, please feel free to reopen this if there's problems...  5:)
