### ISSUE TITLE
VadYaraScan not printing Hex

### ISSUE THREAD

**Issue by Nick-120** [volatilityfoundation/volatility3#209]
Let me preface this by saying this could be me doing something wrong, if this is the case I apologise.

When running the command './vol.py -f 7SP1-Chrome.mem windows.vadyarascan.VadYaraScan --yara-rules "outlook", it doesn't print any hex data like it does in Volatility 2.

**Context**
Volatility Version:  Volatility 3 beta 1.0
Memory Dump Operating System: Windows 7SP1
Python Version: Python 3.7.6 

Command:  ./vol.py -f 7SP1-Chrome.mem windows.vadyarascan.VadYaraScan --yara-rules "outlook"

![Borken yara](https://user-images.githubusercontent.com/34124664/79223639-a0982e00-7e51-11ea-8c05-1633507f065e.png)

**Expected behavior**
In Volatility 2 it would print the related hex data 

Thanks for any help!

**Comment by ikelos** [comment]
Hiya, thanks for the report, it absolutely wasn't you!  We were only returning the names of the rules (I think in case a string ran-away and was matched by vast quantities of data.  I've now added the value matched (hex bytes) to the output as of commit `edecd64`.  Please test it and let me know if it all works ok!  Feel free to reopen this if it doesn't...  5:)
