### ISSUE TITLE
Linux plugins issues

### ISSUE THREAD

**Issue by nov3mb3r** [volatilityfoundation/volatility3#231]
**Describe the bug**
Once using the linux.pstree.PsTree plugin the following issue appears.
Linux symbols have been places under the volatility/symbols folder
```
Progress:   99.25               Scanning FileLayer using MultiStringScanner
Unsatisfied requirement plugins.PsTree.primary: Memory layer for the kernel
Unsatisfied requirement plugins.PsTree.vmlinux: Linux kernel symbols

A symbol table requirement was not fulfilled.  Please verify that:
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner


A translation layer requirement was not fulfilled.  Please verify that:
        A file was provided to create this layer (by -f, --single-location or by config)
        The file exists and is readable
        The necessary symbols are present and identified by volatility
Unable to validate the plugin requirements: ['plugins.PsTree.primary', 'plugins.PsTree.vmlinux']
```

**Context**
Volatility Version:  Volatility 3 Framework 1.0.0-beta.1
Operating System:  Windows 10x64
Python Version:  3.8.3
Suspected Operating System:  
Command:  python3 vol.py -f /mnt/d/mem.dmp linux.pstree.PsTree

**Comment by nov3mb3r** [comment]
Upon running vol.py -vv
```
INFO     root        : Volatility plugins path: ['/home/november/volatility3/volatility/plugins', '/home/november/volatility3/volatility/framework/plugins']
INFO     root        : Volatility symbols path: ['/home/november/volatility3/volatility/symbols', '/home/november/volatility3/volatility/framework/symbols']
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.yarascan based on file: yarascan
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.callbacks based on file: windows/callbacks
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.svcscan based on file: windows/svcscan
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.vadyarascan based on file: windows/vadyarascan
INFO     root        : The following plugins could not be loaded (use -vv to see why): volatility.plugins.windows.callbacks, volatility.plugins.windows.svcscan, volatility.plugins.windows.vadyarascan, volatility.plugins.yarascan
```

**Comment by ikelos** [comment]
Hiya, you haven't provided a suspected operating system for the memory image you were analyzing.  The error message suggests that there isn't a suitable set of linux symbols for the image you were trying to investigate.  The symbols provided in the pack aren't a complete set of all symbols for all linux systems (that would be infeasible to provide, although we are looking to expand the set to include symbols from more standard images).

You can generate symbols for your specific image, if you can get a copy of the kernel with debug symbols and the system.map from the system?  You can then use a tool called dwarf2json to convert those into the format that volatility 3 consumes.

If you can give us a bit more information about the sample you're looking at we might be able to provide further information?

**Comment by nov3mb3r** [comment]
I was using a plain CentOS 5.7 and tried to image it with lime. Then downloaded the symbols from the repo

**Comment by ikelos** [comment]
Hiya, the linux pack doesn't contain the symbols for CentOS 5.7 unfortunately yet (although we are intending to produce a more complete pack down the line).  For now you should attempt to locate the appropriate kernel package (for the System.map) from http://vault.centos.org/5.7/updates/x86_64/RPMS/ and the appropriate kernel-debuginfo package for the kernel with dwarf information from (http://debuginfo.centos.org/5/x86_64/).  You can then generate your own symbols using dwarf2json, and if it matches the image you're using then you should be able to use any of the available plugins.

I'm not sure there's actually a bug here, so I'm going to close this afterwards.  If you feel there's still a problem with the code, please feel free to reopen it, and if you want more help on generating symbols, please contact us on the slack (https://www.volatilityfoundation.org/slack) in the #vol3-dev channel...  5:)

**Comment by songfeigu** [comment]
> Hiya, the linux pack doesn't contain the symbols for CentOS 5.7 unfortunately yet (although we are intending to produce a more complete pack down the line). For now you should attempt to locate the appropriate kernel package (for the System.map) from http://vault.centos.org/5.7/updates/x86_64/RPMS/ and the appropriate kernel-debuginfo package for the kernel with dwarf information from (http://debuginfo.centos.org/5/x86_64/). You can then generate your own symbols using dwarf2json, and if it matches the image you're using then you should be able to use any of the available plugins.
> 
> I'm not sure there's actually a bug here, so I'm going to close this afterwards. If you feel there's still a problem with the code, please feel free to reopen it, and if you want more help on generating symbols, please contact us on the slack (https://www.volatilityfoundation.org/slack) in the #vol3-dev channel... 5:)

I generated my own ISF for my OS, but still got the same error message .  The symbol file is named appropriately or contains the correct banner ? WHAT is the rule for naming the symbol file ? When I used the command uname -r , my kernel is 3.10.0-1160.71.1.el7.x86_64.

**Comment by eve-mem** [comment]
If you compare the versions of the banner between the `banners` plugin and the `isfinfo` plugin you can see if they match. 

They need to be exactly the same. 

If your symbols file doesn't appear in the `isfinfo` plugin output than it is an issue with where the the symbols are located.

**Comment by ikelos** [comment]
> WHAT is the rule for naming the symbol file ? 

Sorry, by that I just meant that if it's a linux symbol table it lives under `symbols/linux` and if it's a windows symbol tables its file name matches the GUID of the pdb.  Both of these requirements have gone since the middle of last year.  You can see which ISF files volatility is aware of using the `isfinfo` plugin.  If you can't find your symbol file listed in there it may be invalid or there may be some other problem.

If you encounter an issue, please either ask on the [volatility slack](https://www.volatilityfoundation.org/slack) or file a separate ticket.  Adding comments to the end of an already closed ticket won't sure they get seem and made confuse multiple issues in the same ticket.  Thanks...  5:)
