### ISSUE TITLE
TypeError: bool.__new__(Boolean): Boolean is not a subtype of bool

### ISSUE THREAD

**Issue by dl9rdz** [volatilityfoundation/volatility3#232]
**Describe the bug**
Traversing the network interface data structures of a Linux image fails with the TypeError: bool.__new__(Boolean): Boolean is not a subtype of bool

**Context**
Volatility Version:  Volshell (Volatility 3 Framework) 1.0.0-beta.1
Operating System:  MacOS Mojave (running volatility)
Python Version:  3.6

**To Reproduce**
wget https://gandra.fim.uni-passau.de/csec_files/vm.dump
wget https://gandra.fim.uni-passau.de/csec_files/linux-image-4.4.0-124-generic_4.4.0-124.148_amd64.json
mv linux-image-4.4.0*json volatility/symbols/linux
python3 volshell.py -f vm.dump  -l
(primary) >>> from volatility.framework import contexts
(primary) >>> vmlinux = contexts.Module(context, "vmlinux1", "primary", 0)
(primary) >>> netll = vmlinux.object_from_symbol("net_namespace_list")
(primary) >>> net = netll.to_list("vmlinux1!net","list")
(primary) >>> l = list(net)
(primary) >>> base = l[0].dev_base_head
(primary) >>> baselist = base.to_list("vmlinux1!net_device","dev_list")
(primary) >>> bl = list(baselist)
(primary) >>> dt(bl[1])
vmlinux1!net_device (2112 bytes)
   0x0 :   name                     vmlinux1!array                        ['101', '116', '104', '48', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
  0x10 :   name_hlist               vmlinux1!hlist_node                   0x88000e845010
[... several lines omitted ...]
 0x26c :   name_assign_type         vmlinux1!unsigned char                0
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/hansi/src/volatility3/volatility/cli/volshell/linux.py", line 60, in display_type
    return super().display_type(object, offset)
  File "/Users/hansi/src/volatility3/volatility/cli/volshell/generic.py", line 252, in display_type
    self._display_value(getattr(volobject, member)))
  File "/Users/hansi/src/volatility3/volatility/framework/objects/__init__.py", line 707, in __getattr__
    member = template(context = self._context, object_info = object_info)
  File "/Users/hansi/src/volatility3/volatility/framework/objects/templates.py", line 72, in __call__
    return self.vol.object_class(context = context, object_info = object_info, **arguments)
  File "/Users/hansi/src/volatility3/volatility/framework/objects/__init__.py", line 123, in __new__
    result = cls._struct_type.__new__(cls, value)
TypeError: bool.__new__(Boolean): Boolean is not a subtype of bool

**Expected behavior**
Complete output of net_device structure, without Excepetion

**Additional information**
Symbol json file generated with (branch linux-module-version of dwarf2json):
`dwarf2json linux --reference-symbols volatility/symbols/linux/linux-image-4.9.0-3-amd64-dbg_4.9.30-2+deb9u2_amd64.json --elf module.ko --system-map System.map-4.4.0-124-generic  --linux-banner "Linux version 4.4.0-124-generic (buildd@lcy01-amd64-028) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 (Ubuntu 4.4.0-124.148-generic 4.4.117)"`
Using the --reference-symbols argument as a workaround, because I have not yet figured out how to make dwarf2json extract the type information of System.map entries from module.ko directly.

**Comment by dl9rdz** [comment]
This is a workaround that prevents the exception:

--- a/volatility/framework/objects/__init__.py
+++ b/volatility/framework/objects/__init__.py
@@ -158,7 +158,7 @@ class PrimitiveObject(interfaces.objects.ObjectInterface):
 
 class Boolean(PrimitiveObject, int):
     """Primitive Object that handles boolean types."""
-    _struct_type = bool  # type: ClassVar[Type]
+    _struct_type = int  # type: ClassVar[Type]
 
 
 class Integer(PrimitiveObject, int):

**Comment by ikelos** [comment]
Ahh, good catch, thanks!  I tried making Boolean inherit from bool, but apparently that's been explicitly disabled [1,2], so I think your solution is correct.  It looks like we can just use the `__bool__` method already defined on int, so this ought to be fine, thanks!  5:)

[1] https://mail.python.org/pipermail/python-dev/2002-March/020822.html
[2] https://mail.python.org/pipermail/python-dev/2004-February/042537.html

Fixed in `16a8e377`.  5:)
