### ISSUE TITLE
Importing volatility.cli.text_renderer sets application root logging level to 1

### ISSUE THREAD

**Issue by Wenzel** [volatilityfoundation/volatility3#241]
When importing `volatility.cli.text_renderer`, the application's root logger's level is modified, and set to 1, which is the most permissive level possible.
As a consequence, all debug messages (in volatility or in the application's code) are enabled.

Volatility Version:  [`master`](https://github.com/volatilityfoundation/volatility3/tree/4b29cf1986efe172b51aae746afef4fe8b0c6271)
Operating System:  Ubuntu 20.04
Python Version:  `3.8`

**To Reproduce**
Please execute the following script:
~~~Python
#!/usr/bin/env python3

import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s:%(name)s:%(message)s")
print("root level: {}".format(logging.root.level))
import volatility.plugins
print("root level: {}".format(logging.root.level))
from volatility import framework
print("root level: {}".format(logging.root.level))
from volatility.framework import contexts, automagic, interfaces
print("root level: {}".format(logging.root.level))
from volatility.framework.interfaces.renderers import RenderOption
print("root level: {}".format(logging.root.level))
from volatility.framework.renderers import format_hints
print("root level: {}".format(logging.root.level))
from volatility.cli.text_renderer import quoted_optional, hex_bytes_as_text, display_disassembly
print("root level: {}".format(logging.root.level))
~~~

**Expected behavior**

~~~
root level: 20
root level: 20
root level: 20
root level: 20
root level: 20
root level: 20
root level: 20
~~~

**Actual behavior**
~~~
root level: 20
root level: 20
root level: 20
root level: 20
root level: 20
root level: 20
root level: 1
~~~

**Additional information**

This causes me a great deal of problem when using Volatility3 as a third-party library in a Python application, as debug messages will be enabled.

Thanks !

**Comment by ikelos** [comment]
Thanks for the report!  5:)  The CLI isn't really supposed to be imported (it's when anything under `volatility.cli` is imported that the logging level is set) but since it all happens after the importing there's not a great deal of difference for us between turning it on during the initialization of the CLI versus globally when the CLI module is imported, so I've moved anything that would also the root logger.

**Comment by Wenzel** [comment]
Confirmed, it works.
Thank you very much !
