### ISSUE TITLE
Win10x64_18362 - Error - Volatility 3 and 2.7

### ISSUE THREAD

**Issue by dunha99** [volatilityfoundation/volatility3#246]
**Describe the bug**

**Context**
Volatility Version:  3.0
Operating System: Kali_v2020
Python Version:  3.7.7 and 2.7.18
Suspected Operating System:   W10-1909_ 18362
Use FTK Imager capture RAM.

1. Volatility 2.7 

volatility -f memdump.mem --profile=Win10x64_18362  psscan > psscan.txt
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : Invalid profile Win10x64_18362 selected

2. Volatility 3 (beta)

volatility3# python3 vol.py -f /root/Desktop/Case_4625/memdump.mem windows.cmdline.CmdLine > cmdline4625.txt
Volatility was unable to read a requested page:y2 using PdbSignatureScanner
Page error 0x2400001160 in layer primary2 (Page Fault at entry 0x0 in table page directory)

        * Memory smear during acquisition (try re-acquiring if possible)
        * An intentionally invalid page lookup (operating system protection)
        * A bug in the plugin/volatility (re-run with -vvv and file a bug)

No further results will be produced

**Comment by garanews** [comment]
I had some read issue with FTK imager and windows 10.
Was able to dump and read MEM with Belkasoft Live RAM Capturer.
Give it a try.

**Comment by ikelos** [comment]
For volatility 2, you could try a different Win10 profile?  The available profiles can be listed with volatility --info I believe?

**Comment by atcuno** [comment]
If you are on the latest git checkout of Volatility 2 then you should have that profile. Can you ensure you are on the latest version?

**Comment by its0x08** [comment]
I have same problem. volatility2.7 is way faster and solid.. the version 3 in 90% of my cases doesnt work :(
I use dumpit and obviously same error with @dunha99  that is using FTK Imager acording to @garanews !!
My guess was that the problem was only with Windows 10 but obviously even XP is not working and I use git lastes for both versions.
![volatility3 not working](https://i.imgur.com/cQCi76g.png)

**Comment by ikelos** [comment]
@its0x08 If you're willing we could help diagnose what's causing the issue with volatility3.  Could you please run it again with `vol.py -vvvv`?  It should give you a lot of debugging output that will start to tell us why it may be having difficulty with that image.

Similarly @dunha99 we can try to help with your volatility3 issues if you run volatility 3 with `vol.py -vvvv` to generate debugging information and from there we can start to figure out what might be going wrong...

**Comment by dunha99** [comment]
Thanks, I managed to use it. I saw some old tickets. Thank you very much for your support.

**Comment by dunha99** [comment]
but I will use the belkasoft capture in the next case

**Comment by ikelos** [comment]
No problem, glad you got it resolved.  @its0x08, I'm going to close this ticket off, but please file a new one with your issues regarding volatility 3 if you'd like us to investigate and provide help with it...
