### ISSUE TITLE
Pack has bad object issue.

### ISSUE THREAD

**Issue by neoki75** [volatilityfoundation/volatility3#252]
root@kali:/home/kali# git clone https://github.com/volatilityfoundation/volatility3.git
Cloning into 'volatility3'...
remote: Enumerating objects: 276, done.
remote: Counting objects: 100% (276/276), done.
remote: Compressing objects: 100% (195/195), done.
fatal: pack has bad object at offset 57906: inflate returned -5
fatal: index-pack failed
root@kali:/home/kali#

**Context**
root@kali:/home/kali# cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.2"
VERSION_ID="2020.2"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
root@kali:/home/kali# 

**To Reproduce**
Shown below

1. Use command 'git....
2. See error

**Expected behavior**

**Screenshots**

**Additional information**
Add any other information about the problem here.

**Comment by ikelos** [comment]
Thanks for the report, I'm unable to recreate this on a separate system.  Do you have another system you could test it on and verify whether you believe it to be a problem with the main repo rather than a local problem?

**Comment by neoki75** [comment]
So sorry, I will try ASAP and will report

**Comment by ikelos** [comment]
Has there been any update on this?  We haven't had any other people reporting this issue?  Hopefully a clean check-out will resolve this issue?  I'll close this off soon if there's no further feedback...
