### ISSUE TITLE
FR: possibility to clear cache when using vol as library

### ISSUE THREAD

**Issue by garanews** [volatilityfoundation/volatility3#264]
**Is your feature request related to a problem? Please describe.**
When updating symbols then from cli is needed launch ```vol.py``` with parameter ``` --clear-cache``` in order to reload updated symbols.
This thing is not supported when using volatility as library.

**Describe the solution you'd like**
something like
```import volatility.symbols```
```volatility.symbols.clear_cache()```

**Describe alternatives you've considered**
Currently the workaround is delete cache folder content:  ```CACHE_PATH = os.path.join(os.path.expanduser("~"), ".cache", "volatility3")```

**Comment by ikelos** [comment]
Ok, this should now be resolved in `dc1e5064`.  The code that was clearing the cache has been moved into `framework.clear_cache()`.  There's a `complete` argument which will clear out the cache for linux/mac banners.  These should be self repairing for the most part (file not found, and new files found) and so not need clearing.  If an existing if an existing file changes its banner, this would be required, but I think the cost of this being used when unnecessary will be larger than the cost of people who need it manually going into the cache directory and clearing it out.  A simple solution would be to rename the JSON that changed and then (if necessary) rename it back.  Rebuilding those will require going through every available linux/mac JSON file and extracting the banners from it, so it's a very slow process and should be avoided if necessary.

Please shout if there's any issues...
