### ISSUE TITLE
adding --memory on dlldump & moddump

### ISSUE THREAD

**Issue by garanews** [volatilityfoundation/volatility3#272]
**Is your feature request related to a problem? Please describe.**
--memory, is likely only familiar to power Volatility users. The purpose of this flag is to instruct Volatility to extract all regions of memory around PE files instead of just relying on the file metadata in the PE header that specifies the original size of each section. This helps substantially when extracting packed executables from memory as you can get data both from the original file as well as the unpacked executable.

**Describe the solution you'd like**
have the same feature on vol3 plugins

**Comment by iMHLv2** [comment]
@garanews Since `procdump --memory` was so frequently used in vol2, that became the default in vol3.

**Comment by garanews** [comment]
@iMHLv2 what about dlldump & moddump?

**Comment by railabouni** [comment]
hi all,
is there is a method to dump the .EXE file from a windows image?
Thank you!

**Comment by iMHLv2** [comment]
> @iMHLv2 what about dlldump & moddump?

Yes, both of these plugins also dump PE files in the same way vol2 with `--memory` did.

**Comment by garanews** [comment]
I'm doing some test, is normal that running on the same image (stuxnet):
vol3 dlllist --dump returns 1252 files 
vol2 dlldump (--memory) returns 1127 files
vol3 modules --dump returns 122 files
vol2 moddump (--memory) returns 121 files

And
vol3 malfind returns 14 files with some hash
vol2 malfind returns 14 files  with completely different hash
