### ISSUE TITLE
Cannot access to the anonymous struct/unions members

### ISSUE THREAD

**Issue by gcmoreira** [volatilityfoundation/volatility3#291]
**Describe the bug**
Members of anonymous structs/unions inside other types are not populated by the framework.

**Context**
Volatility Version: 1.1.0-beta.1 (master)
Operating System: Ubuntu 20.04 LTS
Python Version: 3.8.2
Suspected Operating System: kernel 3.13.0-117 / Ubuntu 12.04
Command:  <new plugin>

**To Reproduce**

```
> kmem_cache_node.vol.type_name
'vmlinux1!kmem_cache_node'

> list(kmem_cache_node.partial.to_list('vmlinux1!page', 'lru'))
IndexError: Member not present in template: lru

> list(vmlinux.get_type('page').members)
['flags', 'unnamed_field_10', 'unnamed_field_20', 'unnamed_field_30', 'unnamed_field_8']

```
Additional information:
[isf.zip](https://github.com/volatilityfoundation/volatility3/files/5066667/isf.zip)

**Comment by gcmoreira** [comment]
Fixed. Now, it works with any number of nested anonymous. Also, I redid everything from scratch because the code was a bit confusing to me.

Be aware that I've quickly tested it. So far, it seems it didn't break anything but just in case please test it with other OSes/versions. Also, it seems a bit faster but it could be my imagination ;)

[intermed.zip](https://github.com/volatilityfoundation/volatility3/files/5069909/intermed.zip)

**Comment by ikelos** [comment]
Ok, so I was ok with your system, but the name of `_reduce_all_fields` and `_reduce_fields` didn't quite feel clear enough, so I rewrote in the original style.  Ironically I did that because I was concerned about `_interdict_to_template` being in there, but then realized that in my first version I refactor the call away completely, which would've broken everything!  5:S  I've since gone back and fixed it up, and there's comments and stuff in there, so hopefully it's easy to follow and makes sense to both of us?  I'm not against using your instead, if you'd like to submit it as a pull request, but I'll need to think it through and may have some minor tweaks around names and things (I'd prefer private methods since they shouldn't really be called from the outside world).

I don't know that I've got any images to match the kernels that I can generate recent JSON for, so if you could test this for me I'd much appreciate it.  5:)

**Comment by gcmoreira** [comment]
Thank @ikelos. 
Mh, I tested it with your version and it doesn't seem to work. It still produces the same result:
```
> list(vmlinux.get_type("page").vol.members)
['flags', 'unnamed_field_10', 'unnamed_field_20', 'unnamed_field_30', 'unnamed_field_8']

> list(kmem_cache_node.partial.to_list(self.get_symbol_fullname('page'), 'lru'))
IndexError: Member not present in template: lru
```

While with the code I sent 
```

> list(vmlinux.get_type("page").vol.members)
['flags', 'freelist', 'index', 'pfmemalloc', 'active', 'counters', '_count', '_mapcount', 'units', 'frozen', 'inuse', 'objects', 'callback_head', 'list', ...]

00:'flags'
01:'freelist'
02:'index'
03:'pfmemalloc'
...
25:'s_mem'
len():26
```
Anyway, you can test it with any Linux kernel version you have available. Struct page is that complex in any of them, you will see it doesn't look right straight away with the unnameds there.

Also I noticed that in my patch I didn't include a minor bugfix and forgot to remove the old `_reduce_indirect_members` .

I won't be much objective giving my opinion of my own code :) but I found mine much simpler, smaller, modular and most importantly ... it works ;), but yeah I understand most of these points are subjective.

If you want I can create a pull request with the latest version. Of course be free of renaming or changing whatever you don't feel right to you. Otherwise, if you prefer to fix yours it's all good.
Thanks

**Comment by ikelos** [comment]
Yeah, please do create a PR, I'm happy to close this one (although I am curious why this didn't work, because I did check another member that contained an anonymous type and it did collapse that, so I'll have to investigate)...  5:)

**Comment by ikelos** [comment]
Sorry, closed the issue not my PR.  5:S

Also, it seems to work for me?  I had to hard load a symbol table that has the anonymous flag, but the output looks ok to me?
```
(primary) >>> from volatility.framework.symbols import intermed
(primary) >>> table_name = intermed.IntermediateSymbolTable.create(context, 'path', 'linux/debian', '5.7.0-rc5-cloud-amd64-dbg_5.7~rc5-1~exp1_amd64')
(primary) >>> table = context.symbol_space[table_name]
(primary) >>> x = table.get_type('page')
(primary) >>> x.members
{'_refcount': (52, <volatility.framework.objects.templates.ReferenceTemplate object at 0x7f5eb7f187d0>), 'flags': (0, <volatility.framework.objects.templates.ObjectTemplate object at 0x7f5eac7e8390>), 'mem_cgroup': (56, <volatility.framework.objects.templates.ObjectTemplate object at 0x7f5eac7e8ed0>), '_mapcount': (48, <volatility.framework.objects.templates.ReferenceTemplate object at 0x7f5eac7e8dd0>), 'active': (48, <volatility.framework.objects.templates.ObjectTemplate object at 0x7f5eac7e8cd0>), 'page_type': (48, <volatility.framework.objects.templates.ObjectTemplate object at 0x7f5eac7e8d50>), 'units': (48, <volatility.framework.objects.templates.ObjectTemplate object at 0x7f5eac7e8c10>), 'callback_head': (8, <volatility.framework.objects.templates.ReferenceTemplate object at 0x7f5eac7e8c90>), 'pgmap': (8, <volatility.framework.objects.templates.ObjectTemplate object at 0x7f5eac7e8a90>), 'zone_device_data': (16, <volatility.framework.objects.templates.ObjectTemplate object at 0x7f5eac7e88d0>)}
```

**Comment by gcmoreira** [comment]
Oh sorry yeah you are right, I was testing the wrong branch. That works too.
I will create the PR later anyway if you don't mind.

**Comment by ikelos** [comment]
No, don't mind in the slightest.  I think you're right, yours may well be cleaner, so do submit it and we can go through the review process...  5:)
