### ISSUE TITLE
MMVAD cannot find children

### ISSUE THREAD

**Issue by slyles1001** [volatilityfoundation/volatility3#304]
In windows 10, there is another layer between MMVAD and children. When `volatility.framework.symbols.windows.extensions.MMVAD` inherits from `MMVAD_SHORT`, the `find_child` functions cannot find a member of the nested objects.

**Context**
Volatility Version:  commit 73f3c217bd0b752ac43d576605bb1931d8ec8a5d
Operating System:  WSL
Python Version:  3.6.9
Suspected Operating System:  Windows 10

**To Reproduce**
call `get_left_child()` on MMVAD object

**Expected behavior**
returns left child address

**Comment by slyles1001** [comment]
I'm happy to work on this, i think the fix will be quick. The `get_parent` function in `MMVAD_SHORT` already has the `VadNode` or `Core` checks.

**Comment by ikelos** [comment]
Ok, cool, please feel free to and submit it as a pull request.  5:)  We'll get @iMHLv2 to look over it, as our resident MMVAD expert...  5;)

**Comment by iMHLv2** [comment]
@slyles1001 We believe this might be an issue with the volshell tool. Going back to commit https://github.com/volatilityfoundation/volatility3/commit/73f3c217bd0b752ac43d576605bb1931d8ec8a5d, are you able to run the vadinfo plugin against your Windows 10 memory sample? In particular, your screen shots from https://github.com/volatilityfoundation/volatility3/pull/305 show `ps()[-1]` so perhaps you could print the process ID of that process and then use `vadinfo --pid <PID>` to see how it goes? Also, do you have any more specific version information for the Windows 10 memory sample? For example, the build number (i.e., 10.0.17763.x) or the GUID that volatility3 identifies (can be seen in the output of vol.py -vvvvvvv)?

**Comment by slyles1001** [comment]
Hey @iMHLv2, I'm using Windows 10 (10.0.10586 Build 10586) in virtualbox for the dump. I was having trouble in a plugin i'm writing and was able to reproduce in the volshell.

The plugin has this as content:
```python
            for vad in [v for v in proc.get_vad_root().traverse()]:
                typ = "None"
                fil = "None"
                if vad.get_start() in heaps:
                    typ = "heap"
                elif vad.get_start() in stacks:
                    typ = "stack"
                elif vad.get_start() in mods:
                    typ = "DLL"
                    fil = mods[vad.get_start()]
                else:
                    fil = vad.get_file_name()
                    if type(fil) != renderers.NotApplicableValue:
                        typ = "mapped"
                    else:
                        fil = "None"
                        typ = "other"
                try:
                    left_child = hex(vad.VadNode.get_left_child())
                except AttributeError:
                    left_child = str(-1)

                try:
                    right_child = hex(vad.VadNode.get_right_child())
                except AttributeError:
                    right_child = str(-1)
```
where `proc` is a process object. I noticed that the `_MMVAD_SHORT` objects had children, but NONE of the `_MMVAD` objects did. 

I found [this](https://www.vergiliusproject.com/kernels/x64/Windows%2010%20|%202016/1511%20Threshold%202/_MMVAD) for reference.
