### ISSUE TITLE
Beginner Question: Unsatisfied requirements

### ISSUE THREAD

**Issue by MureDanta** [volatilityfoundation/volatility3#308]
I'm sure this is a total beginner question, but I'm a total beginner so I suppose that's fair. I'm trying to use Volatility3 to analyze a LiME image taken from a Fedora 32 system. After cloning the software, I created a JSON symbol table for that system with dwarf2json (as documented) and put it in volatility/symbols/linux/ (note that that directory did not exist). When running Volatility I get:

volatility3 -f mini.lime linux.lsof.Lsof
Volatility 3 Framework 1.1.0-beta.1
Progress:   66.67		Building linux caches
Unsatisfied requirement plugins.Lsof.primary: Memory layer for the kernel
Unsatisfied requirement plugins.Lsof.vmlinux: Linux kernel symbols
Unsatisfied requirement plugins.Lsof.linuxutils: 

A symbol table requirement was not fulfilled.  Please verify that:
	You have the correct symbol file for the requirement
	The symbol file is under the correct directory or zip file
	The symbol file is named appropriately or contains the correct banner

A translation layer requirement was not fulfilled.  Please verify that:
	A file was provided to create this layer (by -f, --single-location or by config)
	The file exists and is readable
	The necessary symbols are present and identified by volatility
Unable to validate the plugin requirements: ['plugins.Lsof.primary', 'plugins.Lsof.vmlinux', 'plugins.Lsof.linuxutils']

Other Linux-oriented commands produce similar output. I see that there is nothing in volatility/plugins/linux except an __init__.py and __pycache__, with the latter containing only __init__.cpython-38.pyc. Do I need to do something special to get the plugins documented by --info?

**Context**
Volatility Version:  Volatility 3 Framework 1.1.0-beta.1
Operating System:  Fedora 32 (5.7.15-200.fc32.x86_64)
Python Version:  3.8.5
Suspected Operating System:  Fedora 32 (5.7.15-200.fc32.x86_64) [known with certainty]
Command:  volatility3 -f mini.lime linux.lsof.Lsof

**To Reproduce**

1. Use command volatility3 -f mini.lime linux.lsof.Lsof
2. See error

**Expected behavior**
Presumably something like lsof output, but since I'm a total beginner I'm not sure. But in any case, I don't expect to see errors.

**Comment by MureDanta** [comment]
Hello! Thanks for your note. It does seem like there is something very fundamental wrong, either with the LiME image, the symbols or both! Here's the output with -vvv:

```
Volatility 3 Framework 1.1.0-beta.1
INFO     root        : Volatility plugins path: ['/home/volatility/volatility3/volatility/plugins', '/home/volatility/volatility3/volatility/framework/plugins']
INFO     root        : Volatility symbols path: ['/home/volatility/volatility3/volatility/symbols', '/home/volatility/volatility3/volatility/framework/symbols']
INFO     volatility.framework.automagic: Detected a linux category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsof.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Lsof.vmlinux
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsof.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Lsof.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsof.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Lsof
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Lsof.vmlinux
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Lsof.vmlinux
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Lsof.vmlinux
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Lsof
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Lsof
INFO     volatility.framework.automagic: Running automagic: LinuxBannerCache
INFO     volatility.framework.automagic.symbol_cache: Building linux caches...
INFO     volatility.framework.automagic: Running automagic: LayerStacker
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsof.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Lsof.vmlinux
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsof.primary
Level 9  volatility.framework.configuration.requirements: TypeError - Layer is not the required Architecture: LimeLayer
Level 9  volatility.framework.configuration.requirements: TypeError - Layer is not the required Architecture: FileLayer
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['LimeLayer', 'FileLayer']
INFO     volatility.framework.automagic: Running automagic: LinuxSymbolFinder
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Lsof.vmlinux
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsof.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Lsof.vmlinux

Unsatisfied requirement plugins.Lsof.primary: Memory layer for the kernel
Unsatisfied requirement plugins.Lsof.vmlinux: Linux kernel symbols
Unsatisfied requirement plugins.Lsof.linuxutils: 

A symbol table requirement was not fulfilled.  Please verify that:
	You have the correct symbol file for the requirement
	The symbol file is under the correct directory or zip file
	The symbol file is named appropriately or contains the correct banner


A translation layer requirement was not fulfilled.  Please verify that:
	A file was provided to create this layer (by -f, --single-location or by config)
	The file exists and is readable
	The necessary symbols are present and identified by volatility
Unable to validate the plugin requirements: ['plugins.Lsof.primary', 'plugins.Lsof.vmlinux', 'plugins.Lsof.linuxutils']
```
I'll go back and review how I created both files to see if I missed something, but if there are any hints from the output, that would be very helpful. Thanks!

**Comment by ikelos** [comment]
No problem, your issue got me thinking we could do with a tool to give us basic information about ISF files, so I wrote #309.  You can run it with `vol.py isfinfo --isf <file isf file>` and it should tell you things like which banners are in there, and how many symbols/types it has.  It might be worth running that against your generated file and we can check if the appropriate information is in it or not.  Failing that, the image may not match the kernel that you generated the symbols for, but again the output of the isfinfo plugin should give us the information to go searching the dump to figure it out...  5:)

**Comment by MureDanta** [comment]
Wow! Thanks for that tool! As you expected, there's something wrong with the symbols:

```
Volatility 3 Framework 1.1.0-beta.1
Progress:   66.67		Building linux caches
URI	Valid	Number of base_types	Number of types	Number of symbols	Number of enums	Windows info	Linux banner	Mac banner

file:///home/volatility/volatility3/volatility/symbols/linux/mini.json	Unknown	14	919	46	60	-	-	-
```

I rebuilt the LiME image and confirmed that, among other things, it has the expected banner text, so I'll focus now on the symbols. Thanks again!

**Comment by MureDanta** [comment]
So I think what it comes down to is that I don't know the correct procedure for creating the ISF. I see in the documentation for dwarf2json a command line like:

` $ ./dwarf2json linux --elf /usr/lib/debug/boot/vmlinux-4.4.0-137-generic > output.json >mini.json`

which seems to imply that the argument to --elf is a debug kernel, but trying that results in an error:

`Failed linux processing: could not open /boot/vmlinuz-5.7.16-200.fc32.x86_64+debug: bad magic number '[77 90 234 7]' in record at byte 0x0`

and indeed it seems that the kernel is not an ELF file generally, so... what file needs to be used as the argument to --elf, and if it's something I need to generate, what's a good procedure? I do have the System.map file, which can be used as the argument to --system-map, but that alone does not seem to be sufficient, and the JSON output from 

`$ ./dwarf2json linux --system-map /boot/System.map-5.7.16-200.fc32.x86_64+debug >mini.json`

produces the same (mostly empty) output from the 'isfinfo' command, though it does show a somewhat larger number of symbols. So it seems I'm still stuck at the beginning.

**Comment by ikelos** [comment]
Yep, so you tend to need both (and the debug kernel should be an elf file, but perhaps vmlinuz is a gz zipped version?  I dunno if the tool will cope with that.  You can find a tool (at https://github.com/volatilityfoundation/volatility3/blob/master/development/stock-linux-json.py) that takes a file with two lines in it (or a multiple of two lines) as URLs for packages, and then unpacks them and generates the JSON appropriately.  There are some example text files in the same directory.  Hopefully that will give you an idea/examples of how it's supposed to work?

**Comment by MureDanta** [comment]
Thanks again! It seems there are many hidden gems here. Also your intuition about the compressed kernel is correct (it seems to use a variant of bzip), but what I find after decompressing the debug kernel is that it still doesn't have DWARF data. Instead I guess RedHat is moving to a format called [BTF](https://www.kernel.org/doc/html/latest/bpf/btf.html). Some chatter on the net suggests that it's possible to convert DWARF to BTF, but it's not clear if there's a tool to go the other way. In the interests of simplicity I've just set CONFIG_DEBUG_INFO_DWARF4=y, then will rebuild the kernel and see what happens. Thanks again for all your help and work!

**Comment by ikelos** [comment]
No problem, glad to have helped!  5:)  It may be worth filing a bug with dwarf2json to see about BTF support (as an enhancement request, rather than a bug), just so they can keep track of it.  I figure that this bug's resolved though, so I'm probably gonna close it.  As I say, a better place to ask for interactive support is on the slack channel (see the link in my first response), but you want to get in touch this way, do feel free to reopen the bug instead...  5:)
