### ISSUE TITLE
MFTparser

### ISSUE THREAD

**Issue by AsafEitani** [volatilityfoundation/volatility3#312]
**Is your feature request related to a problem? Please describe.**
The need of MFT parsing. used to have that in volatility 2.

**Describe the solution you'd like**
Add MFT plugin from volatility 2

**Describe alternatives you've considered**
Filescan + dump + external MFT parser.
But right now every dump I tested seems to return an empty filescan result: #278 

**Additional information**
I mainly used it with the timeliner plugin in order to create a more extensive timeline.
Maybe merge them together?

**Comment by lightoyou** [comment]
Just a quick question what is the equivalent of mftparser inside volatility3 ? cause windows.symlinkscan has no --ouput=body very usful to use log2timeline/plaso :)

**Comment by ikelos** [comment]
Hiya, there isn't yet really an equivalent of mftparser (hence this issue).  The symlinkscan supports the timeliner plugin which can produce body files, so you'd run something like:

`vol.py -f <filename> timeliner --plugin-filter symlinkscan --create-bodyfile`.  Any plugin that produces time-based information should have a timeliner interface that means it will be run automatically by timeliner (or can be filtered by it), and the results therefore output in body format.  If there's enhancements or improvements you'd like to the timeliner plugin, please file an issue and we'll try and improve it for you...  5:)

**Comment by ikelos** [comment]
You might also want to see if filescan gives you the information about files you were hoping to get from mftparser?
