### ISSUE TITLE
LDR modules

### ISSUE THREAD

**Issue by AsafEitani** [volatilityfoundation/volatility3#313]
**Is your feature request related to a problem? Please describe.**
LDR modules used to detect unlinked dlls, was under volatility 2 mafind.

**Describe the solution you'd like**
Add LDRmodules plugin like in volatility 2.

**Comment by ikelos** [comment]
There may already be functionality present in one of the other plugins, but I'll leave this here until we get confirmation...  5:)

**Comment by iMHLv2** [comment]
Ldrmodules basically diffs the output of vadinfo and dlllist (both of which are present in vol3). We can create ldrmodules for vol3, but probably will not happen until after the first release.

**Comment by pudii** [comment]
@ikelos I think this can be closed as well.

**Comment by ikelos** [comment]
Yep, thanks catching that!  5:)
