### ISSUE TITLE
Config defaults aren't used for optional values within the framework

### ISSUE THREAD

**Issue by ikelos** [volatilityfoundation/volatility3#324]
When a requirement is defined as `optional = True, default = <thing>` the configuration should contain `<thing>` rather than being empty.

**Comment by ikelos** [comment]
It looks like these are currently populated by the UI, rather than by the framework (see https://github.com/volatilityfoundation/volatility3/blob/master/volatility/cli/__init__.py#L414).

Options for having this happen as part of the framework include:
* Changing every plugin to access `requirement.config_value` or some method instead (since the configuration and the requirements aren't technically tied together, this seems a bad move)
* Making sure that when `unsatisified` is called, it actually populates the configuration with the default if it's not present. This may require additional subpopulation (since I'm not sure we descend into optional requirements), and if the UI doesn't call `unsatisified`, then it's probably not doing its job, but it might cover most places this could be a problem.
* The third option is just pulling `populate_config` inside the framework in some way.

**Comment by AsafEitani** [comment]
@ikelos getting an error on the fix:
```
Traceback (most recent call last):
  File "/home/dev/volatility3/vol.py", line 10, in <module>
    volatility.cli.main()
  File "/home/dev/volatility3/volatility/cli/__init__.py", line 515, in main
    CommandLine().run()
  File "/home/dev/volatility3/volatility/cli/__init__.py", line 299, in run
    constructed = plugins.construct_plugin(ctx, automagics, plugin, base_config_path, progress_callback, self)
  File "/home/dev/volatility3/volatility/framework/plugins/__init__.py", line 51, in construct_plugin
    constructed = plugin(context, plugin_config_path, progress_callback = progress_callback)
  File "/home/dev/volatility3/volatility/framework/interfaces/plugins.py", line 106, in __init__
    self.config[requirement.name] = requirement.default
  File "/home/dev/volatility3/volatility/framework/interfaces/configuration.py", line 150, in __setitem__
    self._setitem(key, value)
  File "/home/dev/volatility3/volatility/framework/interfaces/configuration.py", line 160, in _setitem
    self._data[key] = self._sanitize_value(value)
  File "/home/dev/volatility3/volatility/framework/interfaces/configuration.py", line 188, in _sanitize_value
    raise TypeError("Invalid type stored in configuration")
TypeError: Invalid type stored in configuration
```

**Comment by ikelos** [comment]
Hmmm, ok.  Would you be able to provide the plugin you ran, and then then add some debugging in to `_setitem` to print out the `key` and the `repr(value)`, so we can figure out what type's being handed in?

**Comment by AsafEitani** [comment]
so the plugin i ran is cmdline and the thing that causes the _setitem problem is this pair:
```
key: pslist 
repr(value): None
```

**Comment by ikelos** [comment]
Ok, I believe this should now be sorted as of `eb02ee1`.  Please give it a test and let me know if it resolves this problem...

**Comment by cecio** [comment]
Testing some modifications on vadinfo.py plugin (pr #325) I had the same error. I'm using a version with commit `eb02ee1`.

The dumped values in _setitem are:
```
key: address
value: None
```

**Comment by AsafEitani** [comment]
@ikelos I'm getting error on timeliner plugin, the values are: `key: plugins value: None`
```
Volatility 3 Framework 1.2.0-beta.1
66.67		Building linux caches
Traceback (most recent call last):
  File "/home/dev/volatility3/vol.py", line 10, in <module>
    volatility.cli.main()
  File "/home/dev/volatility3/volatility/cli/__init__.py", line 515, in main
    CommandLine().run()
  File "/home/dev/volatility3/volatility/cli/__init__.py", line 299, in run
    constructed = plugins.construct_plugin(ctx, automagics, plugin, base_config_path, progress_callback, self)
  File "/home/dev/volatility3/volatility/framework/plugins/__init__.py", line 51, in construct_plugin
    constructed = plugin(context, plugin_config_path, progress_callback = progress_callback)
  File "/home/dev/volatility3/volatility/framework/plugins/timeliner.py", line 46, in __init__
    super().__init__(*args, **kwargs)
  File "/home/dev/volatility3/volatility/framework/interfaces/plugins.py", line 107, in __init__
    self.config[requirement.name] = requirement.default
  File "/home/dev/volatility3/volatility/framework/interfaces/configuration.py", line 150, in __setitem__
    self._setitem(key, value)
  File "/home/dev/volatility3/volatility/framework/interfaces/configuration.py", line 160, in _setitem
    self._data[key] = self._sanitize_value(value)
  File "/home/dev/volatility3/volatility/framework/interfaces/configuration.py", line 188, in _sanitize_value
    raise TypeError("Invalid type stored in configuration")
TypeError: Invalid type stored in configuration
```

**Comment by ikelos** [comment]
Yeah, I thought I'd found the only place that happened (but I'm also *really* surprised that the `populate_config` function in the CLI isn't catching all of these?).  I'll go through the codebase again with a finer tooth comb...

**Comment by ikelos** [comment]
Ok, so I need to figure out the semantics with @npetroni 

Essentially the configuration tree only ever holds simple type values (which does not currently include None).  The requirement class allows for a value of `None` as the default, but the configuration doesn't allow a value of `None` as a value.  What this means is that when accessing the config dictionary, you can't ensure that the requirement is always there, because the default for it may have been `None` (and therefore have no entry in the dictionary).  I think the idea behind this was to ensure that the config could be stored as json and keep things simple.  JSON does technically have support for null values, and it'd be quite handy to be able to rely on the simple definition of a requirement ensuring that `config[requirement_name]` doesn't throw an exception.

I've added a branch, `issue324-add-none-to-simpletypes`, which tests this out.  I can't immediately foresee any issues with allowing None into the configuration tree, I don't think anyone had assumptions that it could never be there, and all the unsatisfied methods should validate that their value is of their type (ie, not None), so I think this should be fine but I just wanted to double check that doing this makes sense...

**Comment by ikelos** [comment]
@npetroni Any thoughts on this?  Essentially, do we change the semantics of the config tree, so that config entries can be present, but `None`, rather than only allowing populated simple types in the tree?  The JSON will support it, so it's just if we think things might break/become more difficult if we have to start handling None (although, it's probably easier than including `config.get('item', None)` which seems to be the alternative.  The changes can be found in [issue324-add-none-to-simpletypes](https://github.com/volatilityfoundation/volatility3/tree/issue324-add-none-to-simpletypes) which I'll make a merge request if it's the direction we want to go...
