### ISSUE TITLE
interfacing with volatility3 bypassing the command line

### ISSUE THREAD

**Issue by MarkoMark98** [volatilityfoundation/volatility3#360]
Hi, I have to develope a python framework that interface itself with volatility, so I'm wondering if it's possible to use volatility bypassing the command line, calling the services directly in a python script. Or whether it is possible to instantiate an object to wich pass the command line arguments. Thanks so much.

**Comment by ikelos** [comment]
Absolutely it is, volatility3 is designed to be used as a library.  You can find information on how to use the framework as a library at https://github.com/volatilityfoundation/volatility3/blob/master/doc/source/using-as-a-library.rst, and you can find the CLI to see how it plugs into the framework at https://github.com/volatilityfoundation/volatility3/blob/master/volatility/cli/__init__.py.  There's also a model web interface for the library, which interfaces with the library at https://github.com/volatilityfoundation/volumetric/blob/master/volumetric/api.py.

Hopefully this answers your question, but if not the quickest way of getting in touch with us is to join the #vol3-users or #vol-dev channel on slack at https://www.volatilityfoundation.org/slack.  I hope this helps, and I'm going to close the issue as answered, but others will still be able to search for it under closed tickets.
