### ISSUE TITLE
Error running windows.info plugin

### ISSUE THREAD

**Issue by dadokkio** [volatilityfoundation/volatility3#373]
**Describe the bug**
Running windows info plugin returns error

**Context**
Volatility Version:  Volatility 3 Framework 2.0.0-beta.1
Operating System:  linux
Python Version:  3.9
Suspected Operating System:  windows
Command:  ./vol.py -f ./AMF_MemorySamples/windows/sample001.bin windows.info

**Screenshots**
![image](https://user-images.githubusercontent.com/355183/98793248-f17ffd00-2407-11eb-9483-ceb9eec9ad35.png)

**Additional information**
Other plugins on the same image work properly

**Comment by ikelos** [comment]
Thanks, this should have been resolved by commit `44c37d97612dacc210bbeb9c571d740527f93209`.  Please could you test this and let us know if it's been resolved?

**Comment by dadokkio** [comment]
Yes, it's fixed. Thanks!
