### ISSUE TITLE
references missing Type/Symbol/Enum: '_OBJECT_HEADER_HANDLE_REVOCATION_INFO' with psscan

### ISSUE THREAD

**Issue by cecio** [volatilityfoundation/volatility3#375]
**Describe the bug**
Running the PsScan plugin with a Windows 10 dump, I see the error 
`references missing Type/Symbol/Enum: '_OBJECT_HEADER_HANDLE_REVOCATION_INFO'`

**Context**
Volatility Version:  Volatility 3 Framework 2.0.0-beta.1
Operating System:  Linux
Python Version:  3.8.6
Suspected Operating System:  Win 10
Command:  python3 vol.py -f win10.dmp windows.psscan

**To Reproduce**

1. Use command above
2. I get the following output
```
PID     PPID    ImageFileName   Offset  Threads Handles SessionIdWow64   CreateTime      ExitTime        File output


Volatility experienced a symbol-related issue:
nt_symbols1!_OBJECT_HEADER_HANDLE_REVOCATION_INFO: Type nt_symbols1!_OBJECT_HEADER_HANDLE_REVOCATION_INFO references missing Type/Symbol/Enum: '_OBJECT_HEADER_HANDLE_REVOCATION_INFO'

        * An invalid symbol table
        * A plugin requesting a bad symbol
        * A plugin requesting a symbol from the wrong table

No further results will be produced
```

**Expected behavior**
See the psscan output

**Screenshots**
NA

**Additional information**
The exact same command with the same image was working fine with older versions (for example commit `ae3a97e2c70e31fc5820b4ea810a6cfa6d21d720`)

**Comment by ikelos** [comment]
Thanks, we previously had a far too generic exception catching, which as part of the LGTM code review, was reduced to a more specific handler.  Unfortunately, we didn't handle some of the expected errors that might arise.  I'd added SymbolError to the list of caught exceptions which should now return it to its previous method of operation.  Thanks for spotting it!  5:)
