### ISSUE TITLE
Issue with Dumping Files in Plugin Output

### ISSUE THREAD

**Issue by Digibyte707** [volatilityfoundation/volatility3#376]
**Describe the bug**
An error message appears when attempting to dump PEs as part of the PSlist and Modscan plugins (only plugins tested so far). 
**Context**
Volatility Version:  3 (Version 2.0.0-beta.1)
Operating System:  Ubuntu
Python Version:  3.6.9
Suspected Operating System:  Windows 10, Windows XP

The error messages appear alongside the following messages –
“Unable to dump PE with pid [pid value here]:”
“TypeError:”
The error message for both messages states – 
“Can't instantiate abstract class CLIDirectFileHandler with abstract methods fileno, flush, isatty, read, readable, readline, readlines, seek, seekable, tell, truncate, writable, write, writelines”

**To Reproduce**
1. Use commands in screenshots.
2. See error

**Expected Behavior**
The desired functionality is to dump files related to various plugins to a specific output directory for later analysis.

**Screenshots**
WinXP - Modscan
![image](https://user-images.githubusercontent.com/51827824/99222506-f5ad7100-279f-11eb-9e6f-26eba97925ce.png)

WinXP - PSlist
![image](https://user-images.githubusercontent.com/51827824/99223243-61dca480-27a1-11eb-889e-9a184ee7d99f.png)

![image](https://user-images.githubusercontent.com/51827824/99222524-04942380-27a0-11eb-81d1-1d775e03a1aa.png)

Windows 10 – Modscan
![image](https://user-images.githubusercontent.com/51827824/99222549-107fe580-27a0-11eb-8fad-c1e5e40ba853.png)

Windows 10 – Pslist
![image](https://user-images.githubusercontent.com/51827824/99222586-1fff2e80-27a0-11eb-831b-1061fca5151d.png)
![image](https://user-images.githubusercontent.com/51827824/99222604-255c7900-27a0-11eb-868f-3dca2e680552.png)

 
**Additional information**
The issue does not appear to relate with the compatibility of an image file with Volatility 3. For example, both Windows 10 Pro and Windows XP .img and .mem files were used and the same error message was reproduced in both instances.

**Comment by ikelos** [comment]
Hmmm, so it appears this is an issue with python 3.6, and python 3.7 doesn't exhibit the problem.  I'll look into it and see if I can figure out what's going wrong...  5:)

**Comment by ikelos** [comment]
Ok, think I got it.  Please give the latest version a test and feel free to reopen this if you still encounter the error...  5:)
