### ISSUE TITLE
--output-dir not working

### ISSUE THREAD

**Issue by AsafEitani** [volatilityfoundation/volatility3#386]
**Describe the bug**
Running a --dump plugin with the --output-dir doesn't work - the dump files are not created at all.
running without --output-dir creates the files under the current directory as expected.

**Context**
Volatility Version: 2.0.0-beta.1
Operating System: Windows 10
Python Version:  3.6.9
Suspected Operating System:  Windows 2012 R2 x64
Command: `python vol.py -vvv -r json --output-dir C:\temp -f dump.dd windows.vadinfo --dump

**To Reproduce**

1. use any --dump plugin (I checked mainly on `vadinfo`) and --output-dir
2. See that files are not created

**Expected behavior**
Creation of the dumped files at the wanted location.

**Comment by ikelos** [comment]
In you example you haven't populated `--output-dir`.  It takes an argument and otherwise outputs to the current directory.  I'd expect you to get a lot of files in the current directory?  If not then we can investigate further, but please try specifying a directory there.  There isn't a flag to say give me files or not, it should always create files if it's a file-creating plugin...

**Comment by AsafEitani** [comment]
Sorry my bad the command line was wrong. When --output-dir is present no files are created.

**Comment by ikelos** [comment]
Hmmm, ok.  I'll need to test it on a windows system, it may be that the `\` isn't getting interpreted correctly.  Could you try `C:\\temp` as a path please, with two slashes?  I'll try and fire up a windows system later to figure out what's going on but this will helps me understand if it's the shell or the program that's causing the problem...

**Comment by AsafEitani** [comment]
Okay I found the issue, it seems I gave `--output-dir` a folder that doesn't exists.... Sorry about that.
It does displays messages for each file not being able to create, but maybe it would be best if we check that the output dir exists before the plugin execute.
Also maybe we should create the directory but I assume we chose not to in the first place.
Again, sorry for the stupid mistake :)

**Comment by ikelos** [comment]
This should be fixed in `27fcd1a1`, please feel free to reopen this if you run into any issues...  5:)
