### ISSUE TITLE
pdbconv: parallelizing PDB processing ends up with BrokenProcessPool

### ISSUE THREAD

**Issue by Wenzel** [volatilityfoundation/volatility3#387]
**Describe the bug**
I'm using some functions from `pdbconv.py` to fetch and convert PDB to volatility profiles.
While trying to parallelize their execution, I was surprised to be faced with a sudden `BrokenProcessPool` for no clear reason.

**Context**
Volatility Version:  `1.2.1b1`
Operating System:  `Ubuntu 20.04`
Python Version:  `3.8.5`

**To reproduce**

Here is the script I'm trying to execute.
~~~Python3
#!/usr/bin/env python3

import logging
import json
import time
import urllib
from urllib.request import pathname2url
from concurrent.futures import ProcessPoolExecutor, wait
from concurrent.futures.process import BrokenProcessPool
from volatility.framework.contexts import Context
from volatility.framework.symbols.windows.pdbconv import PdbReader, PdbRetreiver


def process_pdb(guid: str, age: int, pdb_filename: str):
    filename = PdbRetreiver().retreive_pdb(
        guid + str(age), file_name=pdb_filename, progress_callback=None
    )
    ctxt = Context()
    location = f"file:{pathname2url(filename)}"
    profile = PdbReader(ctxt, location).get_json()
    return profile


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    pool = ProcessPoolExecutor(max_workers=1)
    futures = []
    with open("data.json", "r") as f:
        data = json.load(f)

    for item in data:
        print(item)
        fut = pool.submit(process_pdb, item["signature"], item["age"], item["pdb_filename"])
        futures.append(fut)
        # this sleep is important !
        # if you remove it, BrokenProcessPool is not raised
        time.sleep(0.3)

    wait(futures)
    print("done waiting")
~~~

You can find the `data.json` file [on this Gist](https://gist.github.com/Wenzel/88741d8f85875b6c94a5735ac7dc0ee1)

This is the behavior that I get:
![Capture d’écran de 2020-12-02 19-25-06](https://user-images.githubusercontent.com/964610/100915029-2564b480-34d4-11eb-8ed1-ecfa4e11db11.png)

**Expected behavior**
I would have expected that all the PDBs were downloaded and processed.

**Additional information**
After more debugging in volatility, I found out that the pool worker crashes when calling
this function at some point.
https://github.com/volatilityfoundation/volatility3/blob/c9c37a9b352678ecf6f0afe96d33d4ae8bf1e732/volatility/framework/layers/resources.py#L94

This let me to search for an association of
- `BrokenProcessPool`
- `urlopen` function

And it seems that other people have experienced this, but for a Thread pool, and for Python 3.7.
However, with 3.8, the bug is supposed to be gone:
- https://github.com/astropy/astropy/issues/9699
- https://bugs.python.org/issue39853

But here we are running 3.8, and a Process pool.
So did we find a bug in Python's `urlopen` ?

What do you think ?

Thanks !

**Comment by Wenzel** [comment]
Update: by upgrading to the latest Volatility I can't repro this bug anymore.
`git bisect` tells me that https://github.com/volatilityfoundation/volatility3/commit/dd0f69098855d917ba0d4f37a58b3e7611b42f7b fixed the bug, which is actually the fix you provided for my previous issue https://github.com/volatilityfoundation/volatility3/issues/381 :-)

I should have upgraded immediately, but the important is that it's fixed.

Thanks !

**Comment by ikelos** [comment]
Hmmm, that's pretty strange, I'm not sure I see what would fix a thread pool issue in there, but glad it's fixed.  5:)

**Comment by Wenzel** [comment]
> Hmmm, that's pretty strange, I'm not sure I see what would fix a thread pool issue in there, but glad it's fixed. 5:)

it was actually a `BrokenProcessPool` issue.
Using a ThreadPool was fine
