### ISSUE TITLE
Docs: Writing new Templates and Objects.

### ISSUE THREAD

**Issue by NiklasBeierl** [volatilityfoundation/volatility3#390]
**Is your feature request related to a problem? Please describe.**
There is a subsection: "Writing new Templates and Objects" in "Writing more advanced Plugins" but it appears to be empty.
(See `vdoc/source/complex-plugin.rst`) Is this a Todo or did it get lost somewhere?

**Describe the solution you'd like**
If there is some documentation I missed, add it to `vdoc/source/complex-plugin.rst` otherwise it needs to be written. :)

**Describe alternatives you've considered**
Sadly it seems like the documentation in `volatility/framework/objects` is rather sparse.

**Comment by ikelos** [comment]
Yeah, unfortunately that was as far as we got with the documentation, and the heading was a place holder for the things that still need writing, but we will write, it just sort of slipped down the priority list...  5:S
