### ISSUE TITLE
VSL and teaching

### ISSUE THREAD

**Issue by koromodako** [volatilityfoundation/volatility3#391]
What does VSL require me (not) to do if I want to create a course which Volatility3 is part of (i.e. mentioned/explained in lessons and used during tutorials) ?

**Comment by awalters** [comment]
Thanks for reaching out. The Volatility Software License (VSL) was designed to encourage people to contribute back to the community they are benefiting from. Thus, if someone builds training material based on Volatility and makes that material available to others, the VSL asks that they make that material publicly available under the terms of the VSL.  Simply, the VSL was written to make sure any additions, including training material, are distributed with the same freedoms as Volatility.
