### ISSUE TITLE
how can i find official released vol.exe for windows?

### ISSUE THREAD

**Issue by syzby** [volatilityfoundation/volatility3#399]
Hi, volatility3 is a very nice project for memory forensic, how can i find official released vol.exe for windows? or is there a easy to make static vol.exe?
thank you!

**Comment by ikelos** [comment]
Hiya, so the answer is, we haven't done an official release yet, we're technically still in beta!  5:P  We're getting very close to an official release, so please check back again in late January, but for the time being you can find the first beta release (from over a year ago) on the releases page of github: https://github.com/volatilityfoundation/volatility3/releases.  If you open the assets list, you should be able to find the pre-compiled windows binaries there.  If you want to build your own, it should just be a case of getting `pyinstaller` on a windows system and  and running `pyinstaller vol.spec` or `pyinstaller volshell.spec` depending on which binary you're after (you'll need to make sure the various dependencies in setup.py are satisfied, but at the moment I think that's only pefile as a hard dependency).  Please let us know if you try to build it yourself and run into any issues, we're out to make things as easy as possible so feedback is always appreciated...  5:)

**Comment by syzby** [comment]
@ikelos **thank you so much!!!**

follow your instruction, I successfully build vol.exe and I test many plugins, it works fine.

my step are:
```
pip install pyinstaller pefile yara-python capstone pycryptodome

cd D:\github\volatility3

pyinstaller.exe vol.spec
```

**Comment by ikelos** [comment]
Awesome, thanks for the feedback and glad it built ok!  I'll close this issue, but it should still be available if people search for it if they need...  5:)
