### ISSUE TITLE
Changing the attribute of an object via a pointer does not work

### ISSUE THREAD

**Issue by japhlange** [volatilityfoundation/volatility3#400]
**Describe the bug**
As mentioned in https://github.com/volatilityfoundation/volatility3/pull/397#discussion_r547307215.

When trying to access an object constructed via a pointer like `part_table` in the example below I can access the object's attributes like `Partitions`, but changing them does not appear to change the actual value, as the value of `count` like in the last line is still 1.
```python
# part_table is the actual partition table offset and consists out of a dynamic amount of _PARTITION objects
# ~ part_table = context.object(net_symbol_table + constants.BANG + "_PARTITION_TABLE", 
                            # ~ layer_name = layer_name, 
                            # ~ offset = part_table_addr)
part_table = context.object(net_symbol_table + constants.BANG + "pointer",
                            layer_name = layer_name,
                            subtype = context.symbol_space.get_type(net_symbol_table + constants.BANG + "_PARTITION_TABLE"),
                            offset = tcpip_module_offset + part_table_symbol)
part_count = int.from_bytes(context.layers[layer_name].read(tcpip_module_offset + part_count_symbol, 1), "little")
part_table.Partitions.count = part_count
# part_count == 4
# part_table.Partitions.count is still 1 (default value)?
```
Here is the definition:
```json
"_PARTITION_TABLE": {
    "fields": {
        "Partitions": {
            "offset": 0,
            "type": {
                "count": 1,
                "kind": "array",
                "subtype": {
                    "kind": "struct",
                    "name": "_PARTITION"
                }
            }
        }
    },
    "kind": "struct",
    "size": 128
}
```
When changing the value of `count` when the part_table is constructed via the commented-out section in the example above it works.

**Context**
Volatility Version:  2.0.0
Operating System:  Manjaro Linux
Python Version:  3.8
Suspected Operating System:  Win10x64_16299
Command:  see code example above.

**To Reproduce**

1. Construct a struct in memory via a pointer and its subtype, then change its value.

**Comment by ikelos** [comment]
Hmmm, interesting it's only through a pointer...  5:S  As soon as it returns PartTable it should be working on a constructed instance of that table.  I'll need to do some investigating...  5:)

**Comment by ikelos** [comment]
Ok, I figured out what this was.  Basically, every time a pointer is called, it constructed a new copy of the object.  Since objects are typically static, that didn't seem like a problem, but obviously modifying attributes of an object isn't static, so we have to hang onto the object.  I've done with by add standard memoization, which should resolve the issue under the assumption that the pointer isn't dereferenced multiple times (and thus exist the cache).  Please let me know if this shows any weird behaviour for any reason...
