### ISSUE TITLE
windows.netscan doesn't generate any data for win10-x86 samples

### ISSUE THREAD

**Issue by mtressler** [volatilityfoundation/volatility3#423]
**Describe the bug**
When the plugin windows.netscan is run on an x86 sample it runs without error but no data is output.

**Context**
Volatility Version:  release/v2.0.0
Operating System:  Windows/WSL
Python Version:  3.8.2
Suspected Operating System:  win10-x86
Command:  python3 vol.py -f samples/win10-x86-2016-07-08.lime windows.netscan

**To Reproduce**
Run netscan plugin on x86 sample

**Expected behavior**
Should output all network objects in the sample

**Comment by ikelos** [comment]
Sounds like one for @japhlange to look at when he gets time (I understand he's busy at the moment)...

**Comment by japhlange** [comment]
Do you know the Windows build? It'd be great if you could either run `winver` on the live machine or the `windows.info` vol3 plugin :)

**Comment by mtressler** [comment]
Do you want the build of the sample or my machine?

**Comment by japhlange** [comment]
Of the memory sample.

**Comment by mtressler** [comment]
This is what I got from windows.info. I think this is the version 
Major/Minor     15.10586

**Comment by ikelos** [comment]
I can confirm on what appears to be the same image that no results are returned.  If it helps, I think the symbols it's using are: `ntkrpamp.pdb/44B89EEAB81F466591D6570331648068-1`.

I get a bunch of errors in the verbose log along the lines of:
```
DEBUG    volatility.plugins.windows.netscan: Found netw obj @ 0x826f538f of assumed type <class 'volatility.framework.symbols.windows.extensions.network._TCP_LISTENER'>
DEBUG    volatility.framework.symbols.windows.extensions.network: netw obj 0x826f538f invalid due to invalid address_family None
DEBUG    volatility.plugins.windows.netscan: Found netw obj @ 0x82713462 of assumed type <class 'volatility.framework.symbols.windows.extensions.network._TCP_ENDPOINT'>
DEBUG    volatility.framework.symbols.windows.extensions.network: <class 'volatility.framework.symbols.windows.extensions.network._TCP_ENDPOINT'> 0x82713462 invalid due to invalid tcp state 2189234800
DEBUG    volatility.plugins.windows.netscan: Found netw obj @ 0x85254350 of assumed type <class 'volatility.framework.symbols.windows.extensions.network._TCP_LISTENER'>
DEBUG    volatility.framework.symbols.windows.extensions.network: netw obj 0x85254350 invalid due to invalid address_family None
```

Not sure how many of those are supposed to turn up, but there's lots, mostly with address_family being None...

**Comment by japhlange** [comment]
Yeah, the offsets are wrong. I'm on it, gonna take a few days though ;)

What's fascinating is that the existing symbols work for Win10x86_10240 which is older but not for 10586... who knows what Microsoft shuffled up that almost all symbol offsets changed from one release to the next.

**Comment by mtressler** [comment]
@ikelos I think with #428 being merged this issue can be closed.

**Comment by ikelos** [comment]
Cool, thanks.  5:)  Feel free to reopen if it's still an issue...  5:)
