### ISSUE TITLE
Psscan doesn't seem to provide a flag --physical

### ISSUE THREAD

**Issue by Le-no** [volatilityfoundation/volatility3#449]
The offset printed in psscan is the virtual offset. However, the possibility of providing a flag --physical, which will change the output to the physical address, is missing. 
The plugin pslist already supports this feature. A similar solution for psscan is still missing.

**Comment by ikelos** [comment]
I'm sorry this has been open so long, we were intentionally leaving this here as an easy fix to try and attract members of the community to contribute.  When I get a bit of time, I'll try to get it resolved...

**Comment by ikelos** [comment]
This has been closed by a very kind contribution by a member of the community!  5:)  Feel free to reopen this if there are issues of any kind with it...
