### ISSUE TITLE
"File does not exist" for native paths on Windows

### ISSUE THREAD

**Issue by SamB** [volatilityfoundation/volatility3#470]
**Describe the bug**
Volatility rejects native file paths passed for `-f` on Windows.

**Context**
Volatility Version:  dev-prerelease-1249-g1b57a899 (1b57a899e81b7cdc37ce03b275f28672764e02bb)
Operating System:  Microsoft Windows [Version 10.0.19043.844]
Python Version:  3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Suspected Operating System:  N/A
Command:  `python vol.py -f C:\Windows\explorer.exe windows.info`

**To Reproduce**

1. Run: `python vol.py -f C:\Windows\explorer.exe windows.info`
2. See error: `volatility: error: File does not exist: /C:/Windows/explorer.exe`

**Expected behavior**
I would expect this to look for the file at path `C:/Windows/explorer.exe` (**without** the leading slash), find it there, and then perhaps complain that it doesn't know what to do with that file because it's not a recognizable memory dump.

**Screenshots**

**Additional information**
It looks like the check in 1d35406ffee9890927efe693d79353446bea0734 isn't correct: it tries to use the path component of the URL directly; as you can see, this doesn't work on Windows.

**Comment by ikelos** [comment]
Ok, so I wasn't using urllib.request.url2pathname to reverse the parsed URL path into an actual path (which in windows removes the leading `/`).  This should now fix it for absolute and relative paths and URLs (including properly formed `file://` URLS), and it should bail out early if the file doesn't exist.  Please let me know if you still experience the problem (there were a few extra commits afterwards needed to get everything working).

**Comment by ikelos** [comment]
Ok, and thanks for the report and identifying the commit that was bad!  Massively helpful, thanks!  5:D
