### ISSUE TITLE
Volatility 3 doesn't work with fresh Windows builds in crashdump64 format

### ISSUE THREAD

**Issue by cryptouser201** [volatilityfoundation/volatility3#473]
**Describe the bug**
Volatility 3 doesn't work with fresh Windows builds

**Context**
Volatility Version:  Volatility 3 Framework 1.0.1
Operating System:  Windows 10 x64
Python Version:  3.8
Suspected Operating System:  Windows 10 20H2, Windows 10 21H1 preview, Windows Server 2022 preview
Command:  python vol.py -vvv -f memory.dmp windows.ssdt.SSDT

**To Reproduce**

1. Use command python vol.py -vvv -f memory.dmp windows.ssdt.SSDT
2. See error:

python vol.py -vvv -f WIN-20H2-20210307-150455.dmp windows.ssdt.SSDT
Volatility 3 Framework 1.0.1
INFO     volatility3.cli: Volatility plugins path: ['C:\\volatility3\\volatility3\\plugins', 'C:\\volatility3\\volatility3\\framework\\plugins']
INFO     volatility3.cli: Volatility symbols path: ['C:\\volatility3\\volatility3\\symbols', 'C:\\volatility3\\volatility3\\framework\\symbols']
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.nt_symbols
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.primary
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.primary
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.SSDT
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.nt_symbols
INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
DEBUG    volatility3.schemas: All validations will report success, even with malformed input
DEBUG    volatility3.framework.automagic.windows: Self-referential pointer not in well-known location, moving to recent windows heuristic
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.primary
Level 9  volatility3.framework.configuration.requirements: TypeError - Layer is not the required Architecture: WindowsCrashDump64Layer
Level 9  volatility3.framework.configuration.requirements: TypeError - Layer is not the required Architecture: FileLayer
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['WindowsCrashDump64Layer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: WintelHelper
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.primary
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.nt_symbols
INFO     volatility3.framework.automagic.pdbscan: No suitable kernels found during pdbscan
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.SSDT.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.SSDT.nt_symbols

Unsatisfied requirement plugins.SSDT.primary: Memory layer for the kernel
Unsatisfied requirement plugins.SSDT.nt_symbols: Windows kernel symbols

A symbol table requirement was not fulfilled.  Please verify that:
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

A translation layer requirement was not fulfilled.  Please verify that:
        A file was provided to create this layer (by -f, --single-location or by config)
        The file exists and is readable
        The necessary symbols are present and identified by volatility3
Unable to validate the plugin requirements: ['plugins.SSDT.primary', 'plugins.SSDT.nt_symbols']

**Additional information**

Hello.
Volatility 3 doesn't work with fresh builds of Windows 10 and Windows Server.
Dumps you can download from links:

Windows 10 20H2 x64: https://disk.yandex.ru/d/-U6FKDvnedl5vg
Windows 10 21H1 x64 preview: https://disk.yandex.ru/d/4p38pC4D7tt7vw
Windows Server 2022 x64 preview: https://disk.yandex.ru/d/OxW0Z2oPADjr9Q

Output for all dumps looks identical

**Comment by ikelos** [comment]
Hi there, thanks for the extensive report!  5:)

It looks a though all those images are using a crashdump64 format and just to verify that it's not volatility 3's implementation that's causing the problems I used volatility 2 to try to convert it to a raw image.  The file came out with 0 bytes, so I'm more concerned that the image files may not have been written to the crashdump64 format in the way we were expecting.

Do you have tools that can read the format you provided and convert them into raw memory dumps?  It may be that we can update the crashdump handler to support them, but I suspect that's where the problem lies, rather than in the latest windows versions?  Do you have any other images written in the same format (from older versions of windows) that *do* work with volatility 3, which might answer the question of whether it's the file format or the version of the operating system?

**Comment by cryptouser201** [comment]
Yes, volatility 3 works with Windows 10 x64 1903 build (dmp file format):

python vol.py -v -f C:\Windows10-1903x64-2.dmp windows.info
Volatility 3 Framework 1.0.1
INFO     volatility3.cli: Volatility plugins path: ['C:\\volatility3\\volatility3\\plugins', 'C:\\GitRepository\\volatility3\\volatility3\\framework\\plugins']
INFO     volatility3.cli: Volatility symbols path: ['C:\\volatility3\\volatility3\\symbols', 'C:\\GitRepository\\volatility3\\volatility3\\framework\\symbols']
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
INFO     volatility3.schemas: Dependency for validation unavailable: jsonschemacanner
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: WintelHelper
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
Progress:  100.00               PDB scanning finished
Variable        Value
INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema

Kernel Base     0xf80366811000
DTB     0x1aa000
Symbols C:/volatility3/volatility3/symbols/windows/ntkrnlmp.pdb/35A038B1F6E2E8CAF642111E6EC66F57-1.json.xz
Is64Bit True
IsPAE   False
primary 0 WindowsIntel32e
memory_layer    1 WindowsCrashDump64Layer
base_layer      2 FileLayer
KdDebuggerDataBlock     0xf80366c325e0
NTBuildLab      18362.1.amd64fre.19h1_release.19
CSDVersion      0
KdVersionBlock  0xf80366c363c8
Major/Minor     15.18362
MachineType     34404
KeNumberProcessors      1
NtSystemRoot    C:\Windows
NtProductType   NtProductWinNt
NtMajorVersion  10
NtMinorVersion  0INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema

PE MajorOperatingSystemVersion  10
PE MinorOperatingSystemVersion  0
PE Machine      34404

Volatility 2 works with uploaded Windows 10 20H2 dmp file:

python.exe vol.py --profile=Win10x64_19041 --file="C:\WIN-20H2-20210307-150455.dmp" crashinfo
Volatility Foundation Volatility Framework 2.6.1
_DMP_HEADER64:
 Majorversion:         0x0000000f (15)
 Minorversion:         0x00004a62 (19042)
 KdSecondaryVersion    0x00000041
 DirectoryTableBase    0x006d4002
 PfnDataBase           0xffff898000000000
 PsLoadedModuleList    0xfffff8072442d310
 PsActiveProcessHead   0xfffff807244210c0
 MachineImageType      0x00008664
 NumberProcessors      0x00000002
 BugCheckCode          0x5454414d
 KdDebuggerDataBlock   0xffffc90edef04080
 ProductType           0x00000001
 SuiteMask             0x00000110
 WriterStatus          0x45474150
 Comment               PAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGE
 DumpType              Full Dump


Physical Memory Description:
Number of runs: 5
FileOffset    Start Address    Length
00002000      00001000         0009f000
000a1000      00100000         7ec94000
7ed35000      7ed95000         00137000
7ee6c000      7ef1b000         01080000
7feec000      7ffff000         00001000
7feec000      7ffff000

I uploaded raw image for testing (Windows 21H1 preview, x64), but it has cyphered KDBG structure:
https://disk.yandex.ru/d/8y-69fuEgjacwQ

Volatility 2 works with this image:

python.exe vol.py --profile=Win10x64_19041 --file=Win1021H1preview.raw kdbgscan
Volatility Foundation Volatility Framework 2.6.1
**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_19041 (6.4.19041 64bit)
Offset (V)                    : 0xf80428c1da50
Offset (P)                    : 0x7e904a50
KdCopyDataBlock (V)           : 0xf80428562eac
Block encoded                 : Yes
Wait never                    : 0xa8588008779548ac
Wait always                   : 0x10ef22611d0b440
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_19041
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 20257.1.amd64fre.fe_release.2011
PsActiveProcessHead           : 0xfffff80428c43580 (48 processes)
PsLoadedModuleList            : 0xfffff80428c50cb0 (164 modules)
KernelBase                    : 0xfffff8042801d000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff804277cb000 (CPU 0)

**Comment by ikelos** [comment]
I think I figured out what was causing this.  It appears as though Microsoft changed the address that the self-referential pointer lived at, because apparently bad guys can use it too, so they've randomized it at [boot time](https://blahcat.github.io/2020/06/15/playing_with_self_reference_pml4_entry/).  I've attempted to limit the number of addresses tested to just those I've encountered empirically (between 0x1e0 and 0x1ff), so it should still be pretty speedy (we'll have to see how much it slows things down).  This has been updated as of `a1c5f5e` and should now work for all three images.  Please let me know if you encounter more like this...

**Comment by cryptouser201** [comment]
Thanks! It is works now!

Btw, you are using "http://msdl.microsoft.com/download/symbols" link in pdbconv.py. Microsoft already migrate it to https protocol - https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/microsoft-public-symbols. 
If you don't change it, you can get some hidden bugs with symbols downloading in future (i got it already in one case).
