### ISSUE TITLE
Enumeration not found in netscan-win81-x641 table: _PARTITION_TABLE

### ISSUE THREAD

**Issue by michaelmagyar** [volatilityfoundation/volatility3#474]
**Describe the bug**
I am having trouble running windows.netstat on any of the AWS Windows images (Server 2012R2, 2016, and 2019). Each time, I receive an error that _PARTITION_TABLE is not defined in the symbol tables. Netscan runs fine on the same image

**Context**
Volatility Version: Volatility 3 Framework 1.0.1 (just pulled)
Operating System: Ubuntu 20.04.2 LTS (AWS AMI)
Python Version: 3.8.5
Suspected Operating System: AWS Images for Windows Server 2012 R2, Server 2016, Server 2019 (all 64-bit)
Memory Capture: FTK Imager Lite
Command: ./vol.py -vvv -f memdump.mem windows.netstat

**To Reproduce**
1. Create new AWS EC2 instance of any of those Windows versions
2. Capture image (I used FTK Imager Lite from a second volume and saved memory to a third volume)
3. Move capture volume to forensic instance and mount drive
4. Run command 

**Example of netstat on 2012 R2 (6.3.9600)**

> Volatility 3 Framework 1.0.1
> INFO     volatility3.cli: Volatility plugins path: ['/home/ubuntu/Downloads/volatility3/volatility3/plugins', '/home/ubuntu/Downloads/volatility3/volatility3/framework/plugins']
> INFO     volatility3.cli: Volatility symbols path: ['/home/ubuntu/Downloads/volatility3/volatility3/symbols', '/home/ubuntu/Downloads/volatility3/volatility3/framework/symbols']
> DEBUG    volatility3.framework: No module named 'Crypto'
> DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.cachedump based on file: windows/cachedump
> DEBUG    volatility3.framework: No module named 'Crypto'
> DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.hashdump based on file: windows/hashdump
> DEBUG    volatility3.framework: No module named 'Crypto'
> DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.lsadump based on file: windows/lsadump
> INFO     volatility3.cli: The following plugins could not be loaded (use -vv to see why): volatility3.plugins.windows.cachedump, volatility3.plugins.windows.hashdump, volatility3.plugins.windows.lsadump
> INFO     volatility3.framework.automagic: Detected a windows category plugin
> INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.NetStat.primary
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.NetStat.nt_symbols
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.NetStat.primary
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.NetStat.primary
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.NetStat.primary
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.NetStat
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.NetStat.nt_symbols
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.NetStat.nt_symbols
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.NetStat.nt_symbols
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.NetStat
> INFO     volatility3.framework.automagic: Running automagic: LayerStacker
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.NetStat.primary
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.NetStat.nt_symbols
> DEBUG    volatility3.framework.automagic.windows: DTB was found at: 0x1aa000
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.NetStat.primary
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.NetStat.primary
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.NetStat.nt_symbols
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.NetStat.primary
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.NetStat.primary.memory_layer
> Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
> Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
> Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
> Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.NetStat.nt_symbols
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.NetStat.nt_symbols
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.NetStat.nt_symbols
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.NetStat
> DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
> INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
> INFO     volatility3.framework.automagic: Running automagic: WintelHelper
> INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.NetStat.nt_symbols
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.NetStat.nt_symbols
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.NetStat.nt_symbols
> DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
> DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
> DEBUG    volatility3.framework.symbols.windows.pdbutil: Using symbol library: ntkrnlmp.pdb/287E489F93AA4C6D94B9CD1469B7F9DE-1
> DEBUG    volatility3.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf80165a7f000
> Progress:  100.00		PDB scanning finished                     
> Offset	Proto	LocalAddr	LocalPort	ForeignAddr	ForeignPort	State	PID	Owner	Created
> DEBUG    volatility3.plugins.windows.netscan: Determined OS Version: 6.3 15.9600
> DEBUG    volatility3.plugins.windows.netscan: Determined symbol filename: netscan-win81-x64
> DEBUG    volatility3.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT
> DEBUG    volatility3.framework.symbols: Unresolved reference: nt_symbols1!_LDRP_DLL_SNAP_CONTEXT
> DEBUG    volatility3.plugins.windows.netstat: Found tcpip.sys image base @ 0xf800c28b6000
> DEBUG    volatility3.plugins.windows.netstat: Found tcpip.pdb: EF5FEB3F24CD434F84253EC4DBCDC3CC-2
> DEBUG    volatility3.framework.symbols.windows.pdbutil: Using symbol library: tcpip.pdb/EF5FEB3F24CD434F84253EC4DBCDC3CC-2
> 
> 
> DEBUG    volatility3.cli: Traceback (most recent call last):
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/symbols/__init__.py", line 139, in _weak_resolve
>     return getattr(self._dict[table_name], get_function)(component_name)
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/symbols/intermed.py", line 54, in _delegate_function
>     return getattr(self._delegate, name)(*args, **kwargs)
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/symbols/intermed.py", line 674, in get_type
>     return self.natives.get_type(self.name + constants.BANG + type_name)
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/symbols/native.py", line 74, in get_type
>     _native_type, native_format = self._native_dictionary[type_name]
> KeyError: '_PARTITION_TABLE'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/contexts/__init__.py", line 104, in object
>     object_template = self._symbol_space.get_type(object_type)
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/symbols/__init__.py", line 181, in get_type
>     self._resolved[type_name] = self._weak_resolve(SymbolType.TYPE, type_name)  # type: ignore
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/symbols/__init__.py", line 141, in _weak_resolve
>     raise exceptions.SymbolError(component_name, table_name,
> volatility3.framework.exceptions.SymbolError: Type netscan-win81-x641!_PARTITION_TABLE references missing Type/Symbol/Enum: '_PARTITION_TABLE'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/Downloads/volatility3/volatility3/cli/__init__.py", line 327, in run
>     renderers[args.renderer]().render(constructed.run())
>   File "/home/ubuntu/Downloads/volatility3/volatility3/cli/text_renderer.py", line 178, in render
>     grid.populate(visitor, outfd)
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/renderers/__init__.py", line 211, in populate
>     for (level, item) in self._generator:
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/plugins/windows/netstat.py", line 443, in _generator
>     for netw_obj in self.list_sockets(self.context, self.config['primary'], self.config['nt_symbols'],
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/plugins/windows/netstat.py", line 393, in list_sockets
>     for endpoint in cls.parse_partitions(context, layer_name, net_symbol_table, tcpip_symbol_table,
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/plugins/windows/netstat.py", line 245, in parse_partitions
>     part_table = context.object(net_symbol_table + constants.BANG + "_PARTITION_TABLE",
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/contexts/__init__.py", line 106, in object
>     object_template = self._symbol_space.get_enumeration(object_type)
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/symbols/__init__.py", line 217, in get_enumeration
>     retval = self._weak_resolve(SymbolType.ENUM, enum_name)
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/symbols/__init__.py", line 139, in _weak_resolve
>     return getattr(self._dict[table_name], get_function)(component_name)
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/symbols/intermed.py", line 54, in _delegate_function
>     return getattr(self._delegate, name)(*args, **kwargs)
>   File "/home/ubuntu/Downloads/volatility3/volatility3/framework/symbols/intermed.py", line 438, in get_enumeration
>     raise exceptions.SymbolError(enum_name, self.name,
> volatility3.framework.exceptions.SymbolError: Enumeration not found in netscan-win81-x641 table: _PARTITION_TABLE
> 
> Volatility experienced a symbol-related issue:
> netscan-win81-x641!_PARTITION_TABLE: Enumeration not found in netscan-win81-x641 table: _PARTITION_TABLE
> 
> 	* An invalid symbol table
> 	* A plugin requesting a bad symbol
> 	* A plugin requesting a symbol from the wrong table
> 
> No further results will be produced

**Additional information**
1. Looking through the symbols files, I don't see _PARTITION_TABLE in many of them, including netscan-win81-x64.json (referenced in the error above)
2. After doing some really hacky things (just copying the _PARTITION and _PARTITION_TABLE from other symbols), netstat started showing connections, but errored again on other missing symbols
3. A fuller list of missing symbols:
    * _PORT_ASSIGNMENT_ENTRY
    * _PORT_ASSIGNMENT_LIST
    * _PORT_ASSIGNMENT
    * _INET_PORT_POOL
    * _PARTITION
    * _PARTITION_TABLE
4. Although adding these symbols resolved the errors, netstat didn't finish (it just sat there) and it doesn't show the PIDs. I don't know if the missing PIDs are because the symbol values are wrong or if that is a separate issue (I have actually never seen netstat PIDs using volatility 3).

Thanks in advance for looking into this and for all of the work you all do.

**Comment by ikelos** [comment]
Thanks for the detailed diagnostics!  I'll check if @japhlange has any idea about this first since he knows the code better, before diving into it...  5:)

**Comment by japhlange** [comment]
Yeah, the cause is that I haven't added those symbols yet for Win8.1 x64. Your observations are correct, @michaelmagyar :D

I can see if I add them soon™ if that's okay. Apart from all symbols needing to be added to the symbol table we'll also need to make sure that the offsets _within_ the symbols themselves are correct for that Windows version too, which is why some processes for instance don't show up. The easiest way to do this is to check found network connection objects in memory (e.g. with volshell) and looking for the pointer to an EPROCESS object. If you have network connections belonging to a process you know, you can find that pointer by running pslist/psscan and recording that offset (be sure to record the virtual offset).

**Comment by michaelmagyar** [comment]
> I can see if I add them soon™ if that's okay.

I appreciate it, but don't stress over it. This is for a forensics course that needs to use AWS for various reasons, and I think we will be past those modules soon, so I will find another solution instead. (Also, lol at the ™ )

> Apart from all symbols needing to be added to the symbol table we'll also need to make sure that the offsets _within_ the symbols themselves are correct for that Windows version too, which is why some processes for instance don't show up. The easiest way to do this is to check found network connection objects in memory (e.g. with volshell) and looking for the pointer to an EPROCESS object. If you have network connections belonging to a process you know, you can find that pointer by running pslist/psscan and recording that offset (be sure to record the virtual offset).

I assumed that this was a problem. I tried going down this path to contribute, but I keep getting SymbolError Malformed name, so I must be doing something wrong. I have not been able to find resources for volatility3 volshell and the volatility2 volshell process seem different.

Thanks for the quick reply and help

**Comment by ikelos** [comment]
> I assumed that this was a problem. I tried going down this path to contribute, but I keep getting SymbolError Malformed name, so I must be doing something wrong. I have not been able to find resources for volatility3 volshell and the volatility2 volshell process seem different.

Sorry the documentation for volshell is a little sparse at the moment.  `help()` will give you a summary of the commands available, and accessing layers/symbols now all happens through `self.context` but hopefully it's not too much of a departure from volshell in volatility 2.  If you need any help with contributing do please shout on the vol3-dev slack channel.  It's not manned 24-hours a day, but I'm usually pretty quick at responding and I only sleep for 7 hours a day...  5;)

**Comment by japhlange** [comment]
@michaelmagyar Please have a look at the PR #476 if it resolves the issue. I couldn't reproduce the missing PIDs locally.
