### ISSUE TITLE
Support for process memory dump on Mac

### ISSUE THREAD

**Issue by aleksf** [volatilityfoundation/volatility3#485]
**Is your feature request related to a problem? Please describe.**
Volatility version 2 has a number of Mac plugins that supported dumping the memory, in version 3 none of the plugins seem to support it.

**Describe the solution you'd like**
Please implement process memory dump support for Mac in Volatility version 3.

**Describe alternatives you've considered**
I am not aware of any current alternatives, v2 helper scripts to generate symbols for latest MacOS kernels are broken, therefore v2 cannot be used anymore.

**Additional information**
N/A - should be clear from description

**Comment by ikelos** [comment]
Looks like one for @atcuno   5;)

**Comment by ikelos** [comment]
@atcuno, just checking progress on various bugs.  This one's definitely up your street, but hasn't seen much progress...

**Comment by ikelos** [comment]
Reopening this because it's still a valid request and we should add support into the framework...
