### ISSUE TITLE
Unable to validate the plugin requirements: ['plugins.Info.nt_symbols']

### ISSUE THREAD

**Issue by miqsoft** [volatilityfoundation/volatility3#497]
Hey I'm a computer science student and a newbie to Volatility, who is interested in memory forensics.
I tried to play around with an memory capture of my own system.
Then the following error occured.

**Describe the bug**
1.) Created a Memory Capture with FTK Imager 4.2.1.4 of a System with Windows 10 Home (Version 10.0.19041 Build 19041; x64) installed
2.)  Used volatility: python3 vol.py -vvvvvvv -f ./data/10x64_19041.mem windows.info
3.)  Error (see below)

**Context**
Volatility Version:  Volatility 3 Framework 1.0.1
Operating System:  Windows 10 Home (Version 10.0.19041 Build 19041; x64)
Python Version:  3.8.5
Suspected Operating System:  Windows 10 Home (Version 10.0.19041 Build 19041; x64)
Command:  python3 vol.py -vvvvvvv -f ./data/10x64_19041.mem windows.info

**Error Message**

INFO     volatility3.cli: Volatility plugins path: ['/mnt/d/ForensikTools/volatility3/volatility3/plugins', '/mnt/d/ForensikTools/volatility3/volatility3/framework/plugins']
INFO     volatility3.cli: Volatility symbols path: ['/mnt/d/ForensikTools/volatility3/volatility3/symbols', '/mnt/d/ForensikTools/volatility3/volatility3/framework/symbols']
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/plugins, /mnt/d/ForensikTools/volatility3/volatility3/framework/plugins
DEBUG    volatility3.framework: No module named 'Crypto'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.cachedump based on file: windows/cachedump
DEBUG    volatility3.framework: No module named 'Crypto'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.hashdump based on file: windows/hashdump
DEBUG    volatility3.framework: No module named 'Crypto'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.lsadump based on file: windows/lsadump
INFO     volatility3.cli: The following plugins could not be loaded (use -vv to see why): volatility3.plugins.windows.cachedump, volatility3.plugins.windows.hashdump, volatility3.plugins.windows.lsadump
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/automagic
Level 7  volatility3.cli: Cache directory used: /home/mikue/.cache/volatility3
INFO     volatility3.framework.automagic: Detected a windows category plugin
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 7  volatility3.framework.layers.resources: Available URL handlers: HTTPErrorProcessor, HTTPDefaultErrorHandler, HTTPRedirectHandler, ProxyHandler, HTTPBasicAuthHandler, ProxyBasicAuthHandler, HTTPDigestAuthHandler, ProxyDigestAuthHandler, AbstractHTTPHandler, HTTPHandler, HTTPSHandler, HTTPCookieProcessor, UnknownHandler, FileHandler, FTPHandler, CacheFTPHandler, DataHandler, VolatilityHandler, JarHandler
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 6  volatility3.framework.layers.elf: Exception: Bad magic 0x0 at file offset 0x0
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsIntelStacker
DEBUG    volatility3.framework.automagic.windows: DTB was found at: 0x6e0000
Level 8  volatility3.framework.automagic.stacker: Stacked IntelLayer using WindowsIntelStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 6  volatility3.framework.layers.elf: Exception: Offset 0x0 does not exist within the base layer
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary.memory_layer
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 6  volatility3.framework: Importing from the following paths: /mnt/d/ForensikTools/volatility3/volatility3/framework/layers
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: WintelHelper
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - testing fixed base address
DEBUG    volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset caused a page fault: 0x84200000
DEBUG    volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset caused a page fault: 0x32130b000
DEBUG    volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset caused a page fault: 0x386bc8000
DEBUG    volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset caused a page fault: 0x3fdecc000
DEBUG    volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset did not map to expected location: 0x59d44f000
DEBUG    volatility3.framework.automagic.pdbscan: Potential kernel_virtual_offset did not map to expected location: 0x5f95e1000
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - slow scan virtual layer
INFO     volatility3.framework.automagic.pdbscan: No suitable kernels found during pdbscan
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Unable to validate the plugin requirements: ['plugins.Info.nt_symbols']

**Comment by ikelos** [comment]
Hiya, this suggests, unfortunately, that the memory image doesn't contain a kernel with the appropriate PDB information, so even the slow scan (`Kernel base determination - slow scan virtual layer`) could not find an appropriate structure.  I'm afraid this could be due to smear during capture or some other reason, but without the appropriate kernel and similar information, that memory image will likely never be readable.  Your best bet it to try recapturing the memory.  I'm going to close this ticket off, but please feel free to reopen it if you get the same issue grabbing memory again...
