### ISSUE TITLE
linux.pslist not listing init_task / listhead "skipping" start element.

### ISSUE THREAD

**Issue by NiklasBeierl** [volatilityfoundation/volatility3#501]
**Describe the bug**
The pslist plugin does not list the init task. (pid 0) I do not know if that is intentional, to me it seems like a bug.

The underlying problem / way to fix it has two ways of looking at it. That is because of a certain detail in `volatility3.framework.symbols.linux.extensions.list_head.to_list`:  We initialize the `seen` set containing `self.vol.offset`.
That means that the `__iter__` function of the `list_head` will not `yield` the element from which the iteration was started. 
(In the case of PsList its the `init_task`)
This behaviour may or may not make sense depending on how you look at it. Either way, it should be specified and documented. 

Personally I think that the `seen` set should be initialized empty, so the initial element will be yielded in the last iteration if the linked list is "closed". 

The other solution would be to have `volatility3.framework.plugins.linux.pslist.PsList.list_tasks` `yield` the `init_task` explicitily. (If the filter function permits that.)

**Context**
Volatility Version:  1.0.1
Operating System:  Linux
Python Version:  3.9.4
Suspected Operating System:  
Command:  vol -f .. `linux.pslist.PsList`

**To Reproduce**

1. Use command ' vol -f /your/memdump `linux.pslist.PsList`
2. See that pid 0 is missing.

**Expected behavior**
Process with pid 0 should be listed.

**Comment by NiklasBeierl** [comment]
Someone just pointed out a number of things that make me reconsider my position on this:
Apparently the common scenario in the kernel is that the "first" list_head is **not** wrapped in a struct and thereby constitutes the "empty list". The task list seems to be a special case. So much for the implementation of `list_head.__iter__`.

And what completely defeats my complaint is that `ps` will also always skip pid 0. I would have sworn otherwise, but my terminal just proved me wrong. So perhaps the only thing one might still consider doing here is adding a little docstring to `list_head.__iter__` for noobs like me. :)

**Comment by ikelos** [comment]
@atcuno Any chance of a quick docstring here, so we can mark this as closed please?
