### ISSUE TITLE
When I create profile for ubuntu , I got like this error 

### ISSUE THREAD

**Issue by zin-htet-aung** [volatilityfoundation/volatility3#503]
I have dwarf and system.map files. When  I only use system.map file, I got like this 
```./dwarf2json linux --system-map System.map-4.8.0-36-generic > output.json
Volatility 3 Framework 1.0.1
Progress:  100.00		PDB scanning finished  
URI	Valid	Number of base_types	Number of types	Number of symbols	Number of enums	Windows info	Linux banner	Mac banner

file:///home/user/Downloads/tools/volatility3/dwarf2json/output.json	Unknown00	95999	0	-	-	-
``` and can't use in linux analysis

**Comment by atcuno** [comment]
Please paste the full command line input and output that generates the error. Also, add -vvvvvvvv to the command before re-running. Without this information, it is not possible to diagnose issues.

**Comment by ikelos** [comment]
If you're only using system.map, your JSON file won't have the appropriate type structure information, so this isn't expected to work?  You need to have both for it to be able to pull out the kernel string, which is used to identify which JSON file to use.  Given you've got the DWARF files, can I ask why you're not providing them to dwarf2json?  I'm not sure this is actually a bug, and we'd more a description to tell us what the problem actually is...

**Comment by zin-htet-aung** [comment]
I think I am not understand well in dwarf2json even read it . So can you write a command for me? I have "System.map-4.8.0-36-generic" and "module.dwarf" . How can I use these 2 files for Ubuntu profile.

**Comment by ikelos** [comment]
Hiya, the dwarf2json project is a separate project, so it might be better to ask [here](https://github.com/volatilityfoundation/dwarf2json/issues).  I don't know whether dwarf2json currently accepts DWARF information directly, or whether it has to be part of an ELF library, in which case you'll need the debug kernel from the environment you're trying to examine...

**Comment by ikelos** [comment]
There hasn't been any activity on this in several months, so I'm going to close it.  Please feel free to reopen it if you still need support (or visit the slack channel where the whole community can help and give you more interactive responses)...
