### ISSUE TITLE
PML4 self reference scanning error in some Windows dumps

### ISSUE THREAD

**Issue by cryptouser201** [volatilityfoundation/volatility3#505]
Hello!

There was good patch for supporting fresh Windows versions:

https://github.com/volatilityfoundation/volatility3/commit/a1c5f5e5e5ed2ba53711b34eeb63271fddf18ef2#diff-95515258a22a0ced4292d19bfd7dd395e507e8a7f9925efb6c4ec4207b00dd41R131

But some images have ptr_reference below, then 0x1E0, for example 0x10a:

0: kd> ? (poi(nt!MmPteBase) >> 0n39) & 0x1ff
Evaluate expression: 266 = 00000000`0000010a

0: kd> vertarget
Windows 10 Kernel Version 19042 MP (2 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Edition build lab: 19041.1.amd64fre.vb_release.191206-1406
Machine Name:
Kernel base = 0xfffff80679217000 PsLoadedModuleList = 0xfffff80679e41310

Is it possible to change bottom edge ptr_reference range in windows.py or add parameter for custom ptr_reference configuring in vol.py?

**Comment by ikelos** [comment]
I was a little concerned about whether this would make the initial identification of windows images slower, but it seems not to have too much of an impact.  I've created a branch for people to test, but I'd like to see this get a bit of speed testing, so if you could use this branch for a little while and report whether it causes you issues, that would be much appreciated...  5:)

**Comment by cryptouser201** [comment]
Thanks. DTB scanning with new fix take 4-5 seconds for 2 GB Windows dump. 

Analyzing of 12 GB dump give error with pdbconv, but it looks like not PML4 self reference scanning error (probably, i will open another case for this bug, if i can reproduce it on another big dump samples)

**Comment by ikelos** [comment]
If it got to pdbconv then it's already past the point where it did scanning for the PML4, so if you didn't notice a significant delay in the 12Gb image, then it should be good to merge in.

**Comment by cryptouser201** [comment]
Yes, i don't see delays between scanning 2Gb and 12Gb images. 
It will be good, if you apply patch to current branch.

**Comment by ikelos** [comment]
Hmmm, so this started giving us issues on our testing rig once it was added, and I've had direct experience of it breaking volatility's detection of one of my old images.  I'm sure we can get it fixed, but for now I've had to revert it whilst we investigate, sorry...  5:S

**Comment by cryptouser201** [comment]
Ok. Do you need dump with low ptr_reference value for testing?

**Comment by ikelos** [comment]
No, I think it might be higher ones causing the problem.  My current guess is that something shows up with both and we stop as soon as we hit the lower one.  I'll let you know how I get on...

**Comment by ikelos** [comment]
Hiya, so I think I've got a potential fix (as least ti resolves the mistaken DTB issue with image I had where I could recreate the issue I saw) and it's now in PR #511

Please could you test that and let me know if it works?  One of the other reports we had which may be related ( #509 ) may or may not be fixed by it, so I'm gonna wait on the results of that before pushing it and officially marking this as fixed...  5:)

**Comment by cryptouser201** [comment]
Yes, develop branch volatility3 build works with 2GB dump, which i mentioned earlier.

**Comment by ikelos** [comment]
Ok, but the current develop branch had the change reverted because of issues it caused, by commit `7ef7dd88f0`?  That's why I wanted to check that the problem came back and to check that PR #511 still fixed the issue?  Please could you test both again?

**Comment by cryptouser201** [comment]
Commit 505_2 brings errors:

F:\vol_test\develop_505_2>python.exe vol.py -f "F:\temp\dump_volatility\DESKTOP-20210404-144744.dmp" windows.pslist
Volatility 3 Framework 1.0.1
Traceback (most recent call last):
  File "vol.py", line 10, in <module>
    volatility3.cli.main()
  File "F:\vol_test\develop_505_2\volatility3\cli\__init__.py", line 618, in main
    CommandLine().run()
  File "F:\vol_test\develop_505_2\volatility3\cli\__init__.py", line 227, in run
    automagics = automagic.available(ctx)
  File "F:\vol_test\develop_505_2\volatility3\framework\automagic\__init__.py", line 41, in available
    import_files(sys.modules[__name__])
  File "F:\vol_test\develop_505_2\volatility3\framework\__init__.py", line 107, in import_files
    importlib.import_module(base_module.__name__ + "." + module)
  File "C:\Python38x64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\vol_test\develop_505_2\volatility3\framework\automagic\windows.py", line 181, in <module>
    class PageMapScanner(interfaces.layers.ScannerInterface):
  File "F:\vol_test\develop_505_2\volatility3\framework\automagic\windows.py", line 186, in PageMapScanner
    tests = [DtbTest64bit(), DtbTest32bit(), DtbTestPae()]
  File "F:\vol_test\develop_505_2\volatility3\framework\automagic\windows.py", line 134, in __init__
    super().__init__(layer_type = layers.intel.WindowsIntel32e,
TypeError: __init__() got an unexpected keyword argument 'num_entries'

**Comment by ikelos** [comment]
My bad, thanks for letting me know.  It should be fixed now...

**Comment by cryptouser201** [comment]
Thanks, developer build with commit 505_2 can analyze fresh Windows dumps correctly now.

**Comment by ikelos** [comment]
@cryptouser201 Thanks, if you could just confirm that it now correctly works on the one that was breaking before (it might work fine on lots of other images, the original break of the self-referential group being too small would only affect a small number of images), then I can get this merged and we can see if it causes any other problems...  5:)

**Comment by cryptouser201** [comment]
Interesting, that fresh branch https://github.com/volatilityfoundation/volatility3/tree/feature/pdbconv-vs19 works with dump with PML4 entry below 0x1E0:

```
0: kd> ? (poi(nt!MmPteBase) >> 0n39) & 0x1ff
Evaluate expression: 264 = 00000000`00000108

0: kd> vertarget
Windows 10 Kernel Version 21301 MP (4 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Edition build lab: 21301.1000.amd64fre.rs_prerelease.210123-1645
Machine Name:
Kernel base = 0xfffff807`2d000000 PsLoadedModuleList = 0xfffff807`2dc33e80
Debug session time: Sun May 23 19:50:17.395 2021 (UTC + 3:00)
System Uptime: 0 days 0:08:39.167

```

It looks like magic )

```
F:\volatility3-feature-pdbconv-vs19>python.exe vol.py -f "F:\temp\dump_volatility\WIN21H1-21301-20210523.dmp" windows.info
Volatility 3 Framework 1.1.1
Progress:  100.00               PDB scanning finished
Variable        Value

Kernel Base     0xf8072d000000
DTB     0x1aa000
Symbols file:///F:/GitRepository/volatility3_branch/volatility3-feature-pdbconv-vs19/volatility3/symbols/windows/ntkrnlmp.pdb/D06948C5F5258EFB9CF74852D40682A5-1.json.xz
Is64Bit True
IsPAE   False
primary 0 WindowsIntel32e
memory_layer    1 WindowsCrashDump64Layer
base_layer      2 FileLayer
KdDebuggerDataBlock     0xf8072dc00b20
NTBuildLab      21301.1000.amd64fre.rs_prereleas
CSDVersion      0
KdVersionBlock  0xf8072dc155d0
Major/Minor     15.21301
MachineType     34404
KeNumberProcessors      4
SystemTime      2021-05-23 16:50:17
NtSystemRoot    C:\Windows
NtProductType   NtProductWinNt
NtMajorVersion  10
NtMinorVersion  0
PE MajorOperatingSystemVersion  10
PE MinorOperatingSystemVersion  0
PE Machine      34404
PE TimeDateStamp        Thu May  7 21:36:21 2026
```

**Comment by ikelos** [comment]
Interesting, that branch does *not* look for values below 0x1E0?  
https://github.com/volatilityfoundation/volatility3/blob/feature/pdbconv-vs19/volatility3/framework/automagic/windows.py#L131

I wonder what's going on?

**Comment by cryptouser201** [comment]
It is your windows heuristic mechanism works (it looks like cr3 based). I tested it on new Windows 11 preview dump:
```
....
DEBUG    volatility3.framework.automagic.windows: Self-referential pointer not in well-known location, moving to recent windows heuristic
....
```

```
0: kd> ? (poi(nt!MmPteBase) >> 0n39) & 0x1ff
Evaluate expression: 415 = 00000000`0000019f
0: kd> vertarget
Windows 10 Kernel Version 22000 MP (4 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Edition build lab: 22000.1.amd64fre.co_release.210604-1628
Machine Name:
Kernel base = 0xfffff801`63800000 PsLoadedModuleList = 0xfffff801`644295c0
Debug session time: Sun Jul 25 17:49:24.532 2021 (UTC + 3:00)
System Uptime: 0 days 0:02:25.028
```

By the way, If we changed 
https://github.com/volatilityfoundation/volatility3/blob/deaa86f625a55cf5a59ac9e57766bdbd20de6516/volatility3/framework/automagic/windows.py#L363
on
```
   sections = [(0x6d0000, 0x50000)],
```
we can solve problem, which is mentioned in first post of current issue.

**Comment by ikelos** [comment]
That windows heuristic is from very old kernels that always loaded the kernel in approximately the same location.  We should increase the range rather than just change it (because that range worked for older systems) but we'd still need to check that it wouldn't cause false positives and make other systems break.  I surprised that extending the range helps, because the self-referential test it then runs uses a fixed self-referential pointer (0x1ED) from when very old versions of windows had a fixed location, so I suspect it's more chance than a specific fix unfortunately...

**Comment by ikelos** [comment]
Ok, so even with the reverse search, the windened search space keeps hitting false positives on older image.  I've since reduced the scope back to `0x1ff` to `0x1ee`.  Looks like this still needs more work, sorry...

**Comment by cryptouser201** [comment]
Did you test decrease PML4 range step-by-step? Pseudocode can be something like this:
if check(ptr_reference = range(0x1E0, 0x1FF)):
     return True
if check(ptr_reference = range(0x1C0, 0x1DF)):
    return True
if check(ptr_reference = range(0x1A0, 0x1BF)):
   return True

i haven't old Windows dump collection, therefore i can't test it ...

**Comment by ikelos** [comment]
I did, the point is that some selfref64 tests succeed at a low index, before very old pae images get tested at a specific index.  I've worked on trying to improve the situation with #559, which basically needs to be tested on as many images as possible before we merge it to make sure it doesn't suffer the same fate as previous tests...  5:)

**Comment by ikelos** [comment]
This new branch does test the whole range across a narrow set of locations and the more specific older ranges in places where the older ranges succeeded.  It also cleans the code up a lot, reducing it to a single testing mechanism that's much easier to understand.  Hopefully if we don't turn up any images that used to work but don't know, we can just swap it out.  We're also currently need to decide whether to support the old mechanism as a hidden flag, so we can easily test if that's the problem, or just go with this outright and tweak it over time...
