### ISSUE TITLE
FileScan Encoding Error

### ISSUE THREAD

**Issue by MaxZabuty** [volatilityfoundation/volatility3#514]
**Describe the bug**
When performing filescan on a memory sample with file names which contain different language characters I get an encoding error.

**Context**
Operating System:  Windows 10
Python Version:  3.9.0
Suspected Operating System:  Windows 10
Command:  python vol.py -f mem.raw windows.filescan.FileScan > files.txt

**To Reproduce**

1. Use command 'python vol.py -f mem.raw windows.filescan.FileScan > files.txt'
2. See error:
Traceback (most recent call last):B scanning finished
  File "c:\Users\x\Documents\volatility3\vol.py", line 10, in <module>
    volatility.cli.main()
  File "c:\Users\x\Documents\volatility3\volatility\cli\__init__.py", line 586, in main
    CommandLine().run()
  File "c:\Users\x\Documents\volatility3\volatility\cli\__init__.py", line 317, in run
    renderers[args.renderer]().render(constructed.run())
  File "c:\Users\x\Documents\volatility3\volatility\cli\text_renderer.py", line 178, in render
    grid.populate(visitor, outfd)
  File "c:\Users\x\Documents\volatility3\volatility\framework\renderers\__init__.py", line 217, in populate
    accumulator = function(treenode, accumulator)
  File "c:\Users\x\Documents\volatility3\volatility\cli\text_renderer.py", line 173, in visitor
    accumulator.write("{}".format("\t".join(line)))
  File "C:\Python3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 15-18: character maps to <undefined>

**Expected behavior**
Successful mapping of the memory sample files despite the different characters.

**Comment by iMHLv2** [comment]
Hi @MaxZabuty - sorry for the delay. Do you still have access to this memory sample? If so, would you either be able to share it so we can debug or run some additional debug commands to try and track this down?

**Comment by MaxZabuty** [comment]
> Hi @MaxZabuty - sorry for the delay. Do you still have access to this memory sample? If so, would you either be able to share it so we can debug or run some additional debug commands to try and track this down?

Unfortunately I do not have it anymore.
However, I believe this will happen with any memory sample that contains files which are using
"special" kind of characters.
In this case, the file name contained Hebrew characters so I guess if you create any memory sample
that saved a file name using the Hebrew language - that will do the trick.

**Comment by ikelos** [comment]
We've recently run into a similar issue with out testing system.  It seems only to affect windows, and it can happen if the console that python's being run in isn't set to print unicode characters.  You might find that this post resolves your problems, but essentially it's likely due to the console you're working with not being able to print the unicode characters that volatility finds (they may be bad characters, but they should at least be displayed rather than throwing an exception).

https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window

**Comment by ikelos** [comment]
I'm going to mark this as closed, since volatility does output unicode characters correctly, and this sounds like it's the console that's unable to handle the unicode output correctly.  Feel free to reopen this if you think there's still an issue here...
