### ISSUE TITLE
Pdbconv module error: unhandled leaf_type

### ISSUE THREAD

**Issue by cryptouser201** [volatilityfoundation/volatility3#516]
**Describe the bug**
Pdbconv module gives error during dump parsing

**Context**
Volatility Version:  Volatility 3, develop branch with commit 505_2 (https://github.com/volatilityfoundation/volatility3/tree/issues/issue505-2)
It was used because of fresh Windows version (Windows insider preview)
Operating System:  Windows 10, version 21301

**Additional information**
F:\vol_test\develop_505_2>python.exe vol.py -vvvv -f "F:\temp\dump_volatility\WIN21H1-21301.dmp" windows.info
Volatility 3 Framework 1.0.1
INFO     volatility3.cli: Volatility plugins path: ['F:\\vol_test\\develop_505_2\\volatility3\\plugins', 'F:\\vol_test\\develop_505_2\\volatility3\\framework\\plugins']
INFO     volatility3.cli: Volatility symbols path: ['F:\\vol_test\\develop_505_2\\volatility3\\symbols', 'F:\\vol_test\\develop_505_2\\volatility3\\framework\\symbols']
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
DEBUG    volatility3.schemas: All validations will report success, even with malformed input
Level 8  volatility3.framework.automagic.stacker: Stacked WindowsCrashDump64Layer using WindowsCrashDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsIntelStacker
DEBUG    volatility3.framework.automagic.windows: DTB was found at: 0x1aa000
Level 8  volatility3.framework.automagic.stacker: Stacked IntelLayer using WindowsIntelStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary.memory_layer
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.primary.memory_layer.base_layer
INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
DEBUG    volatility3.schemas: All validations will report success, even with malformed input
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'WindowsCrashDump64Layer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: WintelHelper
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
INFO     volatility3.framework.symbols.windows.pdbconv: Download PDB file...
DEBUG    volatility3.framework.symbols.windows.pdbconv: Attempting to retrieve http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/D06948C5F5258EFB9CF74852D40682A51/ntkrnlmp.pdb
Progress:  100.00               Downloading http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/D06948C5F5258EFB9CF7INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
DEBUG    volatility3.schemas: All validations will report success, even with malformed input
DEBUG    volatility3.framework.symbols.windows.pdbconv: Reading DBI stream
DEBUG    volatility3.framework.symbols.windows.pdbconv: Reading PDB Info
DEBUG    volatility3.framework.symbols.windows.pdbconv: Reading TPI
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.nt_symbols
WARNING  volatility3.framework.plugins: Automagic exception occurred: TypeError: Unhandled leaf_type: 5641
Level 9  volatility3.framework.plugins: Traceback (most recent call last):
  File "F:\vol_test\develop_505_2\volatility3\framework\automagic\__init__.py", line 131, in run
    automagic(context, config_path, requirement, progress_callback)
  File "F:\vol_test\develop_505_2\volatility3\framework\automagic\pdbscan.py", line 329, in __call__
    self.recurse_symbol_fulfiller(context, valid_kernel, progress_callback)
  File "F:\vol_test\develop_505_2\volatility3\framework\automagic\pdbscan.py", line 103, in recurse_symbol_fulfiller
    PDBUtility.load_windows_symbol_table(
  File "F:\vol_test\develop_505_2\volatility3\framework\symbols\windows\pdbutil.py", line 81, in load_windows_symbol_table
    cls.download_pdb_isf(context, guid.upper(), age, pdb_name, progress_callback)
  File "F:\vol_test\develop_505_2\volatility3\framework\symbols\windows\pdbutil.py", line 208, in download_pdb_isf
    json_output = pdbconv.PdbReader(context, location, pdb_name, progress_callback).get_json()
  File "F:\vol_test\develop_505_2\volatility3\framework\symbols\windows\pdbconv.py", line 567, in get_json
    self.read_necessary_streams()
  File "F:\vol_test\develop_505_2\volatility3\framework\symbols\windows\pdbconv.py", line 335, in read_necessary_streams
    self.read_tpi_stream()
  File "F:\vol_test\develop_505_2\volatility3\framework\symbols\windows\pdbconv.py", line 343, in read_tpi_stream
    type_references = self._read_info_stream(2, "TPI", self.types)
  File "F:\vol_test\develop_505_2\volatility3\framework\symbols\windows\pdbconv.py", line 396, in _read_info_stream
    output, consumed = self.consume_type(module, offset, length)
  File "F:\vol_test\develop_505_2\volatility3\framework\symbols\windows\pdbconv.py", line 827, in consume_type
    raise TypeError("Unhandled leaf_type: {}".format(leaf_type))
TypeError: Unhandled leaf_type: 5641

Unsatisfied requirement plugins.Info.nt_symbols: Windows kernel symbols

A symbol table requirement was not fulfilled.  Please verify that:
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.nt_symbols']

**Comment by ikelos** [comment]
Thanks we've never encountered that particular type across all the kernels we've had to deal with, but now that we've got a specific kernel that we know fails, we should be able to get that fixed.  It may take a little while though I'm afraid...

**Comment by cryptouser201** [comment]
I can share dump, if you need and if it simplify the analyzing process . Dump was made from working PC: i can send link to DM, if it perhaps

**Comment by ikelos** [comment]
This is because we don't yet handle all C++ types yet.  It will take some time to get this resolved.

**Comment by ikelos** [comment]
Ok, so this isn't actually C++ types, it seems that new types were added to the PDB format last year.  There's now a branch that adds support for the new types.  Please could you test this and let us know whether it allows you to process the image now?

**Comment by cryptouser201** [comment]
Yes, this branch works with Windows 10, version 21301 dump. Thanks.

**Comment by jgru** [comment]
Dear @ikelos,

unfortunately the code in your PR #540 (branch `feature/pdbconv-vs19`) does not work with `win32k.pdb`  of a Windows 1809-system (GUID-age: `c0685fe74deea4bec6f9cc52feac5d231`).

Running `pdbconv.py` I get the following stacktrace:

    python3 volatility3/framework/symbols/windows/pdbconv.py --guid c0685fe74deea4bec6f9cc52feac5d231 -f ~/win32k.pdb -o windows10-64-win32k.json
    
    Traceback (most recent call last):ading TPI layer
      File "volatility3/framework/symbols/windows/pdbconv.py", line 1011, in <module>
        converted_json = convertor.get_json()
      File "volatility3/framework/symbols/windows/pdbconv.py", line 567, in get_json
        self.read_necessary_streams()
      File "volatility3/framework/symbols/windows/pdbconv.py", line 336, in read_necessary_streams
        self.read_tpi_stream()
      File "volatility3/framework/symbols/windows/pdbconv.py", line 344, in read_tpi_stream
        type_references = self._read_info_stream(2, "TPI", self.types)
      File "volatility3/framework/symbols/windows/pdbconv.py", line 396, in _read_info_stream
        output, consumed = self.consume_type(module, offset, length)
      File "volatility3/framework/symbols/windows/pdbconv.py", line 780, in consume_type
        subfield, sub_consumed = self.consume_type(module, sub_offset, sub_length)
      File "volatility3/framework/symbols/windows/pdbconv.py", line 773, in consume_type
        type_handler, has_name, value_attribute = self.type_handlers.get(leaf_type.lookup(), 'LF_UNKNOWN')
    ValueError: too many values to unpack (expected 3)

This issue seems to be linked with #182.
If you need further information on this, please let me know.

BTW: Thanks for providing such great tooling!

**Comment by ikelos** [comment]
@jgru  That's a different issue.  win32k is a C++ module and as such has structures that pdbconv doesn't handle yet.  This one is just about the recent windows 10 kernels (specifically, kernels compiled with the latest visual studio), the issue you're discussing is about C++ types, and you're right is #182.  There is a branch you can try to see if it helps (`features/pdbconv-cplusplus`), but please put any findings on the other bug, rather than this one...

**Comment by jgru** [comment]
Hi @ikelos, thanks for getting back to me and explaining the issue!   
I will try `pdbconv` from the mentioned branch (`features/pdbconv-cplusplus`) and report the result in #182. 
Sorry for mixing those issues!
