### ISSUE TITLE
Page error 0xfffffffffff8 in layer primary (Page Fault at entry 0x8dce063 in table page table)

### ISSUE THREAD

**Issue by SakenOmarov** [volatilityfoundation/volatility3#525]
**Describe the bug**
when trying to run the "python vol.py -vvv -f memdump.mem windows.pstree.PsTree", the following error appears (screenshot). 
Presumably the problem is only with windows.pstree.PsTree. Other plugins such as PsScan, PsList work normally.
**Context**
Volatility Version:  Volatility 3 Framework 1.0.1
Operating System:  Windows 10
Python Version:  Python 3.9.6
Suspected Operating System:  Windows 10
Command:  python vol.py -vvv -f memdump.mem windows.pstree.PsTree

**To Reproduce**

1. Use command 'python vol.py -vvv -f memdump.mem windows.pstree.PsTree'
2. See error - "volatility3.framework.exceptions.PagedInvalidAddressException: Page Fault at entry 0x8dce063 in table page table

Volatility was unable to read a requested page:
Page error 0xfffffffffff8 in layer primary (Page Fault at entry 0x8dce063 in table page table)"

**Expected behavior**
successful output of the command

**Screenshots**
![at the beginning](https://user-images.githubusercontent.com/87036368/124651131-6256b680-debc-11eb-8fe5-08d06d7f7755.png)
![in the end](https://user-images.githubusercontent.com/87036368/124651141-6551a700-debc-11eb-8619-5e94960b9e70.png)
![in the middle](https://user-images.githubusercontent.com/87036368/124651157-684c9780-debc-11eb-842d-dced229a96e8.png)

**Additional information**
[description with -vvv.txt](https://github.com/volatilityfoundation/volatility3/files/6772135/description.with.-vvv.txt)

**Comment by SakenOmarov** [comment]
![1](https://user-images.githubusercontent.com/87036368/124660120-9683a480-dec7-11eb-817f-411cd72e124a.png)


the same error when calling another command

**Comment by SakenOmarov** [comment]
![2](https://user-images.githubusercontent.com/87036368/124660335-e5313e80-dec7-11eb-84a6-f51325b441db.png)

the dlllist command with the error "Stop error 0x19ae8604240 in layer primary_Process 1392_1 ()" I assume the problem is not in volatility but in the snapshot?

**Comment by SakenOmarov** [comment]
"Presumably the problem is only with windows.pstree.PsTree." - I'll take my words back, plugin 'getsids' is also with an error.

**Comment by ikelos** [comment]
Hiya, Yep, I'd imagine that the memory image has some chunks of memory swapped out.  It's quite unusual that pstree doesn't work when pslist does though?  They should do almost identical things except one sorts/output in tree format?  Would you be able to make the memory image available for us to investigate it further?  It seems from the exception traceback that it would be accessing the `proc.UniqueProcessId` value, but pslist should be checking that too...

**Comment by ikelos** [comment]
Haven't had a response on this one for a while, I'm going to mark it as closed, but please feel free to reopen it, particularly if you still experience this issue in version 2.0.0.
