### ISSUE TITLE
Plugin "getsids" broken on develop

### ISSUE THREAD

**Issue by fgomulka** [volatilityfoundation/volatility3#528]
**Describe the bug**
The windows plugin `getsids` is broken on the `develop` branch. 

**Context**
Volatility Version:  Volatility 3 Framework 1.0.1
Operating System:  WinXPSP2x86
Python Version:  3.9.5
Suspected Operating System:  WinXPSP2x86
Command:  python3 /Users/fgomulka/vfoundation/volatility3/vol.py --single-location file:////Users/fgomulka/Downloads/win/win2012r2-x64-6.3.9600.18505.lime -q windows.getsids.GetSIDs --pid 4

**To Reproduce**

1. Run the above command on the develop branch of volatility3
2. See error

**Expected behavior**

The plugin should work, but it seems that commit 0214fa35 broke it.

**Screenshots**

<img width="682" alt="Screen Shot 2021-07-12 at 10 15 49 AM" src="https://user-images.githubusercontent.com/60993471/125302654-25465600-e2fa-11eb-9aac-f015ec54ce3d.png">

**Additional information**
N/A

**Comment by superponible** [comment]
@fgomulka Can you see if 446510ab5fc952bcffb3d5adb7f020e3da231ec8 fixes that for you?

**Comment by fgomulka** [comment]
> @fgomulka Can you see if [446510a](https://github.com/volatilityfoundation/volatility3/commit/446510ab5fc952bcffb3d5adb7f020e3da231ec8) fixes that for you?

That fixed it!
