### ISSUE TITLE
No suitable kernels found during pdbscan

### ISSUE THREAD

**Issue by hawk4n6** [volatilityfoundation/volatility3#577]
I got an Windows 10 RAM dump created by CAPEv2 and want to analyse it. Unfortunately no symbol table is found nor downloaded.

For testing puposes I used an evoluation Windows 10 VM downloaded from Microsoft (Vmware vmdk) converted by qemu-img to qcow2. I did download the Symbols archive windows.zip and extracted to content to the correct directory before running vol.py.

Volatility Version:  2.0.0 (current)
Operating System:  Ubuntu 20.04 (current)
Python Version:  3.8.2
Suspected Operating System:  Windows 10 x64, Release 1809
Command:  python3 vol.py -vvvvvvv -f memory.dmp windows.info

**Expected behavior**
Find or download the matching symbol files.

**Additional information**
[windows-info.txt](https://github.com/volatilityfoundation/volatility3/files/7317265/windows-info.txt)

**Comment by ikelos** [comment]
Thanks very much for the report.  It looks as though volatility found the DTB so was able to read the image successfully, but I'd still prefer to eliminate the Elf64 layer form the equation.  Could you please use the `layerwriter` plugin or the volatility 2 `imagecopy` plugin to get the image into a raw format and check that the issue can be replicated?  In either situation this will probably require us to examine the image to find out why it couldn't find the appropriate pdb signature to be able to continue.  You said that you downloaded a public VM, so would you be willing to share the image with us please?

**Comment by hawk4n6** [comment]
Layerwriter successfully created a 5 GB memory_layer.raw file from an 3.1 GB memory dump. Again Volatility failed to find the matching symbols from the layer file; siehe attached text file.

I can't upload the memory dump here, so please get it from this [link](https://www.transfernow.net/dl/20211011kP392NUP).

[windows-info-memlayer.txt](https://github.com/volatilityfoundation/volatility3/files/7321704/windows-info-memlayer.txt)

**Comment by ikelos** [comment]
Thanks very much for the image, it turned out our regular expression was missing a flag meaning that in certain very specific situations we'd miss a pdb signature completely.  Thanks to your sample we now find it and your sample processes fine as of `daef7df`!  5:D

**Comment by hawk4n6** [comment]
Thanks a lot for your fast help! Solved.
