### ISSUE TITLE
windows.vadinfo.VadInfo `--maxsize` has no default value

### ISSUE THREAD

**Issue by pyllyukko** [volatilityfoundation/volatility3#578]
**Describe the bug**
When I try to run `windows.vadinfo.VadInfo` against a certain memory image, one of the allocations looks like the following:

```
  |  PID |        Process |         Offset |     Start VPN |       End VPN |  Tag |                       Protection |     CommitCharge | PrivateMemory |         Parent |                                                                                                                                                File | File output
* | 2516 |   iexplore.exe | 0xfa8003b0a810 |    0x7fff0000 | 0x7fffffeffff | Vadl |                    PAGE_READONLY | 2251799813685247 |             1 | 0xfa8004e0fdf0 |                                                                                                                                                 N/A |    Disabled
```
So that would account for 8793945538559 bytes which simply can't be true.

**Context**
Volatility Version:  2d39dc5a919f02722f41d83f9c289b6cc6cb07c3
Operating System:  Debian 11
Python Version:  3.9.2
Command:  `python3 vol.py -o results/vads/ -r pretty -f win7-64-Snapshot7.vmem windows.vadinfo.VadInfo --dump 1>./results/windows.vadinfo.VadInfo.txt`

**To Reproduce**
N/A. Might be related to this particular memory image.

**Expected behavior**
Volatility3 not filling my disk with hundreds of gigabytes of data.

**Screenshots**
```
-rw------- 1 xyz xyz  261G Oct 12 12:46 pid.2516.vad.0x7fff0000-0x7fffffeffff.dmp
```

**Comment by ikelos** [comment]
@iMHLv2 Should we set a default value for the `--maxsize` parameter?  I recall preferring not to, but then I didn't expect bad data to lead to 260+ Gb of data output.  5:S  If so what would you recommend as about twice the size of the biggest possible VAD we'd expect to see?
