### ISSUE TITLE
Document the fact that automagic is chosen based on the plugin's subdirectory

### ISSUE THREAD

**Issue by NiklasBeierl** [volatilityfoundation/volatility3#588]
**Describe the bug**
I have multiple snapshots with different kernel versions and sizes and was running a custom plugin on them. The plugin is just a slightly modified `linux.pslist`. See here: https://github.com/NiklasBeierl/nopgd/blob/main/volatility_plugins/linux/pslist_with_pgds.py

Only on one specific snapshot out of 28, i got this: 
```
vol -p ~/code/nopgd/volatility_plugins/ -s ../debugging-symbols/ -f ./snapshot pslist_with
Volatility 3 Framework 1.0.1
Progress:    6.64               Scanning memory_layer using MultiStringScanner
PID     PPID    COMM    virt_pgd        phy_pgd phy_pgd_kernel  phy_pgd_user


Volatility was unable to read a requested page:
Page error 0x82413c78 in layer primary (Page Fault at entry 0x800000003b600063 in table page directory pointer)

        * Memory smear during acquisition (try re-acquiring if possible)
        * An intentionally invalid page lookup (operating system protection)
        * A bug in the plugin/volatility3 (re-run with -vvv and file a bug)

No further results will be produced
``` 
But when i move my plugin into: `volatility_plugins/linux/`, it works!
```
vol -p ~/code/nopgd/volatility_plugins/ -s ../debugging-symbols/-f ./snapshot linux.pslist_with
Volatility 3 Framework 1.0.1
Progress:  100.00               Stacking attempts finished
PID     PPID    COMM    virt_pgd        phy_pgd phy_pgd_kernel  phy_pgd_user

1       0       systemd 172902459375616 1034682368      1034682368      1034686464
393     1       systemd-journal 172902337871872 913178624       913178624       913182720
404     1       lvmetad 172902459703296 1035010048      1035010048      1035014144
415     1       systemd-udevd   172902447865856 1023172608      1023172608      1023176704
570     1       systemd-timesyn 172902422577152 997883904       997883904       997888000
722     1       systemd-network 172902444056576 1019363328      1019363328      1019367424
762     1       systemd-resolve 172902444875776 1020182528      1020182528      1020186624
887     1       accounts-daemon 172902419079168 994385920       994385920       994390016
890     1       lxcfs   172902420496384 995803136       995803136       995807232
899     1       cron    172902411042816 986349568       986349568       986353664
902     1       atd     172902411051008 986357760       986357760       986361856
912     1       dbus-daemon     172902411829248 987136000       987136000       987140096
973     1       networkd-dispat 172902398304256 973611008       973611008       973615104
981     1       systemd-logind  172902394011648 969318400       969318400       969322496
982     1       rsyslogd        172902399459328 974766080       974766080       974770176
1040    1       unattended-upgr 172902444113920 1019420672      1019420672      1019424768
1045    1       polkitd 172902333972480 909279232       909279232       909283328
1055    1       agetty  172902395150336 970457088       970457088       970461184
1065    1       agetty  172902445514752 1020821504      1020821504      1020825600
1334    1       sshd    172902423805952 999112704       999112704       999116800

``` 
It seems so weird because it worked without moving the plugin into a linux module on 27 other snapshots!
Is this intended behavior? Did I miss it in the documentation somewhere? 
I got the idea to move my plugin to linux folder because `linux.pslist` worked just fine.

**Context**
Volatility Version:  Volatility 3 Framework 1.0.1
Operating System:  Linux
Python Version:  Python 3.9.2
Suspected Operating System:  Linux
Command:  vol -f /one/specific/snapshots -p my/plugin/dir -s my/symbols (linux.)pslist_with

**To Reproduce**
See command and description.
I think I could make a transfer of the desired snapshot happen if desired.

**Expected behavior**
Plugin should work even if outside a "linux" module.

**Comment by ikelos** [comment]
So when a plugin is under the `linux` namespace, the number of automagic options that are run are reduced to just linux relevant ones.  Without that, you'll get automagic for mac and windows running against the image as well.  In most cases, those won't be able to find suitable matches, but in certain circumstances one of them will succeed in locating bogus information and then volatility won't really know what to do.  You can see the difference in runs by putting it in the `linux` directory and running it with `-vvvvv` and then moving it out of the linux directory and doing the same.

We strongly recommend that if a particular plugin is for a particular operating system, you put it under the operating system's namespace.  This will also speed up runs of volatility because it won't have to try hunting for data that you know won't be relevant...  5:)

I'm not sure what to do with this, there isn't really a bug specifically, so I'm going to mark this as closed, but if you think it should be left open as a question, let me know and we can change the labels and title to help and reopen it...

**Comment by NiklasBeierl** [comment]
I see, I kind of suspected something like that. I wasn't aware that vols `-v` worked up to `-vvvvv`. :innocent:
Do you point me to the the relevant place in the of code so that I can fully understand this mechanism and update the doc? 
I think the "How to Write a Simple Plugin" guide might be a good place to start?

**Comment by ikelos** [comment]
Hiya, I think `-v` actually goes up to `-vvvvvvv`, but I'm not sure anything that far is all that useful...  5;P

The code that does the choosing is at https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/automagic/__init__.py#L52
At the moment, the automagic chooser information is buried under the library section https://volatility3.readthedocs.io/en/stable/using-as-a-library.html#using-automagic-to-complete-the-configuration, but you're right, we should mention it under the writing a simple plugin bit.
We should probably also update: https://volatility3.readthedocs.io/en/stable/vol2to3.html#automagic to mention it.
