### ISSUE TITLE
Python-3.10 - AttributeError: module 'collections' has no attribute 'Sequence'

### ISSUE THREAD

**Issue by JamesFirth2020** [volatilityfoundation/volatility3#589]
Hello,
I'm trying to run a yarascan using a keyword phrase on volatility 3 and whatever I pick it starts writing a file and immediately fails:
C:\volatility3-develop>py vol.py -f E:\memdump.mem yarascan.YaraScan --yara-rules https://
Volatility 3 Framework 1.0.1
Progress:  100.00               PDB scanning finished
Offset  Rule    Component       Value
Traceback (most recent call last):
  File "C:\volatility3-develop\vol.py", line 10, in <module>
    volatility3.cli.main()
  File "C:\volatility3-develop\volatility3\cli\__init__.py", line 618, in main
    CommandLine().run()
  File "C:\volatility3-develop\volatility3\cli\__init__.py", line 326, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\volatility3-develop\volatility3\cli\text_renderer.py", line 178, in render
    grid.populate(visitor, outfd)
  File "C:\volatility3-develop\volatility3\framework\renderers\__init__.py", line 214, in populate
    treenode = self._append(parent, item)
  File "C:\volatility3-develop\volatility3\framework\renderers\__init__.py", line 275, in _append
    return self._insert(parent, len(children), values)
  File "C:\volatility3-develop\volatility3\framework\renderers\__init__.py", line 284, in _insert
    tree_item = TreeNode(newpath, self, parent, values)
  File "C:\volatility3-develop\volatility3\framework\renderers\__init__.py", line 58, in __init__
    self._validate_values(values)
  File "C:\volatility3-develop\volatility3\framework\renderers\__init__.py", line 73, in _validate_values
    if not (isinstance(values, collections.Sequence) and len(values) == len(self._treegrid.columns)):
AttributeError: module 'collections' has no attribute 'Sequence'

vol.3 -vv shows no errors, all should be running as expected. Fresh python310 install yesterday.

**Comment by JamesFirth2020** [comment]
Also same problem and error for windows.registry.userassist.UserAssist

**Comment by JamesFirth2020** [comment]
Aha, this is a python 3.10 issue it seems.

**Comment by ikelos** [comment]
Hmm, thanks for pointing this out.  It looks like it is an issue (under python-3.10 at least), so I'm gonna leave this open until we get it fixed...  5:)

**Comment by JamesFirth2020** [comment]
Excellent - at least that means the time spent I struggling was not a total waste! When it works it works, but when it doesn't...

**Comment by jkvaidya** [comment]
Do we have a solution to this yet? I am porting my codes from python 3.9.11 to python 3.10.5 and all my codes have the error of collections.abc as AttributeError (like below)
AttributeError: module 'collections' has no attribute 'Sequence'
There are many of them, and I have not got a way to solve all of them yet. Please let me know if there is a solution to it. Thanks

**Comment by digitalisx** [comment]
Hello @jkvaidya,

To check if the error still exists, I changed it to the python version (`3.10.5`) you told us and performed the test.

```shell
> python -V
Python 3.10.5

> python3 vol.py -f case.vmem yarascan.YaraScan --yara-rules="https://"
Volatility 3 Framework 2.3.0
Progress:  100.00		PDB scanning finished
Offset	Rule	Component	Value

0x8000dd662b81	r1	$a	68 74 74 70 73 3a 2f 2f
0x97065b6685ad	r1	$a	68 74 74 70 73 3a 2f 2f
0x97065b668820	r1	$a	68 74 74 70 73 3a 2f 2f
0x97065b668847	r1	$a	68 74 74 70 73 3a 2f 2f
```

As a result, it seems to work well. If it does not work as desired, it is possible that you are using an unpatched version associated with this issue. Volatility3 recommends that you use a minimum version of `2.0.1` or higher, and patches for that issue appear to be in effect from `2.0.0` or higher.

Could you please download the latest release version (`2.0.1`) of the framework and leave a comment with the log if you have any additional issues?
