### ISSUE TITLE
Windows Registry Print Key plugin not fully functional

### ISSUE THREAD

**Issue by MATTANDERS0N** [volatilityfoundation/volatility3#595]
**Describe the bug**
The Print Key plugin does not pull back the registry value data back like it does with volatility 2.  It was only able to find and display the name of the registry key. 

**Context**
Volatility Version:  3
Operating System:  Linux remnux 5.4.0-89-generic #100-Ubuntu 
Python Version:  3.8.10
Suspected Operating System: Win7SP1x86_23418
Command:  vol3 -f mem.raw windows.registry.printkey  --key "Software\Microsoft\Windows\CurrentVersion\Run"  

**To Reproduce**
Get a memory dump of a Windows system with a User Run Key and run the command to examine the key. 
It shows the registry key but not the value data inside the key. 

**Expected behavior**
It should pull back the value data inside the key.  This works as expected in version 2 using the profile stated above. 

**Screenshots**

**Additional information**
Add any other information about the problem here.

**Comment by ikelos** [comment]
Thanks for the report, could you please attach example output from both volatility 2 and volatility 3 indicating the issue, so we have something to compare?

**Comment by superponible** [comment]
@MATTANDERS0N Just wanted to update this issue and see if you are able to post some output from volatility 2 and volatility 3 to compare and show where vol2 can find data that vol3 doesn't.  Might also be helpful to include verbose output (-vvvvvv) for vol3.

Also, do other vol3 plugins work on the sample (windows.pslist, windows.modules, etc)?

**Comment by MATTANDERS0N** [comment]
I don't know if I still have the same sample to test with. I only found an issue with the one plug-in. Others seemed to work okay. I will see if I can find anything to show.

Jan 6, 2022 11:58:20 AM superponible ***@***.***>:

**Comment by ikelos** [comment]
This issue has been open over 6 months without further information provided, as such the issue has been closed.  If you believe it's still a problem, please feel free to reopen the issue.
