### ISSUE TITLE
Cache issues

### ISSUE THREAD

**Issue by gcmoreira** [volatilityfoundation/volatility3#599]
**Cache issues**

vol3 `--clear-cache` doesn't seem to work as expected. The way it's implemented only allows to remove the `data_*.cache` but the actual symbols cache. The framework function [clear_cache](https://github.com/volatilityfoundation/volatility3/blob/3c11099e6621027777ac5a9eeb3f8fbdc5b39b4b/volatility3/framework/__init__.py#L185) has a `complete` argument with a default argument to _False_ which is never used or changed when this function is called. Also, it's inconsistent with the **volshell** `--clear-cache` implementation [here](https://github.com/volatilityfoundation/volatility3/blob/3c11099e6621027777ac5a9eeb3f8fbdc5b39b4b/volatility3/cli/volshell/__init__.py#L141) which does remove everything. The latter may also need to call the same function instead of re-implementing it.

**Comment by ikelos** [comment]
Hiya, I've pushed another PR which doesn't clear out the entire cache, but instead points out when multiple files may work for a particular banner, and if so which one will be used.  This should allow a user to find and clear out any bad ones, which the linux cache automagic should then resolve.

Please test #609 out and let me know if it helps you get past the issue you were encountering.
