### ISSUE TITLE
memmap performance

### ISSUE THREAD

**Issue by kevthehermit** [volatilityfoundation/volatility3#604]
### Issue

When comparing the performance of `memdump` in volatility 2 and `memmap` in volatility 3 I have noticed a significant performance impact.

First discussed on Slack - https://volatilitycommunity.slack.com/archives/CNV2K4V9Q/p1639950485064800 , opening a GIt issue with more details. 

### Expected Behaviour

`memdump` and `memmap --dump` processing times should be comparable. 

### Actual Behaviour
Running the command with Vol2 takes ~8 seconds to dump and Vol3 takes almost 3 minutes. 

### Host Details

Host OS: Ubuntu 20.04
Image: AWS Server 2016 `Win2016x64_14393`
Collection: `winpmem_mini_x64_rc2.exe`

### Volatility 2.6

```
time vol.py -f image1.raw --profile Win2016x64_14393 memdump -p 4604 -D . 
Volatility Foundation Volatility Framework 2.6
************************************************************************
Writing rundll32.exe [  4604] to 4604.dmp

real	0m8.385s
user	0m7.564s
sys	0m0.807s
```

### Volatility 3 (develop Branch)

```
vol -f image1.raw --output-dir=procdump/ windows.memmap --pid 4604 --dump  
... Lots of print to screen all the offsets. 

174.19s user 3.10s system 99% cpu 2:57.57 total
```

###  write-config

Using `--write-config` and then running again with the resulting config file has no significant change in the time 

```
vol -c config.json -f image1.raw --output-dir=procdump/ windows.memmap --pid 4604
161.77s user 2.52s system 99% cpu 2:44.76
```

### Other Plugins

Other plugins run in a "normal" amount of time

- `vol -f image1.raw --output-dir=procdump/ windows.pslist  1.40s user 0.44s syst
em 99% cpu 1.841 total`

### Profile

Performance profile captured with the following command 

```
python3 -m cProfile -o out.prof vol.py -f image1.raw --output-dir=procdump/ windows.memmap --pid 4604 --dump
```
[profile.zip](https://github.com/volatilityfoundation/volatility3/files/7741823/profile.zip)

**Comment by ikelos** [comment]
Thanks very much, it looks like it's spending a lot of time in the rendering step.  Could you please get the latest commit of the repo (`fc12956`) and try `vol.py -r none ...`?  That should turn off all output and ideally cut 129s off the run.  It's still not ideal, but it should tell us if that's one of the pain points or not...

**Comment by kevthehermit** [comment]
Here you go

```
Updating 3c11099e..fc129567
Fast-forward
 volatility3/cli/text_renderer.py | 11 +++++++++++
 1 file changed, 11 insertions(+)
```

Results in no output as expected 

```
time python3 vol.py -r none -f image1.raw --output-dir=procdump/ windows.memmap --pid 4604 --dump
Volatility 3 Framework 2.0.0
python3 vol.py -r none -f image1.raw --output-dir=procdump/ windows.memmap     140.97s user 1.99s system 99% cpu 2:23.25 total

```

**Comment by ikelos** [comment]
Hmmm, it didn't cut off as much time as I'd hoped.  5:S  Any chance you could send through a `-m cProfile -o out2.prof` with the `-r none` param please?

**Comment by kevthehermit** [comment]
Created with
 
`python3 -m cProfile -o memmap-none.prof vol.py -r none -f image1.raw --output-dir=procdump/ windows.memmap --pid 4604 --dump `

[memmap-none.zip](https://github.com/volatilityfoundation/volatility3/files/7741867/memmap-none.zip)

**Comment by ikelos** [comment]
Well, that was embarrassing.  The default implementation of the renderer was *really* inefficient at the most common case (no tree and simply appending a line to the end of the results).  It would generate the list of children and then count it, twice, for every append!  After applying the pull requests a full run of memmap on an image went from using 1230.0s in the `_append` call to 0.2s.  5:S

I'm likely to commit this after a very short review, push it into the release branch, and then quietly try to forget that I ever let anything that inefficient into the codebase, let alone being the one that wrote it in the first place!  5:S  Thanks for brining it to our attention!  5:D
