### ISSUE TITLE
hashdump Hbootkey is not valid

### ISSUE THREAD

**Issue by mabangde** [volatilityfoundation/volatility3#617]
**Describe the bug**

**Context**
Volatility Version:  Volatility 3 Framework 2.0.0
Operating System:  
Python Version:  Python 3.8.5
Suspected Operating System:  Ubuntu 18.04.5 LTS (wls 1)
Command:  `./vol.py -f /tmp/memory.dmp windows.hashdump.Hashdump`

**Screenshots**
![image](https://user-images.githubusercontent.com/6219246/148936234-c067d930-6c83-46f2-b0dc-92075626cf20.png)
![image](https://user-images.githubusercontent.com/6219246/148936640-c9100876-2cb5-4451-b459-73157bac0650.png)

![lQLPDhsLBtQy_1vNBrPNDmSw3KsqMVr3RXUB4r1CYwC8AA_3684_1715](https://user-images.githubusercontent.com/6219246/148936148-089a0fd8-4383-4e79-88cb-0f0fec698a84.png)

![image](https://user-images.githubusercontent.com/6219246/148936760-b79d1db7-af50-4800-9442-3a49e533b06b.png)
![image](https://user-images.githubusercontent.com/6219246/148936829-fd135ad2-7767-49ef-860b-d605fe543067.png)
![image](https://user-images.githubusercontent.com/6219246/148936852-aa81c255-393a-45d2-8c6a-356477406165.png)
![image](https://user-images.githubusercontent.com/6219246/148937366-74e2693d-4a1b-4624-a1b2-d1a67a521d41.png)

**Comment by ikelos** [comment]
Thanks for the report, could you please include a short description about the issue?  It's difficult to figure out what's going wrong based only on the screenshots.

As far as I can tell, you'd get the error Hbootkey is not valid, when `SAM\\Domains\\Account\\F` doesn't contain a starting byte of 2 or 3.  The volatility 2 options you show don't demonstrate that it can get the information either, so it's unclear why they're included?  If you'd be willing to provide the image file for analysis we might be able to figure out why you're not getting data from hashdump, but as it stands it's very difficult to interpret what you'd like to see change?
