### ISSUE TITLE
Volatility can't process UNC path

### ISSUE THREAD

**Issue by sin4ts** [volatilityfoundation/volatility3#627]
**Describe the bug**
Volatility3 can't process files which are located on network share and thus provided using UNC path.
All the more, if cached symbols are also located on a network share (for example because volatility itself is stored on a network share), they can't be loaded which cause volatility to crash.
I assume of course one has the correct permission to access the given network share. Thank's to Windows SSO, credentials are not required to be explicitly provided - i.e. one can access the network share using the corresponding UNC path, as if it was a local drive.

**Context**
Volatility Version:  1.0.0 and later
Operating System:  Windows
Python Version:  3.7
Suspected Operating System:  
Command: 
vol.py -f \\\\SHARE\memdump.mem
Or:
vol.y --single-location file://SHARE/memedump.mem
Or:
\\\\SHARE\vol.py -f C:\memdump.mem

**To Reproduce**
- Run vol.py locally with a memory image stored on a network share and provided with a UNC path
Or:
- Run vol.py from a network share with a memory image stored on the local disk

**Expected behavior**
vol.py crashes with the below stacktrace.

WARNING  volatility3.framework.plugins: Automagic exception occurred: urllib.error.URLError: <urlopen error [WinError 3] Le chemin d’accès spécifié est introuvable: '\\share\\dev\\volatility3\\volatility3\\framework\\symbols\\windows\\pdb.json'>
Level 9  volatility3.framework.plugins: Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1505, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: '\\share\\dev\\volatility3\\volatility3\\framework\\symbols\\windows\\pdb.json'

**Additional information**
The issue seems to be caused by urllib being unable to process UNC path in volatility3\framework\layers\resources.py (even  if pysmb is installed).
The bug can be mitigated by processing URL starting with file:// with the native "open" function instead of urllib.request.urlopen (with a bit of formatting to convert the URL into a valid UNC path or local file path).

**Full Stacktrace**
Volatility 3 Framework 2.0.0
INFO     volatility3.cli: Volatility plugins path: ['Z:\\dev\\volatility3\\volatility3\\plugins', 'Z:\\dev\\volatility3\\volatility3\\framework\\plugins']
INFO     volatility3.cli: Volatility symbols path: ['Z:\\dev\\volatility3\\volatility3\\symbols', 'Z:\\dev\\volatility3\\volatility3\\framework\\symbols']
DEBUG    volatility3.framework: No module named 'Crypto'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.hashdump based on file: Z:\dev\volatility3\volatility3\framework\plugins\windows\hashdump.py
DEBUG    volatility3.framework: No module named 'Crypto'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.cachedump based on file: Z:\dev\volatility3\volatility3\framework\plugins\windows\cachedump.py
DEBUG    volatility3.framework: No module named 'Crypto'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.lsadump based on file: Z:\dev\volatility3\volatility3\framework\plugins\windows\lsadump.py
INFO     volatility3.cli: The following plugins could not be loaded (use -vv to see why): volatility3.plugins.windows.cachedump, volatility3.plugins.windows.hashdump, volatility3.plugins.windows.lsadump
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList
INFO     volatility3.framework.automagic: Running automagic: SymbolBannerCache
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using AVMLStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsIntelStacker
DEBUG    volatility3.framework.automagic.windows: Detecting Self-referential pointer for recent windows
DEBUG    volatility3.framework.automagic.windows: DtbSelfRef64bit test succeeded at 0x1aa000
DEBUG    volatility3.framework.automagic.windows: DTB was found at: 0x1aa000
Level 8  volatility3.framework.automagic.stacker: Stacked IntelLayer using WindowsIntelStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using AVMLStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name.memory_layer
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf80549e00000
INFO     volatility3.framework.symbols.windows.pdbconv: Download PDB file...
DEBUG    volatility3.framework.symbols.windows.pdbconv: Attempting to retrieve http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/733830ECAFA1A3073FFA9CC3A38FE93C1/ntkrnlmp.pdb
INFO     volatility3.framework.automagic: Running automagic: SymbolFindernload/symbols/ntkrnlmp.pdb/733830ECAFA1A3073FFA9CC3A38FE93C1/ntkrnlmp.pdb
INFO     volatility3.framework.automagic: Running automagic: KernelModule
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
WARNING  volatility3.framework.plugins: Automagic exception occurred: urllib.error.URLError: <urlopen error [WinError 3] Le chemin d’accès spécifié est introuvable: '\\share\\dev\\volatility3\\volatility3\\framework\\symbols\\windows\\pdb.json'>
Level 9  volatility3.framework.plugins: Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1505, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: '\\share\\dev\\volatility3\\volatility3\\framework\\symbols\\windows\\pdb.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\dev\volatility3\volatility3\framework\automagic\__init__.py", line 124, in run
    automagic(context, config_path, requirement, progress_callback)
  File "Z:\dev\volatility3\volatility3\framework\automagic\pdbscan.py", line 336, in __call__
    self.recurse_symbol_fulfiller(context, valid_kernel, progress_callback)
  File "Z:\dev\volatility3\volatility3\framework\automagic\pdbscan.py", line 104, in recurse_symbol_fulfiller
    PDBUtility.load_windows_symbol_table(
  File "Z:\dev\volatility3\volatility3\framework\symbols\windows\pdbutil.py", line 82, in load_windows_symbol_table
    cls.download_pdb_isf(context, guid.upper(), age, pdb_name, progress_callback)
  File "Z:\dev\volatility3\volatility3\framework\symbols\windows\pdbutil.py", line 209, in download_pdb_isf
    json_output = pdbconv.PdbReader(context, location, pdb_name, progress_callback).get_json()
  File "Z:\dev\volatility3\volatility3\framework\symbols\windows\pdbconv.py", line 267, in __init__
    self._layer_name, self._context = self.load_pdb_layer(context, location)
  File "Z:\dev\volatility3\volatility3\framework\symbols\windows\pdbconv.py", line 315, in load_pdb_layer
    msf_layer = msf.PdbMultiStreamFormat(new_context, msf_config_path, msf_layer_name)
  File "Z:\dev\volatility3\volatility3\framework\layers\msf.py", line 32, in __init__
    self._pdb_symbol_table = intermed.IntermediateSymbolTable.create(context, self._config_path, 'windows', 'pdb')
  File "Z:\dev\volatility3\volatility3\framework\symbols\intermed.py", line 241, in create
    table = cls(context = context,
  File "Z:\dev\volatility3\volatility3\framework\symbols\intermed.py", line 105, in __init__
    fp = resources.ResourceAccessor().open(isf_url)
  File "Z:\dev\volatility3\volatility3\framework\layers\resources.py", line 118, in open
    raise excp
  File "Z:\dev\volatility3\volatility3\framework\layers\resources.py", line 104, in open
    fp = urllib.request.urlopen(url, context = self._context)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1483, in file_open
    return self.open_local_file(req)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1522, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 3] Le chemin d’accès spécifié est introuvable: '\\share\\dev\\volatility3\\volatility3\\framework\\symbols\\windows\\pdb.json'>

Unsatisfied requirement plugins.PsList.kernel: Windows kernel
Unable to validate the plugin requirements: ['plugins.PsList.kernel']
Exception ignored in: <function FileLayer.__del__ at 0x00000173E4349360>
Traceback (most recent call last):
  File "Z:\dev\volatility3\volatility3\framework\layers\physical.py", line 193, in __del__
  File "Z:\dev\volatility3\volatility3\framework\layers\physical.py", line 190, in destroy
  File "Z:\dev\volatility3\volatility3\framework\layers\physical.py", line 109, in _file
  File "Z:\dev\volatility3\volatility3\framework\layers\resources.py", line 101, in open
  File "C:\Program Files\Python310\lib\urllib\request.py", line 601, in build_opener
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1400, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by ikelos** [comment]
This is a feature of how windows UNCs are supported in python.  It appears to work with file:////host/path/to/host.  Please could you test this with `--single-location` and let us know.  If so, we can investigate supporting it in the `-f` parameter, but I'd like to check that the URL version works properly first...

**Comment by sin4ts** [comment]
Thank you for your answer. I have just tested with --single-location file:////host/path/to/host, indeed it works ! Thank you for pointing it to me.
However that only solve half of the issue: if the Volatility source code is located on a network share, then it does not work - even if the network share is mounted as a drive.
The problem seems to be related to the way Volatility deals with symbols: the path used to point to symbol's files (in order to write or read them) is not properly constructed which result in Volatility to crash. See below screenshots:

1. Using volatility on network share not mounted:
![Capture d’écran du 2022-01-19 09-42-34](https://user-images.githubusercontent.com/9694893/150096879-7b548144-0bf3-47b6-a6ac-4a1a5f831c76.png)

2. Using volatility on network share mounted as a drive:
![Capture d’écran du 2022-01-19 09-44-42](https://user-images.githubusercontent.com/9694893/150095204-00552e31-6685-4f4d-a09f-87e9303e6c2b.png)

As you can see, Volatilty try to store symbols to \\\\share\\dev\\volatility3\\volatility3\\framework\\symbols\\windows\\pdb.json whereas it shoulds store them to \\\\vboxsrv\share\dev\volatility3\volatility3\framework\symbols\windows\pdb.json or W:\dev volatility3\volatility3\framework\symbols\windows\pdb.json

Please note I have used a fake network share (virtualbox shared folder between host and guest) for this example, but I tested with a real network share as well, same behavior was observed.

Please let me know if you would like me to provide further information or update the issue's description above.

* Full Stack Trace*
C:\Users>python W:\dev\volatility3\vol.py -vvvv -f C:\memdump.mem windows.pslist
Volatility 3 Framework 2.0.0
INFO     volatility3.cli: Volatility plugins path: ['W:\\dev\\volatility3\\volatility3\\plugins', 'W:\\dev\\volatility3\\volatility3\\framework\\plugins']
INFO     volatility3.cli: Volatility symbols path: ['W:\\dev\\volatility3\\volatility3\\symbols', 'W:\\dev\\volatility3\\volatility3\\framework\\symbols']
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList
INFO     volatility3.framework.automagic: Running automagic: SymbolBannerCache
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using AVMLStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsIntelStacker
DEBUG    volatility3.framework.automagic.windows: Detecting Self-referential pointer for recent windows
DEBUG    volatility3.framework.automagic.windows: DtbSelfRef64bit test succeeded at 0x1aa000
DEBUG    volatility3.framework.automagic.windows: DTB was found at: 0x1aa000
Level 8  volatility3.framework.automagic.stacker: Stacked IntelLayer using WindowsIntelStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using AVMLStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name.memory_layer
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf80549e00000
INFO     volatility3.framework.symbols.windows.pdbconv: Download PDB file...
DEBUG    volatility3.framework.symbols.windows.pdbconv: Attempting to retrieve http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/733830ECAFA1A3073FFA9CC3A38FE93C1/ntkrnlmp.pdb
INFO     volatility3.framework.automagic: Running automagic: SymbolFindernload/symbols/ntkrnlmp.pdb/733830ECAFA1A3073FFA9CC3A38FE93C1/ntkrnlmp.pdb
INFO     volatility3.framework.automagic: Running automagic: KernelModule
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel
WARNING  volatility3.framework.plugins: Automagic exception occurred: urllib.error.URLError: <urlopen error [WinError 3] Le chemin d’accès spécifié est introuvable: '\\share\\dev\\volatility3\\volatility3\\framework\\symbols\\windows\\pdb.json'>
Level 9  volatility3.framework.plugins: Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1505, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: '\\share\\dev\\volatility3\\volatility3\\framework\\symbols\\windows\\pdb.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:\dev\volatility3\volatility3\framework\automagic\__init__.py", line 124, in run
    automagic(context, config_path, requirement, progress_callback)
  File "W:\dev\volatility3\volatility3\framework\automagic\pdbscan.py", line 336, in __call__
    self.recurse_symbol_fulfiller(context, valid_kernel, progress_callback)
  File "W:\dev\volatility3\volatility3\framework\automagic\pdbscan.py", line 104, in recurse_symbol_fulfiller
    PDBUtility.load_windows_symbol_table(
  File "W:\dev\volatility3\volatility3\framework\symbols\windows\pdbutil.py", line 82, in load_windows_symbol_table
    cls.download_pdb_isf(context, guid.upper(), age, pdb_name, progress_callback)
  File "W:\dev\volatility3\volatility3\framework\symbols\windows\pdbutil.py", line 209, in download_pdb_isf
    json_output = pdbconv.PdbReader(context, location, pdb_name, progress_callback).get_json()
  File "W:\dev\volatility3\volatility3\framework\symbols\windows\pdbconv.py", line 267, in __init__
    self._layer_name, self._context = self.load_pdb_layer(context, location)
  File "W:\dev\volatility3\volatility3\framework\symbols\windows\pdbconv.py", line 315, in load_pdb_layer
    msf_layer = msf.PdbMultiStreamFormat(new_context, msf_config_path, msf_layer_name)
  File "W:\dev\volatility3\volatility3\framework\layers\msf.py", line 32, in __init__
    self._pdb_symbol_table = intermed.IntermediateSymbolTable.create(context, self._config_path, 'windows', 'pdb')
  File "W:\dev\volatility3\volatility3\framework\symbols\intermed.py", line 241, in create
    table = cls(context = context,
  File "W:\dev\volatility3\volatility3\framework\symbols\intermed.py", line 105, in __init__
    fp = resources.ResourceAccessor().open(isf_url)
  File "W:\dev\volatility3\volatility3\framework\layers\resources.py", line 118, in open
    raise excp
  File "W:\dev\volatility3\volatility3\framework\layers\resources.py", line 104, in open
    fp = urllib.request.urlopen(url, context = self._context)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1483, in file_open
    return self.open_local_file(req)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1522, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 3] Le chemin d’accès spécifié est introuvable: '\\share\\dev\\volatility3\\volatility3\\framework\\symbols\\windows\\pdb.json'>


Unsatisfied requirement plugins.PsList.kernel: Windows kernel
Unable to validate the plugin requirements: ['plugins.PsList.kernel']

**Comment by ikelos** [comment]
Ok, I think I've narrowed down where it might be going wrong.  We do some messing with filenames at https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/symbols/windows/pdbutil.py#L204

It looks like we try to convert the windows filepath into a URL, but that goes wrong rather than using the filename directly.  It'll take me a little bit to set up an appropriate environment to test this.  In the meantime, if you generate the appropriate JSON file using `pdbconv.py` and put it in the symbols directory, it *should* sidestep this issue...

**Comment by ikelos** [comment]
This is now an official python bug at https://bugs.python.org/issue46654.  The issue is that the URL returned by Pathlib's `to_uri()` isn't accepted by urllib's `urlopen()` function.  I haven't worked up a local patch yet, we'll see if this can be resolved quickly upstream...

**Comment by sin4ts** [comment]
Thank you very much for your update and for escalating this to the Python project !
In case that can help you, I was actually able to temporary fix the issue with the attached patch. Basically I just open UNC paths using the default "open" function instead of Urllib. Definitely not rocket science, neither it's a very elegant fix, but so far it seems to work nicely for me :)
Thank's again for your work & help !
[0001-UNC-path-patch.zip](https://github.com/volatilityfoundation/volatility3/files/8016229/0001-UNC-path-patch.zip)

**Comment by ikelos** [comment]
Thanks for the patch (and to @paulkermann for #655 as well).  Please could you review the pull request I've put up.  It should work both if python fixes the bug and if they don't without affecting any other systems.  I've done my own testing and it resolves the issue, but I'd like confirmation from others and then I'll merge it...  5:)

**Comment by sin4ts** [comment]
Sorry for my late reply, I have been AFK for a while. I just successfully tested your patch and it looks like it's working nicely. Thank you again for your support !

**Comment by ikelos** [comment]
No problem, thanks for testing it, glad it works!  5:)
