### ISSUE TITLE
Windows 11 cannot write new ISF files to the symbols directory

### ISSUE THREAD

**Issue by mbunde** [volatilityfoundation/volatility3#629]
**Is your feature request related to a problem? Please describe.**
Hello I would like to request if there is suggestible profile that can be used by the Windows 11 memdumps

**Describe the solution you'd like**
Any profile that can be used with win11 will help in analyzing windows 11 memdumps

**Comment by ikelos** [comment]
Thanks, this isn't really a bug report, and doesn't really tell us enough to help with your issue?  Volatility 3 doesn't use profiles, that's part of volatility 2.  Windows ISF json files should be automatically generated by volatility from a PDB downloaded from Microsoft *if* volatility is able to determine the correct kernel.  As far as we're aware this functionality works for Windows 11 as well as it does for Windows 10, but if you're having difficulty with a Windows 11 image there could be a number of reasons, only one of which would be a lack of symbols.  Please provide the output from running volatility 3 against your windows 11 image including at least `-vvv` to help us diagnose why the image may not be being read correctly.

**Comment by mbunde** [comment]
Hello @ikelos  see attached. note i am using ubuntu installed on windows 10 via wsl.

<img width="961" alt="run_vol" src="https://user-images.githubusercontent.com/20443467/150693933-ec110940-6850-4006-9fb3-019fd883d96f.PNG">


See below sample run results 
vol -f memdump.mem -v windows.registry.hivelist.HiveList

Volatility 3 Framework 2.0.0
INFO     volatility3.cli: Volatility plugins path: ['/usr/local/lib/python3.8/dist-packages/volatility3-2.0.0-py3.8.egg/volatility3/plugins', '/usr/local/lib/python3.8/dist-packages/volatility3-2.0.0-py3.8.egg/volatility3/framework/plugins']
INFO     volatility3.cli: Volatility symbols path: ['/usr/local/lib/python3.8/dist-packages/volatility3-2.0.0-py3.8.egg/volatility3/symbols', '/usr/local/lib/python3.8/dist-packages/volatility3-2.0.0-py3.8.egg/volatility3/framework/symbols']
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
INFO     volatility3.framework.automagic: Running automagic: SymbolBannerCache
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
WARNING  volatility3.framework.symbols.windows.pdbutil: Cannot write necessary symbol file, please check permissions on /usr/local/lib/python3.8/dist-packages/volatility3-2.0.0-py3.8.egg/volatility3/symbols/windows/ntkrnlmp.pdb/F4ED78B31C1925908274B0A979AA418A-1.json.xz
WARNING  volatility3.framework.symbols.windows.pdbutil: Cannot write necessary symbol file, please check permissions on /usr/local/lib/python3.8/dist-packages/volatility3-2.0.0-py3.8.egg/volatility3/framework/symbols/windows/ntkrnlmp.pdb/F4ED78B31C1925908274B0A979AA418A-1.json.xz
WARNING  volatility3.framework.symbols.windows.pdbutil: Cannot write downloaded symbols, please add the appropriate symbols or add/modify a symbols directory that is writable
INFO     volatility3.framework.symbols.windows.pdbutil: The symbols can be downloaded later using pdbconv.py -p ntkrnlmp.pdb -g F4ED78B31C1925908274B0A979AA418A1
INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
INFO     volatility3.framework.automagic: Running automagic: KernelModule

Unsatisfied requirement plugins.HiveList.kernel: Windows kernel
Unable to validate the plugin requirements: ['plugins.HiveList.kernel']

**Comment by ikelos** [comment]
So actually, this is trying to create the symbols, but can't write to the location where symbols are written:

```
Cannot write necessary symbol file, please check permissions on /usr/local/lib/python3.8/dist-packages/volatility3-2.0.0-py3.8.egg/volatility3/framework/symbols/windows/ntkrnlmp.pdb/F4ED78B31C1925908274B0A979AA418A-1.json.xz
```
Either grant yourself permissions, install volatility3 local to your user (such as by using pip) or follow the [instructions for generating the ISF file](https://volatility3.readthedocs.io/en/stable/symbol-tables.html#windows-symbol-tables) and putting it in the exact location specified above...
