### ISSUE TITLE
Unable to validate the plugin requirements: ['plugins.PsList.kernel']

### ISSUE THREAD

**Issue by samuelzurowski** [volatilityfoundation/volatility3#632]
**Describe the bug**
Hello, I am attempting to try to analyze a memory dump that is running Ubuntu. I generated the symbol table using dwarf2json and I believe that the symbol tables are matching up. I was able to run volatility on a Windows image without an issue though. However, I get the error: 

Unsatisfied requirement plugins.PsList.kernel: Linux kernel
Unable to validate the plugin requirements: ['plugins.PsList.kernel']

**Context**
Volatility Version:  2.0.0
Operating System:  20.04.1-Ubuntu
Python Version:  Python 3.8.10
Suspected Operating System:  
Command:  vol.py -v -f Ubuntu20.04_LTSdesktop-Snapshot3.vmem linux.pslist.PsList

**Screenshots**
linux.pslist.PsList output
![image](https://user-images.githubusercontent.com/34222183/151081534-920188b1-ee56-46b7-9e2b-44309dc2b615.png)

isfinfo
![image](https://user-images.githubusercontent.com/34222183/151081628-afa130ef-7620-4aba-aad8-fa50d4e0ffd4.png)

banners
![image](https://user-images.githubusercontent.com/34222183/151081813-ae9ac075-5a2d-4533-ba91-36e12714284c.png)

If I am doing something wrong please let me know. Any help would be appreciated!

**Comment by ikelos** [comment]
Hi there, you're doing a lot of things right, but unfortunately the kernel you got the symbols from wasn't *exactly* the same as the one in the image, and so volatility couldn't use it (it might introduce subtle errors, which is a bad thing for a forensics tool to do). 

The image you're looking at begins `Linux  version 5.13.9-051309-generic` but the symbols you've made start `Linux version 5.13.9-27-generic`.  The rest of the banner also doesn't match, so you'll need to try and find the exact package that matches the kernel banner exactly.  You might try putting it into https://isf-server.techanarchy.net/ and seeing if someone else has already made the ISF file for that kernel?

**Comment by ikelos** [comment]
I'm going to close this, since I've somewhat answered the question, but feel free to reopen it or better join our [slack channel](https://www.volatilityfoundation.org/slack) to get more interactive support.  5:)
