### ISSUE TITLE
Get empty result from Mac OS's memory

### ISSUE THREAD

**Issue by PeterQi** [volatilityfoundation/volatility3#639]
**Describe the bug**
I dumped my mac's memory by osxpmem. Then I used volatility3 to analyze it. But I could only get empty result.

**Context**
Volatility Version:  Volatility 3 Framework 2.0.0
Operating System:  Mac OS X 10.15.7 19H15
Python Version:  Python 3.8.2
Suspected Operating System:  Mac OS X 10.15.7 19H15
Command:  python3 vol.py -f ../memory.dmp mac.bash.Bash

**To Reproduce**

1. Use command 'python3 vol.py -f ../memory.dmp mac.bash.Bash'
2. I get empty result with only title:

> Progress:  100.00		Stacking attempts finished
> PID	Process	CommandTime	Command

3. Use command 'python3 vol.py -f ../memory.dmp mac.ifconfig.Ifconfig'
4. I still get empty result with only title:

> Progress:  100.00		Stacking attempts finished
> Interface	IP Address	Mac Address	Promiscuous

**Expected behavior**
Some bash history commands and ifconfig message should appear.

**Screenshots**
<img width="564" alt="5ADAFCDE-A44B-4511-8F58-81E348A920E2" src="https://user-images.githubusercontent.com/4083094/152669198-cb434db9-55b4-4e9a-bfb8-5c92ee490673.png">

**Additional information**
I produced the json file by command `dwarf2json mac --macho /Library/Developer/KDKs/KDK_10.15.7_19H15.kdk/System/Library/Kernels/kernel.dSYM/Contents/Resources/DWARF/kernel --macho-symbols /Library/Developer/KDKs/KDK_10.15.7_19H15.kdk/System/Library/Kernels/kernel > kernel_debug_kit_10.15.7_19h15.dmg.json` and then put it into directory 'volatility3-develop/volatility3/symbols/mac'.
The result of isfinfo plugin showed that the json file could be loaded successfully.

> python3 vol.py -f ../memory.dmp isfinfo.IsfInfo
> Volatility 3 Framework 2.0.0
> Progress:  100.00		PDB scanning finished
> URI	Valid	Number of base_types	Number of types	Number of symbols	Number of enums	Windows info	Linux banner	Mac banner
> 
> file:///Users/bibilins/snowqizhang/volatility3-develop/volatility3/symbols/mac/kernel_debug_kit_10.15.7_19h15.dmg.json	Unknown	19	6228	54010	258	--	Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64

The result of banners plugin showed that the dumped memory matched the json file version:

> python3 vol.py -f ../memory.dmp banners.Banners
> Volatility 3 Framework 2.0.0
> Progress:  100.00		PDB scanning finished
> Offset	Banner
> 
> 0xe6f8c9d	Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2\~1/RELEASE_X86_64
> 0xe6f8d00	Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2\~1/RELEASE_X86_64
> 0xe885ac4	Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2\~1/RELEASE_X86_64
> 0x3473dae5	Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2\~1/RELEASE_X86_64
> 0x6286a300	Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2\~1/RELEASE_X86_64

If I ran vol.py with vvv, I got following result:

> python3 vol.py -vvv -f ../memory.dmp mac.bash.Bash
> Volatility 3 Framework 2.0.0
> INFO     volatility3.cli: Volatility plugins path: ['/Users/bibilins/snowqizhang/volatility3-develop/volatility3/plugins', '/Users/bibilins/snowqizhang/volatility3-develop/volatility3/framework/plugins']
> INFO     volatility3.cli: Volatility symbols path: ['/Users/bibilins/snowqizhang/volatility3-develop/volatility3/symbols', '/Users/bibilins/snowqizhang/volatility3-develop/volatility3/framework/symbols']
> INFO     volatility3.plugins.yarascan: Python Yara (>3.8.0) module not found, plugin (and dependent plugins) not available
> DEBUG    volatility3.framework: No module named 'yara'
> DEBUG    volatility3.framework: Failed to import module volatility3.plugins.yarascan based on file: /Users/bibilins/snowqizhang/volatility3-develop/volatility3/framework/plugins/yarascan.py
> INFO     volatility3.plugins.yarascan: Python Yara (>3.8.0) module not found, plugin (and dependent plugins) not available
> DEBUG    volatility3.framework: No module named 'yara'
> DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.svcscan based on file: /Users/bibilins/snowqizhang/volatility3-develop/volatility3/framework/plugins/windows/svcscan.py
> DEBUG    volatility3.framework: No module named 'Crypto'
> DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.hashdump based on file: /Users/bibilins/snowqizhang/volatility3-develop/volatility3/framework/plugins/windows/hashdump.py
> DEBUG    volatility3.framework: No module named 'Crypto'
> DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.cachedump based on file: /Users/bibilins/snowqizhang/volatility3-develop/volatility3/framework/plugins/windows/cachedump.py
> INFO     volatility3.plugins.yarascan: Python Yara (>3.8.0) module not found, plugin (and dependent plugins) not available
> DEBUG    volatility3.framework: No module named 'yara'
> DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.vadyarascan based on file: /Users/bibilins/snowqizhang/volatility3-develop/volatility3/framework/plugins/windows/vadyarascan.py
> INFO     volatility3.plugins.yarascan: Python Yara (>3.8.0) module not found, plugin (and dependent plugins) not available
> DEBUG    volatility3.framework: No module named 'yara'
> DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.mftscan based on file: /Users/bibilins/snowqizhang/volatility3-develop/volatility3/framework/plugins/windows/mftscan.py
> INFO     volatility3.plugins.yarascan: Python Yara (>3.8.0) module not found, plugin (and dependent plugins) not available
> DEBUG    volatility3.framework: No module named 'yara'
> DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.callbacks based on file: /Users/bibilins/snowqizhang/volatility3-develop/volatility3/framework/plugins/windows/callbacks.py
> DEBUG    volatility3.framework: No module named 'Crypto'
> DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.lsadump based on file: /Users/bibilins/snowqizhang/volatility3-develop/volatility3/framework/plugins/windows/lsadump.py
> INFO     volatility3.cli: The following plugins could not be loaded (use -vv to see why): volatility3.plugins.windows.cachedump, volatility3.plugins.windows.callbacks, volatility3.plugins.windows.hashdump, volatility3.plugins.windows.lsadump, volatility3.plugins.windows.mftscan, volatility3.plugins.windows.svcscan, volatility3.plugins.windows.vadyarascan, volatility3.plugins.yarascan
> INFO     volatility3.framework.automagic: Detected a mac category plugin
> INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Bash.kernel
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel.layer_name
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Bash.kernel.layer_name
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel.layer_name
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Bash.kernel
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Bash.kernel.symbol_table_name
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Bash.kernel.symbol_table_name
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Bash.kernel.symbol_table_name
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Bash.kernel
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Bash
> INFO     volatility3.framework.automagic: Running automagic: SymbolBannerCache
> INFO     volatility3.framework.automagic: Running automagic: MacBannerCache
> INFO     volatility3.framework.automagic: Running automagic: LayerStacker
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel
> DEBUG    volatility3.framework.automagic.mac: Identified banner: b'Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2\~1/RELEASE_X86_64\x00'
> INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
> DEBUG    volatility3.schemas: All validations will report success, even with malformed input
> DEBUG    volatility3.framework.automagic.mac: Identified banner: b'Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2\~1/RELEASE_X86_64\x00'
> INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
> DEBUG    volatility3.schemas: All validations will report success, even with malformed input
> DEBUG    volatility3.framework.automagic.mac: DTB was found at: 0x2252f000
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel.layer_name
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Bash.kernel
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel.layer_name
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel.layer_name.memory_layer
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Bash.kernel.symbol_table_name
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Bash.kernel.symbol_table_name
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Bash.kernel.symbol_table_name
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Bash.kernel
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel
> Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Bash
> DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
> INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
> INFO     volatility3.framework.automagic: Running automagic: MacSymbolFinder
> Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Bash.kernel.symbol_table_name
> DEBUG    volatility3.framework.automagic.symbol_finder: Identified banner: b'Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2\~1/RELEASE_X86_64\x00'
> DEBUG    volatility3.framework.automagic.symbol_finder: Using symbol library: file:///Users/bibilins/snowqizhang/volatility3-develop/volatility3/symbols/mac/kernel_debug_kit_10.15.7_19h15.dmg.json
> INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
> DEBUG    volatility3.schemas: All validations will report success, even with malformed input
> INFO     volatility3.framework.automagic: Running automagic: KernelModule
> Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel
> DEBUG    volatility3.plugins.mac.pslist: Using method tasks
> 
> PID	Process	CommandTime	Command
> INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
> DEBUG    volatility3.schemas: All validations will report success, even with malformed input
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!thread_group
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!vmem
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!IOSKArena
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!IOSKRegion
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!IOSKMapper
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!IOMemoryDescriptor
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!\_\_lck_attr\_\_
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!\_\_lck_grp_attr\_\_

**Comment by atcuno** [comment]
@PeterQi can you please try the pslist and lsmod plugins and report back if you get any output?
