### ISSUE TITLE
Mftscan enters infinite loop (How long should a timeline take?)

### ISSUE THREAD

**Issue by robertstrom** [volatilityfoundation/volatility3#646]
**Describe the bug**
Timeliner plugin not completing / taking forever

**Context**
Volatility Version:  
Volatility 3 Framework 2.0.0
Operating System:  
NAME="Linux Mint"
VERSION="20.3 (Una)"
Python Version:  
Python 3.8.10
Suspected Operating System:  
0,"NtMajorVersion","10"
0,"NtMinorVersion","0"
0,"Major/Minor","15.22000"
Command:  
currently running command
/home/rstrom/volatility3/vol.py -f /mnt/data/memoryimages/U-4678457_memory.raw timeliner.Timeliner
previously attempted command
/home/rstrom/volatility3/vol.py --parallelism -f /mnt/data/memoryimages/U-4678457_memory.raw timeliner.Timeliner
**To Reproduce**

1. Use command '...' /home/rstrom/volatility3/vol.py -f /mnt/data/memoryimages/U-4678457_memory.raw timeliner.Timeliner 
2. See error - no error, just a timeline plugin command that has been running for 108 hours with no signs of completing

**Expected behavior**

The completion of a timeline in a reasonable amount of time. I have run numerous other volatility plugin commands against the same memory image on the same Linux system producing the expected results within a reasonable amount of time. All of the files listed below were the result of volatility commands run on the same system as the current timeliner plugin command. These 20 plugins all ran and completed within approximately a half an hour.

-rw-rw-r-- 1 rstrom rstrom  729 Feb  4 22:36 U-4678457_volatility_windows.info.Info.csv
-rw-rw-r-- 1 rstrom rstrom  84K Feb  4 22:39 U-4678457_volatility_windows.psscan.PsScan.csv
-rw-rw-r-- 1 rstrom rstrom  36K Feb  4 22:41 U-4678457_volatility_windows.netscan.NetScan.csv
-rw-rw-r-- 1 rstrom rstrom 117K Feb  4 22:42 U-4678457_volatility_windows.pstree.PsTree.csv
-rw-rw-r-- 1 rstrom rstrom  295 Feb  4 22:43 U-4678457_volatility_windows.registry.userassist.UserAssist.csv
-rw-rw-r-- 1 rstrom rstrom   53 Feb  4 22:43 U-4678457_volatility_windows.cachedump.Cachedump.csv
-rw-rw-r-- 1 rstrom rstrom  90K Feb  4 22:44 U-4678457_volatility_windows.cmdline.CmdLine.csv
-rw-rw-r-- 1 rstrom rstrom  12K Feb  4 22:44 U-4678457_volatility_windows.netstat.NetStat.csv
-rw-rw-r-- 1 rstrom rstrom  85K Feb  4 22:45 U-4678457_volatility_windows.pslist.PsList.csv
-rw-rw-r-- 1 rstrom rstrom  500 Feb  4 22:45 U-4678457_volatility_windows.hashdump.Hashdump.csv
-rw-rw-r-- 1 rstrom rstrom 2.0K Feb  4 22:46 U-4678457_volatility_windows.lsadump.Lsadump.csv
-rw-rw-r-- 1 rstrom rstrom 765K Feb  4 22:47 U-4678457_volatility_windows.envars.Envars.csv
-rw-rw-r-- 1 rstrom rstrom 1.9M Feb  4 22:48 U-4678457_volatility_windows.dlllist.DllList.csv
-rw-rw-r-- 1 rstrom rstrom 137K Feb  4 22:48 U-4678457_volatility_windows.svcscan.SvcScan.csv
-rw-rw-r-- 1 rstrom rstrom 1.3M Feb  4 22:56 U-4678457_volatility_windows.filescan.FileScan.csv
-rw-rw-r-- 1 rstrom rstrom 815K Feb  4 22:59 U-4678457_volatility_windows.verinfo.VerInfo.csv
-rw-rw-r-- 1 rstrom rstrom  43K Feb  4 23:06 U-4678457_volatility_windows.malfind.Malfind.csv
-rw-rw-r-- 1 rstrom rstrom 543K Feb  4 23:07 U-4678457_volatility_windows.getsids.GetSIDs.csv
-rw-rw-r-- 1 rstrom rstrom  38K Feb  4 23:07 U-4678457_volatility_windows.getservicesids.GetServiceSIDs.csv
-rw-rw-r-- 1 rstrom rstrom  18K Feb  4 23:10 U-4678457_volatility_windows.driverscan.DriverScan.csv

The command for the timeliner plugin was started on February 7th and is still running with zero results currently

-rw-rw-r-- 1 rstrom rstrom    0 Feb  7 20:31 U-4678457_memory.timeliner.Timeliner.csv

**Screenshots**

**Additional information**
 The additional information above that mentions a command with the --parallelism command line argument was mentioned because I tried running the timeliner plugin with this paramenter so that volatility would use multiple CPU's to execute the command and speed up the time line for obtaining results. The command started but crashed shortly after execution. I do not have that crash information at this time. So at this time the timeliner plugin is running using only one CPU. I have also tried the --parallelism argument in some other situations and, while it does use multiple CPU's, it does not seem to actually decrease the time for results to be produced. As a matter of fact I was playing around with it on an 8GB Raspberry Pi and all 4 CPU's were used and the results for a series of multiple plugin command lines actually took longer than running the same series on the same Raspberry Pi when using only one CPU.

/home/rstrom/volatility3/vol.py --parallelism -f /mnt/data/memoryimages/USF-4678457_memory.raw timeliner.Timeliner

**Comment by ikelos** [comment]
Sadly the `--parallelism` code isn't all that useful and tends to still take as long for a number of reasons (it only applies to the scanning steps, and the generator for the blocks to scan happens outside of the parallelism and is really slow, pypy might give better results), which is why we turn it off be default.

The timeliner plugin *should* take as long to run as each of the applicable plugins, and unfortunately it won't return results until the last plugin has run because it sorts them based on the timestamp returned.  At the moment there is no functionality for immediate results, since most people want the timeliner to generate a timeline.  We could probably start outputting data to the body file early (at the moment we wait until the plugin has completed)?  However, the plugin should provide progress output as it runs the automagic and then as it runs the plugins, so you should be seeing along the lines of:

```
Volatility 3 Framework 2.0.2
Progress:  100.00		PDB scanning finished                         
Plugin	Description	Created Date	Modified Date	Accessed Date	Changed Date
Progress:   25.00		Running plugin MFTScan...                     
```

If you can't see that in the stderr output, it suggests something's gone wrong far higher up.  I'd recommend running it with `-vvvvvv` to see if it gets past the automagic.  It may be a single plugin causing the issue (scans that go through the virtual address space may take a very long time on windows 10 systems, although we try to detect and avoid windows mapping *lots* of pages to a dummy page).

You can also use `--plugin-filter` to narrow the number of plugins that timeliner will run.

**Comment by ikelos** [comment]
My guess would be the `mftscan` plugin, it seems like it can take a *really* long time to return...  5:S

**Comment by ikelos** [comment]
Could you please try out PR #647 ?  It will likely write to a temporary file, but that should grow as output occurs.  Also, if the execution is cancelled before the plugin is complete (and any output has been produced) the file should get renamed to the requested filename and contain the data that had been written so far.

**Comment by robertstrom** [comment]
I believe that I am trying PR #647 - I am just barely starting to learn git / I am not a programmer ;-) Luckily atcuno preemptively guided me in a reply to my post in Running Vol3 PSTREE Module #574.

Here I believe that I am running the code that you mentioned
```
rstrom@linux-mint-vm:~/volatility3$ git pull
rstrom@linux-mint-vm:~/volatility3$ git checkout issues/issue646
Branch 'issues/issue646' set up to track remote branch 'issues/issue646' from 'origin'.
Switched to a new branch 'issues/issue646'
rstrom@linux-mint-vm:~/volatility3$ git status
On branch issues/issue646
Your branch is up to date with 'origin/issues/issue646'.

nothing to commit, working tree clean
rstrom@linux-mint-vm:~/volatility3$ 
```

After killing the other running timeline (at about 132 hours), I have started it again with -vvvvvv and in addition to what you have done I am writing to a log file

```
/home/rstrom/volatility3/vol.py -vvvvvv -l /home/rstrom/volatility-output/timeliner.log -r csv -f /mnt/data/memoryimages/U-4678457_memory.raw timeliner.Timeliner > /home/rstrom/volatility-output/U-4678457_memory.timeliner.Timeliner.csv
```
We'll see how it goes.

I never really did see much in the way of progress. I believe that I saw some early on but after that I just saw this. So yes, it looks like it is stuck on the MFT scan. The memory image is from a computer (laptop) with 24GB of RAM.

```
DEBUG    volatility3.plugins.windows.mftscan: Attr Type: PROPERTY_SET
DEBUG    volatility3.plugins.windows.mftscan: Attr Type: PROPERTY_SET
DEBUG    volatility3.plugins.windows.mftscan: Attr Type: PROPERTY_SET
DEBUG    volatility3.plugins.windows.mftscan: Attr Type: PROPERTY_SET
DEBUG    volatility3.plugins.windows.mftscan: Attr Type: PROPERTY_SET
DEBUG    volatility3.plugins.windows.mftscan: Attr Type: PROPERTY_SET
DEBUG    volatility3.plugins.windows.mftscan: Attr Type: PROPERTY_SET
DEBUG    volatility3.plugins.windows.mftscan: Attr Type: PROPERTY_SET
DEBUG    volatility3.plugins.windows.mftscan: Attr Type: PROPERTY_SET
DEBUG    volatility3.plugins.windows.mftscan: Attr Type: PROPERTY_SET
^CTraceback (most recent call last):
  File "/home/rstrom/volatility3/vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/home/rstrom/volatility3/volatility3/cli/__init__.py", line 625, in main
    CommandLine().run()
  File "/home/rstrom/volatility3/volatility3/cli/__init__.py", line 333, in run
    renderers[args.renderer]().render(constructed.run())
  File "/home/rstrom/volatility3/volatility3/cli/text_renderer.py", line 241, in render
    grid.populate(visitor, outfd)
  File "/home/rstrom/volatility3/volatility3/framework/renderers/__init__.py", line 212, in populate
    for (level, item) in self._generator:
  File "/home/rstrom/volatility3/volatility3/framework/plugins/timeliner.py", line 115, in _generator
    for (item, timestamp_type, timestamp) in plugin.generate_timeline():
  File "/home/rstrom/volatility3/volatility3/framework/plugins/windows/mftscan.py", line 138, in generate_timeline
    for row in self._generator():
  File "/home/rstrom/volatility3/volatility3/framework/plugins/windows/mftscan.py", line 76, in _generator
    vollog.debug(f"Attr Type: {attr_header.AttrType.lookup()}")
  File "/usr/lib/python3.8/logging/__init__.py", line 1433, in debug
    if self.isEnabledFor(DEBUG):
KeyboardInterrupt
```

Thanks much!

Robert

**Comment by robertstrom** [comment]
Started the timeliner plugin command at 

**22-02-13 10:33:16** volatility3.cli INFO     Logging started

It is now 1:10PM

I stopped the timeline @ 22-02-13 13:09:01 since it already looks like it is hung and the log file is sitting at 3.9GB

at 22-02-13 10:52:33 I started seeing these log entries

22-02-13 10:52:33 volatility3.plugins.windows.mftscan DEBUG    Attr Type: PROPERTY_SET

![image](https://user-images.githubusercontent.com/3240205/153773475-813f7a81-52a9-4df4-bd26-f03c76f9062b.png)

**2048547** which is the entry shown above through the end of the file at line **46081253**

I believe that I have confirmed that all entries past line 2048547 are nothing but

"DEBUG    Attr Type: PROPERTY_SET"

Total number of lines in log file = 46081253
Line number that these entries begin on = 2048547

46081253 - 2048547 = 44032706

tail -n 44032706 timeliner.log | grep -v 'DEBUG    Attr Type: PROPERTY_SET'

and there are no results

remove the -v from the grep command and there are results and add a wc -l to the end and the count is, as expected

44032706

![image](https://user-images.githubusercontent.com/3240205/153773455-158862c5-42ee-4b2d-a973-39babf205313.png)

Where do we go from here?

Thanks!

**Comment by ikelos** [comment]
Great work on the debugging!  You've narrowed it down to a loop that happens in `mftscan`, and it looks as though there *is* a circumstance when it could get into an infinite loop.  Could you please add the following code at [line 127](https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/plugins/windows/mftscan.py#L127) of the `mftscan` file please?

```
  if attr_header.Length == 0:
    print("Infinite loop detected")
    break
````

That should tell us whether a) I'm right and you're hitting an infinite loop and b) whether this helps gets past it).  If so, then it's an easy fix, if not then it's back to inspect the code more carefully...  5:)

**Comment by ikelos** [comment]
I've run local tests, and updated pull request #647 to include the mftscan fix.  `mftscan` will likely still take a long time to complete (particularly with 24Gb to scan), but hopefully it will complete in a reasonable time (and there's no other plugins with infinite loops).  After you confirm that, I'll get #647 merged...  5:)

**Comment by robertstrom** [comment]
I made the modification to the **./volatility3/framework/plugins/windows/mftscan.py** file

![image](https://user-images.githubusercontent.com/3240205/153927827-0ed6319d-924f-458b-b880-237c0989218f.png)

I kicked it off and it ran for approximately 30 minutes before stopping. Start time was:

-rw-rw-r--  1 rstrom rstrom    0 **Feb 14 09:35** U-4678457_memory.timeliner.Timeliner.csv

And the time when the break kicked in was

**22-02-14 10:06:11**

![image](https://user-images.githubusercontent.com/3240205/153928083-66848a55-05c9-40fe-b7eb-7730322b7feb.png)

Hopefully that gives you the information that you need (seems like it did).

**Comment by ikelos** [comment]
Awesome, thanks.  If timeliner completed then it looks like it was just `mftscan` getting stuck!  5:)  I'll make the merge which should close this off, thanks for your help debugging it all!  5:D
