### ISSUE TITLE
Hashdump not working : AttributeError: 'NoneType' object has no attribute 'get_key'

### ISSUE THREAD

**Issue by h49nakxs** [volatilityfoundation/volatility3#665]
**Describe the bug**
Plugin hashdump is not working as expected. Instead, it throws the following error : 
> AttributeError: 'NoneType' object has no attribute 'get_key'

**Context**
Volatility Version:  Volatility 3 Framework 2.0.2
Operating System:  Linux host 5.16.0-kali1-amd64
Python Version:  Python 3.9.10
Suspected Operating System:  Microsoft Windows Server 2012 R2 Standard
Command:  python3 vol.py -f SILO-20180105-221806.dmp windows.hashdump

**To Reproduce**
1) Download the dump available here :
https://www.dropbox.com/sh/69skryzfszb7elq/AADZnQEbbqDoIf5L2d0PBxENa?dl=0
Password = £%Hm8646uC$

2) Run the following command : 
`python3 vol.py -f SILO-20180105-221806.dmp windows.hashdump`

**Expected behavior**
Dump of the NTLM hashes

**Additional information**
This is for a HTB challenge so there's no private information inside the dump. Also, regarding the many write-ups available on the web, the hash dump used to work with previous version of volatility (either 2 or 3).

**Comment by ikelos** [comment]
Interesting, thanks for the information and the image to reproduce it.  Git bisection shows it up as being a recent patch: `265b2825697ecb8c94ba8654acd6191ba0055fdd`, but it's not clear immediately why it's causing the problem.  I guess possibly the code was expecting an exception somewhere and instead for an empty string?  I'll dig into it more but it should be pretty fixable...  5:)
