### ISSUE TITLE
Freed big pools in list_big_pools()

### ISSUE THREAD

**Issue by paulkermann** [volatilityfoundation/volatility3#668]
When a big pool is freed the struct's `self.Va` is or'd with `0x1` (as per [Alex Ionescu's blog post](https://www.alex-ionescu.com/?p=231)).

> One thing to be aware of is that the Virtual Address (Va) is OR’ed with a bit to indicate if the allocation is freed or allocated — in other words, you may have duplicate Va’s, some freed, and at most one allocated.

Currently the `BigPools` plugin doesn't check if a big pool was freed (and no `is_freed` method is available for `POOL_TRACKER_BIG_PAGES` in volatility3/framework/symbols/windows/extensions/pool.py). So big pool information returned by the plugin can be deceiving, e.g. a virtual address could fall within the bounds of both a freed big pool and a newly-allocated big pool.

I'd suggest having an `is_freed` method, and also allowing to filter results by their freed status in `list_big_pools()`. 
Alternatively, modify the current `is_valid()` method to also verify `(self.Va & 1) == 0`. That depends on your interpretation of the `is_valid()` functionality.

**Comment by iMHLv2** [comment]
@paulkermann Could you give this branch (https://github.com/volatilityfoundation/volatility3/compare/issue_668_windows_freed_big_pools) a try and let me know if it works as you'd like?

**Comment by paulkermann** [comment]
Tested this on a couple of samples, seems to work great. Thank you for implementing this logic.
I'd rename the BooleanRequirement's to `show-free` with a `-` as this seems to be the convention (for example `include-corrupt` in `/framework/plugins/windows/netstat.py`) - Volatility automatically refactors it to `show-free` anyway.

**Comment by ikelos** [comment]
Yep, as you say the CLI fixes it anyway, but consistency is good.  5;)  Thanks for the version bump at @iMHLv2.  Technically for an additive change, I think the `MINOR_VERSION` gets bumped the `REVISION` gets set back to 0 (I think the semantic version checking only uses the major and minor numbers), but thanks for remembering it!  5:D

**Comment by ikelos** [comment]
I think this is closed by #706 being merged (feel free to reopen it if not)  5:)
