### ISSUE TITLE
Missing double quotes csv output of two plugins 

### ISSUE THREAD

**Issue by blueteam0ps** [volatilityfoundation/volatility3#672]
Following were observed with Volatility 3 Framework 2.0.0 csv output.

Plugins -
windows.cmdline.CmdLine
windows.registry.userassist.UserAssist.csv

Output contained certain rules that doesn't have closing double quotes.
Pls find below an example

0,624,"svchost.exe","C:\Windows\system32\svchost.exe -k DcomLaunch -p -s LSM"
0,512,"LogonUI.exe",""LogonUI.exe" /flags:0x2 /state0:0xa3bd1855 /state1:0x41c64e6d"

**Comment by digitalisx** [comment]
Hello @blueteam0ps,
As a result of running the command to confirm the output you mentioned,
it was confirmed that it was printed the same as the above result.
However, the output looks normal, and the actual Raw data is stored in the following form as in the example above.
```
"LogonUI.exe" /flags:0x2 /state0:0xa3bd1855 /state1:0x41c64e6d
```
It can be seen that double quotes have been added left and right to change this to suit the CSV Rederer.
```
" + "LogonUI.exe" /flags:0x2 /state0:0xa3bd1855 /state1:0x41c64e6d + "
""LogonUI.exe" /flags:0x2 /state0:0xa3bd1855 /state1:0x41c64e6d"
```
If I misunderstand the problem, please leave an additional thread in this issue.
Thank you.

**Comment by ikelos** [comment]
Thanks very much, I'm surprised I manually implemented csv first time around, but I've now adapted it to use the built-in python CSV module, which handles quotes properly (as well as only using quotes when strictly necessary).  This should get merged in in a few days, but please feel free to test the branch before then and shout if there's any issues.  5:)
