### ISSUE TITLE
libyara undefined symbol lookup_rule

### ISSUE THREAD

**Issue by slsanna** [volatilityfoundation/volatility3#679]
Hi guys, I installed everything but when I type python3 vol.py -h I get this error:
AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule
I tried every solution on Google about libyara to link the correct file but none of them worked.
Can you help me please?

**Context**
Volatility Version:  3
Operating System:  kali 5.6.11
Python Version:  3.9

**Comment by ikelos** [comment]
Hiya, could you please check which version of yara's python interface you're using and which copy of the yara library you have?  It sounds like there's a mismatch.  There's an [old yara library](https://pypi.org/project/yara/) for python which doesn't work and a [new one](https://pypi.org/project/yara-python/) which should.  You'll also need to make sure that the appropriate library for the python version is installed.

This isn't really a volatility issue though, so could I ask you to see further help on our [community slack channel](https://www.volatilityfoundation.org/slack) please?  It's a much better place for asking questions and getting support like this.  As such, I'm going to close this issue, but feel free to reopen it if you find out there's an actual issue with volatility, or just comment on it if you have difficulty getting on to slack...  5:)
