### ISSUE TITLE
Unable to Run Plugins on a LiME file

### ISSUE THREAD

**Issue by awiley-coyote** [volatilityfoundation/volatility3#680]
**Describe the bug**
(this shows up with all plugins, except the banner.Banners plugin)
Unsatisfied requirement plugins.Lsmod.kernel: Linux kernel
Unable to validate the plugin requirements: ['plugins.Lsmod.kernel']

**Context**
Volatility Version:  Volatility 3 Framework 2.0.2
Operating System:  Linux ubuntu 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Python Version:  3
Suspected Operating System:  see above
Command:  vol -f myRAMDump.lime linux.lsmod.Lsmod

**Expected behavior**
An module output

**Comment by ikelos** [comment]
Thanks, could you please make sure that the banners reported under the `banners` plugin match with an ISF file in the output of `isfinfo`?  It would also be useful to attach or include the full output of an attempted run using `vol.py -vvvvvvv` to give us as much information as possible...

**Comment by awiley-coyote** [comment]
![Annotation 2022-03-16 160735](https://user-images.githubusercontent.com/63591759/158681189-c16e9d4c-e35a-4ad2-af0a-3bd6c65435c6.png)

This is the output when I tried vol -v

So, likely I have misconfigured volatility. If you have any suggestions I would love them, I am not skilled with linux. Barring that, I will just reinstall volatility. Thank you for your prompt response.

**Comment by ikelos** [comment]
Sorry, what I meant by running `vol.py -vvvvvv` was in addition to the previous flags you were using, so `vol.py -vvvvvvv -f <path-to-linux-image> linux.pslist`.  Please also note that it's multiple v's in order to increase the verbosity.  Also hopefully you can run the `banners` and `isfinfo` plugin and make sure that the values match appropriately.

**Comment by awiley-coyote** [comment]
INFO     volatility3.cli: Volatility plugins path: ['/home/hunter/.local/lib/python3.8/site-packages/volatility3/plugins', '/home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/plugins']
INFO     volatility3.cli: Volatility symbols path: ['/home/hunter/.local/lib/python3.8/site-packages/volatility3/symbols', '/home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/symbols']
Level 6  volatility3.framework: Importing from the following paths: /home/hunter/.local/lib/python3.8/site-packages/volatility3/plugins, /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/plugins
INFO     volatility3.plugins.yarascan: Python Yara (>3.8.0) module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: 
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.yarascan based on file: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/plugins/yarascan.py
INFO     volatility3.plugins.yarascan: Python Yara (>3.8.0) module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: 
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.svcscan based on file: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/plugins/windows/svcscan.py
INFO     volatility3.plugins.yarascan: Python Yara (>3.8.0) module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: 
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.callbacks based on file: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/plugins/windows/callbacks.py
INFO     volatility3.plugins.yarascan: Python Yara (>3.8.0) module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: 
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.mftscan based on file: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/plugins/windows/mftscan.py
INFO     volatility3.plugins.yarascan: Python Yara (>3.8.0) module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: 
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.vadyarascan based on file: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/plugins/windows/vadyarascan.py
INFO     volatility3.cli: The following plugins could not be loaded (use -vv to see why): volatility3.plugins.windows.callbacks, volatility3.plugins.windows.mftscan, volatility3.plugins.windows.svcscan, volatility3.plugins.windows.vadyarascan, volatility3.plugins.yarascan
Level 6  volatility3.framework: Importing from the following paths: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/automagic
Level 7  volatility3.cli: Cache directory used: /home/hunter/.cache/volatility3
INFO     volatility3.framework.automagic: Detected a linux category plugin
Level 6  volatility3.framework: Importing from the following paths: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/layers
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 6  volatility3.framework: Importing from the following paths: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsmod.kernel
Level 6  volatility3.framework: Importing from the following paths: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsmod.kernel
Level 6  volatility3.framework: Importing from the following paths: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/layers
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Lsmod.kernel
Level 6  volatility3.framework: Importing from the following paths: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsmod.kernel.layer_name
Level 6  volatility3.framework: Importing from the following paths: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/layers
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Lsmod.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsmod.kernel.layer_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Lsmod.kernel
Level 6  volatility3.framework: Importing from the following paths: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Lsmod.kernel.symbol_table_name
Level 6  volatility3.framework: Importing from the following paths: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/layers
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Lsmod.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Lsmod.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Lsmod.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsmod.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Lsmod
INFO     volatility3.framework.automagic: Running automagic: SymbolBannerCache
INFO     volatility3.framework.automagic: Running automagic: LinuxBannerCache
Level 6  volatility3.framework.symbols.intermed: Searching for symbols in /home/hunter/.local/lib/python3.8/site-packages/volatility3/symbols, /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/symbols
INFO     volatility3.framework.automagic.symbol_cache: Building linux caches...
Level 7  volatility3.framework.layers.resources: Available URL handlers: HTTPErrorProcessor, HTTPDefaultErrorHandler, HTTPRedirectHandler, ProxyHandler, HTTPBasicAuthHandler, ProxyBasicAuthHandler, HTTPDigestAuthHandler, ProxyDigestAuthHandler, AbstractHTTPHandler, HTTPHandler, HTTPSHandler, HTTPCookieProcessor, UnknownHandler, FileHandler, FTPHandler, CacheFTPHandler, DataHandler, VolatilityHandler, JarHandler, OfflineHandler
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 6  volatility3.framework: Importing from the following paths: /home/hunter/.local/lib/python3.8/site-packages/volatility3/framework/layers
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsmod.kernel
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using AVMLStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 6  volatility3.framework.layers.elf: Exception: Bad magic 0x905c689 at file offset 0x0
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LinuxIntelStacker
INFO     volatility3.framework.automagic.linux: No Linux banners found - if this is a linux plugin, please check your symbol files location
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsmod.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: TypeError - Layer is not the required Architecture: FileLayer
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['FileLayer']
INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
INFO     volatility3.framework.automagic: Running automagic: LinuxSymbolFinder
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Lsmod.kernel.symbol_table_name
INFO     volatility3.framework.automagic: Running automagic: KernelModule
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsmod.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsmod.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Lsmod.kernel
Unable to validate the plugin requirements: ['plugins.Lsmod.kernel']


This is what I got from the vol -vvvvvvv

**Comment by awiley-coyote** [comment]
{
    "symbols": {}, 
    "enums": {}, 
    "base_types": {
        "unsigned char": {
            "kind": "char", 
            "size": 1, 
            "signed": false, 
            "endian": "little"
        }, 
        "pointer": {
            "kind": "int", 
            "size": 8, 
            "signed": false, 
            "endian": "little"
        }
    }, 
    "user_types": {
        "hist_entry": {
            "fields": {
                "timestamp": {
                    "type": {
                        "subtype": {
                            "count": 1024, 
                            "subtype": {
                                "kind": "base", 
                                "name": "unsigned char"
                            }, 
                            "kind": "array"
                        }, 
                        "kind": "pointer"
                    }, 
                    "offset": 8
                }, 
                "line": {
                    "type": {
                        "subtype": {
                            "count": 1024, 
                            "subtype": {
                                "kind": "base", 
                                "name": "unsigned char"
                            }, 
                            "kind": "array"
                        }, 
                        "kind": "pointer"
                    }, 
                    "offset": 0
                }, 
                "data": {
                    "type": {
                        "subtype": {
                            "kind": "struct", 
                            "name": "void"
                        }, 
                        "kind": "pointer"
                    }, 
                    "offset": 16
                }
            }, 
            "kind": "struct", 
            "size": 24
        }
    }, 
    "metadata": {
        "producer": {
            "version": "0.0.1", 
            "name": "/mnt/hgfs/volshared/vtypes_to_json.py", 
            "datetime": "2018-12-03T09:55:34.880766"
        }, 
        "format": "4.1.0"
    }
}
This is the JSON

**Comment by ikelos** [comment]
Ok, so there's a few things going on here.  The first is that the JSON file you've got  has no symbols, and perhaps only a couple of user types in it, this also means that it doesn't contain the banner of the linux version it supports, and volatility needs this to figure out which one to use for each memory image it encounters.  I'm not sure where the `vtypes_to_json` tool came from, but it's not producing enough information to make a usable symbol table.  I'd recommend using the `banners` plugin to determine the specific kernel you're looking for, and then track down the debugging kernel for that (assuming it's one of the major distros, if you can't find the debugging kernel then things will become a lot more difficult).  Once you've got the debugging kernel, follow along with [this section](https://volatility3.readthedocs.io/en/stable/symbol-tables.html#mac-linux-symbol-tables) to use `dwarf2jon` to produce an appropriate ISF JSON file... 

Once you've got that the `isfinfo` plugin should show you the banner and give you healthy numbers in the output of `isfinfo`.  Once all that's in place, it should get rid of the message saying `INFO volatility3.framework.automagic.linux: No Linux banners found - if this is a linux plugin, please check your symbol files location` and if the numbers are right it might even give you results...  5;)

**Comment by awiley-coyote** [comment]
Thank you
