### ISSUE TITLE
dumpfiles - required module capstone

### ISSUE THREAD

**Issue by 0xtejas** [volatilityfoundation/volatility3#687]
**Describe the bug**
dumpfiles require capstone module 

**Context**
Volatility Version:  2.0.2
Operating System:  Ubuntu 16.07 LTS
Python Version:  python3.9.4
Suspected Operating System:  Windows 10 x64 
Command:  `python3.9 volatility3/vol.py -o dump/ -f physmemraw windows.dumpfiles --pid 10432` (PID of Notepad.exe)`

**To Reproduce**

1. Use command 'python3.9 volatility3/vol.py -o dump/ -f physmemraw windows.dumpfiles --pid 10432` (PID of Notepad.exe)'
2. See error 

```bash
Volatility 3 Framework 2.0.2
Progress:  100.00		PDB scanning finished                        
Cache	FileObject	FileName	Result


Volatility could not import a necessary module: capstone
Requires capstone to find the SAR value for decoding handle table pointers

	* A required python module is not installed (install the module and re-run)

No further results will be produced
```

**Expected behavior**
I should be able to dump the file.. for some reason I was not able to dump file found from `filescan` by using option `virtaddr` and `phyaddr`

**Screenshots**
![image](https://user-images.githubusercontent.com/47889755/160175240-88fa13ee-e412-40ba-8304-c52277ad6c85.png)

**Additional Information**

Here the vol3 is an alias set to `python3 <vol.py location>`

**Comment by ikelos** [comment]
Thanks very much for your report.  Dumpfiles is designed to locate file handles within the address space of a process, and extract any that it finds.  To do this, it uses the handles plugin, which (in order to find necessary structures) relies on on capstone to locate the SAR value as mentioned in the error message.  As such, the error message is correct, and you'll need to install capstone in order to be able to dump all file handle objects from the process you've listed.

If you're just trying to dump the memory of the specific process identified by the pid, then you probably want to use `pslist --dump` instead.  `dumpfiles` is specifically for dumping file that the process has open.  Please let us know whether you were intending to dump all the files in file handles held by the process, and believe that can be done without capstone, or whether you'd just wanted to dump the process and we can close this bug.  Thanks...

**Comment by 0xtejas** [comment]
> Thanks very much for your report. Dumpfiles is designed to locate file handles within the address space of a process, and extract any that it finds. To do this, it uses the handles plugin, which (in order to find necessary structures) relies on on capstone to locate the SAR value as mentioned in the error message. As such, the error message is correct, and you'll need to install capstone in order to be able to dump all file handle objects from the process you've listed.
> 
> If you're just trying to dump the memory of the specific process identified by the pid, then you probably want to use `pslist --dump` instead. `dumpfiles` is specifically for dumping file that the process has open. Please let us know whether you were intending to dump all the files in file handles held by the process, and believe that can be done without capstone, or whether you'd just wanted to dump the process and we can close this bug. Thanks...

My bad that I didn't mention that I installed capstone module. I hoped I can dump the file used by the process. I didn't want to dump the process (I know that it needs other approach).

**Comment by chikyukrish** [comment]
i have same trouble

**Comment by chikyukrish** [comment]
> > Thanks very much for your report. Dumpfiles is designed to locate file handles within the address space of a process, and extract any that it finds. To do this, it uses the handles plugin, which (in order to find necessary structures) relies on on capstone to locate the SAR value as mentioned in the error message. As such, the error message is correct, and you'll need to install capstone in order to be able to dump all file handle objects from the process you've listed.
> > If you're just trying to dump the memory of the specific process identified by the pid, then you probably want to use `pslist --dump` instead. `dumpfiles` is specifically for dumping file that the process has open. Please let us know whether you were intending to dump all the files in file handles held by the process, and believe that can be done without capstone, or whether you'd just wanted to dump the process and we can close this bug. Thanks...
> 
> My bad that I didn't mention that I installed capstone module. I hoped I can dump the file used by the process. I didn't want to dump the process (I know that it needs other approach).

are you playing ctf?

**Comment by 0xtejas** [comment]
> are you playing ctf?

I was and then I left.

**Comment by ikelos** [comment]
Hmmm, if you think you have the capstone module installed, but the plugin isn't finding it, then it's possible it's installed for a different version of python?  You can test whether it's installed for the version of python that volatility uses by running that version of python (I assume python3.9) and trying `import capstone`.  If that fails then it hasn't installed for that version of python correctly, and you could try using pip from that version of python to install it properly.  If it does import correctly then we can try digging into more but honestly I'd be very surprised if that happens...

**Comment by 0xtejas** [comment]
I'm closing issue because it was an issue caused by having multiple python versions. 
sorry for the trouble

**Comment by ikelos** [comment]
No problem, glad you figured out what was going wrong.  5:)

**Comment by chikyukrish** [comment]
i have a solution, you can use this comand `$python3 vol.py -f physmemraw -o . windows.dumpfiles --pid 8180`

**Comment by Ultra7FLASH** [comment]
> I'm closing issue because it was an issue caused by having multiple python versions. sorry for the trouble

can you explain how you overcame this issue, because I'm having the same issue here.

**Comment by 0xtejas** [comment]
> can you explain how you overcame this issue, because I'm having the same issue here.

If I remember correctly I had installed the module in pip for python3.5 whilst I was running volatility for python3.9 causing the issue. 
Or maybe installed it with pip for python2 and ran it with python3 causing the issue.

**Comment by sluke-nuix** [comment]
For future searchers:  I had the same issue, but different scenario:
* Python 3.12
* capstone was installed
* Same error as reported here for windows.handles plugin, or for dumpfiles.

Testing:
* Launched Python interactive shell and did import capstone, and it reported an error loading distutils

Cause:
* distutils was deprecated in Python 3.10 and removed from the standard library in 3.12
* capstone 5.0.1, the latest as of this post, still relies on it

Solution:
* install setuptools (I used 69.2.0) which also provides distutils
