### ISSUE TITLE
The windows.filescan command did not output correctly

### ISSUE THREAD

**Issue by Randark-JMT** [volatilityfoundation/volatility3#696]
When I try to execute the filescan command to view the file, Volatility does seem to execute filescan, but I don't get the corresponding output

Volatility Version:  3.2.0.2
Operating System:  debian 5.10.0-12-amd64
Python Version:  .9.2
Suspected Operating System:  win7sp1_rtm.
Command:  filescan

I wanted to use the filescan command to view the files in memory, but I didn't get any useful output：
![图片](https://user-images.githubusercontent.com/56223739/161293395-6543a8d7-3242-41a3-a4af-1ad989b430e7.png)
And the expected output should be as follows (Volatility2)：
![图片](https://user-images.githubusercontent.com/56223739/161293566-f0a980b1-87af-48d1-b1d4-b0a4048b3a12.png)

**Comment by Randark-JMT** [comment]
Sorry, this is my problem, because I clone the source code directly from Github above and then run it directly python vol.py, so some elements should be missing, which causes filescan to run abnormally. I installed the whl package after downloading it and then ran it without problems.

**Comment by q2dg** [comment]
Well, I don't know if it is the same problem, but with all images provided in all labs from https://github.com/stuxnet999/MemLabs "filescan" plugin is unable to take any output. It's true these labs were thought for Vol2 but it's a bit "strange" Vol2's "filescan" plugin does well while Vol3's one doesn't. I't worth looking at
