### ISSUE TITLE
Implement configuration file for persistent CLI options

### ISSUE THREAD

**Issue by dummys** [volatilityfoundation/volatility3#716]
Hi, I would like to setup a symbol directory without using everytime the `-s` option. Is the volatilityrc still usable ? what is the default configuration search path ? Where is the documentation on the configuration file as well please ?

**Comment by ikelos** [comment]
Hi there, there isn't support for anything like that at the moment, for now you'll need a copy you can edit and then alter the following lines:

https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/constants/__init__.py#L17

We do hope to implement a configuration file mechanism, but we haven't planned out exactly how it'll work yet I'm afraid.
