### ISSUE TITLE
volatility2.6 volatility 3 offset(v) Has the expression changed?

### ISSUE THREAD

**Issue by FurD3n** [volatilityfoundation/volatility3#739]
Hello, I am a student studying forensics. I have a question. Has the expression changed? virturl offset?
The physical offset confirmed the same thing.
0xfffffa8018d47740
0xfa8018d47740	

Volatility Foundation Volatility Framework 2.6
Offset(V)          Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit
------------------ -------------------- ------ ------ ------ -------- ------ ------ ------------------------------ ------------------------------
0xfffffa8018d47740 System                    4      0     94      562 ------      0 2021-11-17 14:48:36 UTC+0000
0xfffffa8019d25b30 smss.exe                264      4      2       29 ------      0 2021-11-17 14:48:36 UTC+0000
0xfffffa801ad6e6d0 csrss.exe               352    336      9      514      0      0 2021-11-17 14:48:37 UTC+0000
0xfffffa801ae5e5f0 wininit.exe             404    336      3       76      0      0 2021-11-17 14:48:38 UTC+0000
0xfffffa801ae5f910 csrss.exe               412    396     12      362      1      0 2021-11-17 14:48:38 UTC+0000
0xfffffa801b003060 services.exe            476    404      6      217      0      0 2021-11-17 14:48:38 UTC+0000
0xfffffa801b00ab30 lsass.exe               484    404      6      565      0      0 2021-11-17 14:48:38 UTC+0000
0xfffffa801b018b30 lsm.exe                 492    404     10      148      0      0 2021-11-17 14:48:38 UTC+0000
0xfffffa801b012060 winlogon.exe            500    396      3      113      1      0 2021-11-17 14:48:38 UTC+0000
0xfffffa801b216060 svchost.exe             636    476     11      373      0      0 2021-11-17 14:48:39 UTC+0000
0xfffffa801b24f060 vm3dservice.ex          700    476      3       44      0      0 2021-11-17 14:48:39 UTC+0000
0xfffffa801b607b30 svchost.exe             724    476      8      283      0      0 2021-11-17 14:48:39 UTC+0000
0xfffffa801b2753a0 svchost.exe             776    476     23      516      0      0 2021-11-17 14:48:39 UTC+0000
0xfffffa801b2d4640 svchost.exe             900    476     24      525      0      0 2021-11-17 14:48:39 UTC+0000
0xfffffa801b2dab30 svchost.exe             940    476     41     1014      0      0 2021-11-17 14:48:39 UTC+0000
0xfffffa801b311060 audiodg.exe            1000    776      6      128      0      0 2021-11-17 14:48:39 UTC+0000
0xfffffa801b3406d0 svchost.exe             400    476     17      420      0      0 2021-11-17 14:48:39 UTC+0000
0xfffffa801b344b30 svchost.exe             988    476     17      494      0      0 2021-11-17 14:48:39 UTC+0000

====================================================================
volatility 3 Framework 2.0.2
Progress:  100.00		PDB scanning finished                  
PID	PPID	ImageFileName	Offset(V)	Threads	Handles	SessionId	Wow64	CreateTime	ExitTime	File output

4	0	System	0xfa8018d47740	94	562	N/A	False	2021-11-17 14:48:36.000000 	N/A	Disabled
264	4	smss.exe	0xfa8019d25b30	2	29	N/A	False	2021-11-17 14:48:36.000000 	N/A	Disabled
352	336	csrss.exe	0xfa801ad6e6d0	9	514	0	False	2021-11-17 14:48:37.000000 	N/A	Disabled
404	336	wininit.exe	0xfa801ae5e5f0	3	76	0	False	2021-11-17 14:48:38.000000 	N/A	Disabled
412	396	csrss.exe	0xfa801ae5f910	12	362	1	False	2021-11-17 14:48:38.000000 	N/A	Disabled
476	404	services.exe	0xfa801b003060	6	217	0	False	2021-11-17 14:48:38.000000 	N/A	Disabled
484	404	lsass.exe	0xfa801b00ab30	6	565	0	False	2021-11-17 14:48:38.000000 	N/A	Disabled
492	404	lsm.exe	0xfa801b018b30	10	148	0	False	2021-11-17 14:48:38.000000 	N/A	Disabled
500	396	winlogon.exe	0xfa801b012060	3	113	1	False	2021-11-17 14:48:38.000000 	N/A	Disabled
636	476	svchost.exe	0xfa801b216060	11	373	0	False	2021-11-17 14:48:39.000000 	N/A	Disabled
700	476	vm3dservice.ex	0xfa801b24f060	3	44	0	False	2021-11-17 14:48:39.000000 	N/A	Disabled
724	476	svchost.exe	0xfa801b607b30	8	283	0	False	2021-11-17 14:48:39.000000 	N/A	Disabled
776	476	svchost.exe	0xfa801b2753a0	23	516	0	False	2021-11-17 14:48:39.000000 	N/A	Disabled
900	476	svchost.exe	0xfa801b2d4640	24	525	0	False	2021-11-17 14:48:39.000000 	N/A	Disabled
940	476	svchost.exe	0xfa801b2dab30	41	1014	0	False	2021-11-17 14:48:39.000000 	N/A	Disabled
1000	776	audiodg.exe	0xfa801b311060	6	128	0	False	2021-11-17 14:48:39.000000 	N/A	Disabled
400	476	svchost.exe	0xfa801b3406d0	17	420	0	False	2021-11-17 14:48:39.000000 	N/A	Disabled
988	476	svchost.exe	0xfa801b344b30	17	494	0	False	2021-11-17 14:48:39.000000 	N/A	Disabled
1120	476	spoolsv.exe	0xfa801b3c7b30	13	265	0	False	2021-11-17 14:48:39.000000 	N/A	Disabled
1172	476	svchost.exe	0xfa801b3f25f0	20	313	0	False	2021-11-17 14:48:39.000000 	N/A	Disabled
1236	476	taskhost.exe	0xfa801b425880	10	212	1	False	2021-11-17 14:48:39.000000 	N/A	Disabled

**Comment by ikelos** [comment]
Thanks, the addresses haven't changed.  On a 64-bit system, only the lowest bits are used in general, the top bits don't contain data and are reserved for future use (in amd64 they are 0 and in ia-32e, they are sign extended).

In volatility 3 we've chosen to mask these so that pointers are comparable if they'll look-up to the same address (ie, the high bits are ignored).  As such they're masked to the maximum size of a pointer for the address space the pointer maps to.  In 64-bit systems this is actually 52-bits, hence why the highest 12 bits aren't displayed.

Hopefully this answers you're question, and as such I'm going to close the ticket.  This isn't really a bug, so if your question hasn't been fully answered I'd suggest asking it on the slack channel (https://www.volatilityfoundation.org/slack) for more of an interactive discussion...  5:)

This relates to #731 and #702.

**Comment by FurD3n** [comment]
Thank you for your detailed answer

**Comment by ikelos** [comment]
In case you're interested, PR #905 is currently being reviewed for inclusion, and provides tool to convert between canonicalized and decanonicalized addresses.
