### ISSUE TITLE
Downloading PDB files failed (`getaddrinfo` failed)

### ISSUE THREAD

**Issue by 3quall** [volatilityfoundation/volatility3#762]
Hello everyone! I hope you are doing great! Can someone help me to figure out what is the problem based on the error that I’m getting below? Thank you in advance!

Command: python vol.py -vvv -f 1st_Resp.raw windows.info

![image](https://user-images.githubusercontent.com/107179197/172805762-76d29dac-5cf3-4f54-a223-93ffa6683e34.png)
![image](https://user-images.githubusercontent.com/107179197/172805844-fffa5de0-3136-4d96-a015-a554d8a12b3a.png)
![image](https://user-images.githubusercontent.com/107179197/172805893-58f058c4-c815-4d62-bd24-5109bdba2d07.png)
![image](https://user-images.githubusercontent.com/107179197/172805905-b6eb5c1a-b3c5-4699-a98c-b10452ef671e.png)

**Comment by ikelos** [comment]
Hiya, so this has identified a windows image, and is trying to download the necessary files to create an ISF JSON for that kernel.  It appears as though the system can't get to the internet (`getaddrinfo failed`) for some reason.  The error message suggests an issue carrying out a DNS lookup for the microsoft.com server.  If your system doesn't have access to the internet, you can manually convert a PDB file into the necessary JSON file (based on https://volatility3.readthedocs.io/en/latest/symbol-tables.html#windows-symbol-tables).  You can also include `--offline` to stop volatility trying to go to the internet on any particular run.

If you need further support, I'd recommend asking on our slack server (https://www.volatilityfoundation.org/slack) where you can get more interactive feedback.  I'll leave this issue open for a bit, but please let us know how you get on and if you run into more problems or whether we can close the issue off.  5:)

**Comment by 3quall** [comment]
Hello @ikelos! Thank you so much for the detailed explanation! However I'm getting the error below when converting the PDB file:

![image](https://user-images.githubusercontent.com/107179197/172826240-32a82b72-8eed-4a71-89d7-907760a668a7.png)

The argument --offline was also unrecognized:
![image](https://user-images.githubusercontent.com/107179197/172826674-3d1a1795-a9a5-4167-88b4-84f285723ae7.png)

Thank you!

**Comment by 3quall** [comment]
Just to add that the VM where I'm using Volatility does not have connection to the internet.

**Comment by digitalisx** [comment]
Hello, @3quall

For the first error, could you try this command?
```
pip3 install volatility3
```
(However, if the environment is not Internet-enabled, you must build and install it on your own.)

The second error is that the version of `volatility3` being used is low.
I tracked the code and it seems that the `offline` option is supported from `2.0.1` or higher.
I recommend that you download and use the latest version.

**Comment by ikelos** [comment]
You can also do as the documentation points out and set `PYTHONPATH="." ` to include the current directory (and therefore the volatility3 subfolder) in the path your copy of python looks in.

`--offline` was added sometime around version 2 of volatility3, I'd recommend updating to either the latest development branch, or at least 2.0.1, since there are a few important fixes in there.  5:)

**Comment by 3quall** [comment]
Thanks for the answers guys!

What is the meaning of PYTHONPATH? Is it the same as Environment Variable of the machine?

**Comment by digitalisx** [comment]
Yes @3quall,
I think what @ikelos says would be the environmental variable of the operating systems.

**Comment by 3quall** [comment]
Thank you so much for helping guys! I really appreciate it!

@ikelos even helped me troubleshoot problems that I encountered through the Slack channel. Very helpful guy!

It seems that the issues that I’ve faced can be resolved easily if the box has connection to the internet, but I have no control over it. I ended up using the lower version of volatility. Thank you so much again! You may close this now. Have a great day!

**Comment by ikelos** [comment]
No problem, sorry we weren't able to help get the pdb file converted for you. Unfortunately there are too many symbols, and new ones coming out all the time, for us to package them all up easily without the internet.  I'm going to mark this as resolved since it's not strictly a bug in the way volatility 3 works, but feel free to reopen this if you think there's something that still needs addressing...
