### ISSUE TITLE
Automatic synchronization of `readthedocs` to the latest version.

### ISSUE THREAD

**Issue by digitalisx** [volatilityfoundation/volatility3#767]
Hello, everyone in the community! 🙂
While I was teaching students about `volatility3`, I told them that it would be good to refer to the document,
but it seems that the [documents](https://volatility3.readthedocs.io/en/latest/) is not synchronized with the latest code.
If possible, I think `readthedocs` will be a little more useful if we reflect the newly added or removed contents in connection with Github Actions.
It's very easy to write Github Actions, which deploy `readthedocs` that are being push to repository.
But credentials and permissions are required to link with `readthedocs`.
So I can't contribute this area.
Perhaps, Could you have any plans or intentions for this? :)

**Comment by ikelos** [comment]
Hiya, By default readthedocs takes you to the current stable version (`stable` branch), but you can get the latest development documentation, for the `develop` branch. by going to the `latest` version or visiting https://volatility3.readthedocs.io/en/latest/.  We've chosen this due to the unstable nature of the `develop` branch and wanting to avoid confusion from people who just download the main package and don't make use of git.  If you find that latest is out of date with develop, please let us know.  Otherwise I believe it's functioning as intended...

**Comment by digitalisx** [comment]
Yes @ikelos, your intentions seem very right.
So I think that the `stable` version is up to date as you said!
However, the `develop` version does not seem to be reflected immediately as the content of the `develop` branch..!
Some of the submodules (like linux `psaux`, windows `devicetree`, `mbrscanner`..) that have been reflected since a certain point in time seem to be missing or have not been updated.
I think most document builds by hand. And last [build](https://readthedocs.org/projects/volatility3/builds/) of `develop` is about 2 months ago.
Could you check this please? 🙂

**Comment by ikelos** [comment]
Thanks, that's all looked after by @npetroni, so best to check in with him.  My understanding was that it should be done automatically, but I'm not certain...  5:)

**Comment by npetroni** [comment]
I rebuilt `latest` and added a webhook. Let's see what happens next push to `develop`.

**Comment by digitalisx** [comment]
@npetroni Thank you for your work! I'll check result when push at `develop` branch. :)

**Comment by digitalisx** [comment]
All right, Recently I was lucky enough to get the chance (#768) will change the document to push at `develop` branch. And when I checked the changes, it was successful. If there is no problem with the participants of this issue, we will close the issue in the near future.

**Comment by ikelos** [comment]
No problem with me.  5:)

**Comment by npetroni** [comment]
Great, thanks. Looks good to me now too.

**Comment by digitalisx** [comment]
Good, all participants have expressed their intentions, so we're happy to close this issue. If there is any additional issue, please open it again. :)
