### ISSUE TITLE
Suggest configuring repository topic for `volatility3`.

### ISSUE THREAD

**Issue by digitalisx** [volatilityfoundation/volatility3#770]
## Description

Hello, everyone in the community! 🙂

Github's repository topic helps more people discover and understand our projects.
We can check the repository topic in the `volatility`.

- [python](https://github.com/topics/python)
- [ram](https://github.com/topics/ram)
- [memory](https://github.com/topics/memory)
- [malware](https://github.com/topics/malware)
- [volatility-framework](https://github.com/topics/volatility-framework)
 
However, `volatility3` does not yet have a [separate topic ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics)associated with it.
Unfortunately, Github has not created a separate proposal feature for this.
If you don't mind, it would be good if the maintainer's designate this.

Adding something will require consultation from the foundation members (maintainers),
but it seems very good just to succeed to the existing `volatility`.

**Comment by digitalisx** [comment]
Hello @awalters, as the star of the `volatility3` project approaches 1k, the interest in the framework is high.
I think it's one of the best ways for more people to get interested and participate in the project. :)

**Comment by awalters** [comment]
Hi @digitalisx, Thank you for the suggestion. I've updated the topics.

**Comment by digitalisx** [comment]
Thank you for your work @awalters!
