### ISSUE TITLE
How to get pdbconv.py to download file behind a network proxy server

### ISSUE THREAD

**Issue by SergeyDrachuk** [volatilityfoundation/volatility3#781]
It seems pdbconv.py can't work behind proxy in a linux

It would be nice to have a possibility to use system-wide environment variables (http_proxy / https_proxy)

If I understand right the "urllib.request" used to download files from Microsoft.
https://github.com/volatilityfoundation/volatility3/blob/cb6af3e5f7f33995fe46de3e6a3d81c9946d6a08/volatility3/framework/layers/resources.py#L120

If there is any existing workaround to work behind proxy I will be very thankfull to know about it.

Thank you taking the time to read.

**Comment by ikelos** [comment]
`urllib` automatically picks up proxy as defined by standard environment variables on linux (it might be the same on windows)?  From the python documentation at https://docs.python.org/3/library/urllib.request.html:
```
In addition, if proxy settings are detected (for example, when a *_proxy environment variable like http_proxy is set), [ProxyHandler](https://docs.python.org/3/library/urllib.request.html#urllib.request.ProxyHandler) is default installed and makes sure the requests are handled through the proxy.
```
So try setting `http_proxy` and `https_proxy` variables, and let us know if that sorts the problem.  Once the allow configuration files (#754) we can look to add specific volatility3 CLI options for setting a proxy.

**Comment by SergeyDrachuk** [comment]
@ikelos, really it works fine (checked in kali with last update).
Thanks 👍
