### ISSUE TITLE
netstat plugin shows "ValueError: too many values to unpack (expected 2)"

### ISSUE THREAD

**Issue by siftuser** [volatilityfoundation/volatility3#799]
**Describe the bug**
netstat plugin shows "ValueError: too many values to unpack (expected 2)"

**Context**
Volatility Version:  Volatility 3 Framework 2.3.0
Operating System:  Ubuntu
Python Version:  3.10
Suspected Operating System:  Win 10 Build: 19042.
Command:   vol -f mem.raw  windows.netstat

**Comment by digitalisx** [comment]
Hello, @siftuser
I think we need a little more logs to investigate the error.
Could you please provide the results using `-vvvv`?

```shell
> python3 vol.py -f mem.raw -vvvv windows.netstat
```

**Comment by ghost** [comment]
Hello there!
I am having the same issue. 

**Context**
Volatility Version: Volatility 3 Framework 2.3.0
Operating System: Mac OS 12.3.1
Python Version: 3.9.9
Suspected Operating System: Win 7 SP1 x64
Command: `python3 vol.py -f mem.raw -vvvv windows.netstat`

It works using Volatility 2.6 Mac standalone, but not using Volatility3.
Executing above command renders the output in the attached log file.
[log.txt](https://github.com/volatilityfoundation/volatility3/files/9330011/log.txt)

**Comment by digitalisx** [comment]
Thank you to everyone for reporting and interesting in this issue. This would have been resolved by this commit (https://github.com/volatilityfoundation/volatility3/commit/1f1355711d08e5e62b27156e5d186e3ed59366b2).
The issue will be closed by the maintainer, and if you have any additional problems, please open the issue again at any time.
