### ISSUE TITLE
Bug with CACHE_PATH

### ISSUE THREAD

**Issue by paulkermann** [volatilityfoundation/volatility3#803]
`constants.CACHE_PATH` is updated if `cache_path` is in the arguments for the cli.
However `LINUX_BANNERS_PATH`, `MAC_BANNERS_PATH` and `IDENTIFIERS_PATH` are not updated accordingly.
This causes those files to be created in the default cache path.
We need to update all those paths as well with the new cache path.

**Comment by jeffguy** [comment]
I've written and tested a bugfix for this. I expected to see a link on this Issue page to create a pull request so my pull request would link to the issue.

When I tried the pull requests page, it looks like it won't allow me to create a pull request straight into the `develop` branch.

You can see my patch at my fork of the repo. Feel free to cherry pick or point me to how I can submit a pull request for this issue.

**Comment by digitalisx** [comment]
Hello @jeffguy,
First of all, thank you for your work.
I believe the maintainer will judge whether this is actually a bug and whether the method you suggested is a good solution.

Here is the [link](https://github.com/volatilityfoundation/volatility3/compare/develop...jeffguy:volatility3:develop) for PR.
The more detail you write down what you suggest and everything about it, the more helpful it will be to merge.

If you still can't open the PR, please tell me
There is also a way for me to open it separately.
