### ISSUE TITLE
Port "cmdscan" and "console" plugins from Vol2 to Vol3, please

### ISSUE THREAD

**Issue by q2dg** [volatilityfoundation/volatility3#816]
**Is your feature request related to a problem? Please describe.**
I want to inspect which commands are executed in a terminal and what is its output but with Vol3 there's no "cmdscan" and "console" plugin equivalent, so I can't get this information.

**Describe the solution you'd like**
A "cmdscan" and "console" plugin port from Vol2 to Vol3

Thanks a lot!

P.S: "Screenshot" plugin would be nice to have, too.

**Comment by LF1scher** [comment]
Is there any news on this? Maybe a workaround? An unofficial plugin? I don't seem to find anything towards this on the Internet, and since Windows 11 is not supported in Volatility 2, it's becoming a problem.

**Comment by eve-mem** [comment]
Not to my knowledge - but it's good to know people are interested.
