### ISSUE TITLE
header.NameInfo.Name cannot be resolved when pool scanning for Executive Objects

### ISSUE THREAD

**Issue by bridgeythegeek** [volatilityfoundation/volatility3#829]
(Apologies if I get terminology wrong! Still trying to get used to Volatility3!)

**Describe the bug**
When pool scanning for executive objectives, the `name` of the executive object is not recovered.

**Context**
Volatility Version:  Volatility 3 Framework 2.3.1 (`git pull` today)
Operating System:  Running Volatility3 on Linux Mint 20.3 Cinnamon (5.4.0-125-generic)
Python Version:  3.8.10
Suspected Operating System:  OS being analysed is **Windows 7 64-bit**
Command:  `python vol.py -f /path/to/WIN7SP1x64.raw windows.mutantscan.MutantScan`

**To Reproduce**
With the command above, many mutants are recovered, but all have a name of `N/A`.

**Expected behavior**
The name of the mutant is returned.

**Screenshots**
```
Volatility 3 Framework 2.3.1
Progress:  100.00		PDB scanning finished                                                                                             
Offset	Name

0xcd1dd70	N/A
0x108df270	N/A
0x108f6940	N/A
0x1d734d30	N/A
0x1ddb35d0	N/A
0x1df28880	N/A
0x1dfec880	N/A
0x1e2142f0	N/A
0x1e234370	N/A
0x1e2362e0	N/A
0x1e2367a0	N/A
0x1e236ac0	N/A
0x1e23c120	N/A
0x1e249e20	N/A
0x1e249f40	N/A
0x1e24c340	N/A
--SNIP--
```

**Additional information**
Running the `mutantscan` plugin from Volatility 2.6.1 against the same memory file does return mutant names:
```
Volatility Foundation Volatility Framework 2.6.1
Offset(P)              #Ptr     #Hnd Signal Thread                   CID Name
------------------ -------- -------- ------ ------------------ --------- ----
0x000000000cd1dd70        2        1      1 0x0000000000000000           VBoxService
0x00000000108df270        1        1      1 0x0000000000000000           
0x00000000108f6940        1        1      1 0x0000000000000000           
0x000000001d734d30        1        1      1 0x0000000000000000           
0x000000001ddb35d0        2        1      1 0x0000000000000000           {bc43c8ff-0e31-41df-9b12-9504be7a6f46}:sqlce_se_lck:12
0x000000001df28880        1        1      1 0x0000000000000000           
0x000000001dfec880        1        1      1 0x0000000000000000           
0x000000001e2142f0        4        3      1 0x0000000000000000           C::Users:memtest:AppData:Local:Microsoft:Windows:Explorer:thumbcache_idx.db!ThumbnailCacheInit
```
### I suspect the problem is...
When the `poolscanner.PoolScanner` plugin is run, it returns an Executive Object in the `native_layer` which has an offset relative to the input file - as opposed to a virtual offset in kernel space:
```
<KMUTANT symbol_table_name1!_KMUTANT: memory_layer @ 0x1ff65060 #56 (Native: layer_name)>
                                                     ^^^^^^^^^^
```
Therefore, when Volatility3 tries to read the offset pointed to by `header.NameInfo.Name` the address is out of bounds. By removing the code from the `mutantscan.MutantScan` plugin that hides the error, we can see this happen:
```
Volatility was unable to read a requested page:
0xf8a000829a40 in layer memory_layer (Offset outside of the buffer boundaries)
```
#### So, I suspect the answer would be...
To have `poolscanner.PoolScanner` return virtual addresses relative to the kernel layer, rather than the input file.

**Comment by bridgeythegeek** [comment]
In poolscanner.py I see:
https://github.com/volatilityfoundation/volatility3/blob/1f1355711d08e5e62b27156e5d186e3ed59366b2/volatility3/framework/plugins/windows/poolscanner.py#L283-L288
This seems to be the culprit. If I comment out L287 and L288, my Mutants have names. Well, some of them do.

**Comment by ikelos** [comment]
So typically windows 10 is special in certain ways, in that it was the first version (I believe) where they introduced the mapping of large chunks of the memory to empty space, so the mappings appear valid (meaning we have to scan them) but contain nothing useful.  *Lots* of nothing useful.

We have a defence mechanism against this built into the intel space, which says that if all entries within a page are mapped to the same entry, treat it as bad memory and move on.  It may, therefore, no longer be necessary to swap to a virtual layer, but I'm going to defer to @iMHLv2 as the author, in case there's another reason we can't use the virtual layer on a windows 10 system.  

We also, should be able to cope with a scan object being found in a physical layer and still being able to have it point to something in the virtual layer properly (that's the whole point of the `native_layer` capability, to allow pointers to be found in physical memory, but address things in virtual memory), so if we don't handle that right somewhere, it'd be good to know about that too.

The requested page read you mentioned (`0xf8a000829a40`) does look to be in the virtual range though?  If you can track down what's referencing the value we can check and figure out which layer it should be addressing...

**Comment by bridgeythegeek** [comment]
Thanks @ikelos! To make sure we're on the same page (no pun intended), the `if` statement means that if the OS is **_not_** Win10 (which is the case in my example - it's Win7), the layer is swapped to the physical layer, i.e. it is no longer the virtual layer, right? This would fit with what I'm seeing.

I'm pretty sure the address of the requested read (`0xf8a000829a40`) comes from the `_OBJECT_HEADER`. Specifically: `PoolScanner` has created the `_OBJECT_HEADER` and then the call to `_OBJECT_HEADER.get_name()` uses the relative offsets within the `_OBJECT_HEADER` struct to get `OBJECT_HEADER_NAME_INFO`, and eventually lands on a pointer to a virtual offset to read the `UNICODE_STRING` which contains the name - so, the address is the location of the `UNICODE_STRING` that holds the name.

And yes, I agree that it'd be nice to be able to scan both virtual and physical memory - I guess we'd need some kind of flag for the function to know it needs to translate between layers.
