### ISSUE TITLE
Symbol Tables 404

### ISSUE THREAD

**Issue by firefart** [volatilityfoundation/volatility3#836]
All lthe symbol table download links currently end in a 404

```
https://downloads.volatilityfoundation.org/volatility3/symbols/windows.zip
https://downloads.volatilityfoundation.org/volatility3/symbols/mac.zip
https://downloads.volatilityfoundation.org/volatility3/symbols/linux.zip
```

![image](https://user-images.githubusercontent.com/105281/190895028-d14496b3-3b5d-4428-8e6d-55f38d923f2c.png)

**Comment by ikelos** [comment]
@npetroni any chance you could look into this please?

**Comment by smclinden** [comment]
There are a lot if links on the Volatility Foundation page that are broken. This isn't helping as time is of the essence on this case.

**Comment by marcurdy** [comment]
Impacting me also

**Comment by ikelos** [comment]
@awalters Sounds like it's not just the symbols directory...

**Comment by npetroni** [comment]
I  speak to AW often, you can assume we are on the same page generally.

Try again please.

**Comment by marcurdy** [comment]
npetroni, I don't know to what you're referring, but the repo hasn't changed. Firefart's original ask stands.

**Comment by ikelos** [comment]
Hiya, I've been told that the specific links should now work (note that browsing of the directories isn't available, but the direct symbol table zip packs should work).  @smclinden could you please provide some examples of the links that aren't functioning on the volatility foundation website please?

**Comment by firefart** [comment]
can confirm, the symbol downloads are now working again thanks!
