### ISSUE TITLE
Volatility3.framework.plugins: Automagic exception occurred: urllib.error.URLError:

### ISSUE THREAD

**Issue by AhmetPayaslioglu** [volatilityfoundation/volatility3#856]
Hi,

**Describe the bug**
When I try to know the image info of the OS , I get this error.

**Context**
Volatility Version: volatility3-1.0.0
Operating System:  Edition: Windows 10 Enterprise Evaluation Version: 21H2 OS Build:19044.1288
Python Version:  Python 3.7.9
Command:  vol.py -f ram-image.raw windows.info.Info

**To Reproduce**

1. Use command 'vol.py -f ram-image.raw windows.info.Info' 
2. See error : 
Volatility 3 Framework 1.0.0
WARNING  volatility3.framework.plugins: Automagic exception occurred: urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Unsatisfied requirement plugins.Info.nt_symbols: Windows kernel symbols

A symbol table requirement was not fulfilled.  Please verify that:
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.nt_symbols']

**Expected behavior**
Get the Windows info.

**Screenshots**
![image](https://user-images.githubusercontent.com/46576332/199439567-6449284c-6c77-4ae7-aabb-09800d6971ec.png)

**Comment by digitalisx** [comment]
Hello, @AhmetPayaslioglu
I think the version of volatility3 that using is too old version to catch this error.
Would you like to try the latest `2.0.1` version of the [release](https://github.com/volatilityfoundation/volatility3/releases/tag/v2.0.1)?

**Comment by AhmetPayaslioglu** [comment]
Hello, @digitalisx 
Thank you. The new version is working properly. 
I would like to ask one more question, Doesn't work without an internet connection? Looks like it need download from http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/733830ECAFA1A3073FFAWARNING . 
Did you set this new? I remember that it also worked without the internet a long time ago. Thank you.

**Comment by digitalisx** [comment]
All right, I'm very happy to hear that it's working fine. Fortunately, the question is possible.
Here is a well-writed [article](https://blogs.jpcert.or.jp/en/2021/09/volatility3_offline.html) on how to use volatility3 offline.
If you are still curious or need help reading this, please leave a thread.

**Comment by ikelos** [comment]
This sounds like it's been answered, so I'm going to mark it as closed.  If you're still having difficulties, please feel free to reopen it...  5:)

**Comment by AhmetPayaslioglu** [comment]
Thanks a lot!
