### ISSUE TITLE
Need help installing the requirements.txt

### ISSUE THREAD

**Issue by eduardogarcia4499** [volatilityfoundation/volatility3#860]
Can you help me get Volatility 3 working on Windows 11? I get this error when I run this command pip install -r requirements.txt I don't know what else to try. 

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pefile>=2017.8.1 in c:\users\garci\appdata\roaming\python\python311\site-packages (from -r requirements.txt (line 2)) (2022.5.30)
Requirement already satisfied: yara-python>=3.8.0 in c:\users\garci\appdata\roaming\python\python311\site-packages (from -r requirements.txt (line 8)) (4.2.3)
Collecting capstone>=3.0.5
Using cached capstone-4.0.2-py2.py3-none-win_amd64.whl (896 kB)
Collecting pycryptodome
Using cached pycryptodome-3.15.0-cp35-abi3-win_amd64.whl (1.9 MB)
Collecting leechcorepyc>=2.4.0
Using cached leechcorepyc-2.13.0-cp36-abi3-win_amd64.whl (349 kB)
Collecting python-snappy==0.6.0
Using cached python-snappy-0.6.0.tar.gz (21 kB)
Preparing metadata (setup.py) ... done
Requirement already satisfied: future in c:\users\garci\appdata\roaming\python\python311\site-packages (from pefile>=2017.8.1->-r requirements.txt (line 2)) (0.18.2)
Building wheels for collected packages: python-snappy
Building wheel for python-snappy (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [26 lines of output]
C:\Program Files\Python311\Lib\site-packages\setuptools_distutils\dist.py:264: UserWarning: Unknown distribution option: 'cffi_modules'
warnings.warn(msg)
running bdist_wheel
running build
running build_py
creating build
creating build\lib.win-amd64-cpython-311
creating build\lib.win-amd64-cpython-311\snappy
copying snappy\hadoop_snappy.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy\snappy.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy\snappy_cffi.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy\snappy_cffi_builder.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy\snappy_formats.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy_init_.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy_main_.py -> build\lib.win-amd64-cpython-311\snappy
running build_ext
building 'snappy._snappy' extension
creating build\temp.win-amd64-cpython-311
creating build\temp.win-amd64-cpython-311\Release
creating build\temp.win-amd64-cpython-311\Release\snappy
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Program Files\Python311\include" "-IC:\Program Files\Python311\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcsnappy/crc32c.c /Fobuild\temp.win-amd64-cpython-311\Release\snappy/crc32c.obj
crc32c.c
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Program Files\Python311\include" "-IC:\Program Files\Python311\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpsnappy/snappymodule.cc /Fobuild\temp.win-amd64-cpython-311\Release\snappy/snappymodule.obj
snappymodule.cc
snappy/snappymodule.cc(32): fatal error C1083: Cannot open include file: 'snappy-c.h': No such file or directory
error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe' failed with exit code 2
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for python-snappy
Running setup.py clean for python-snappy
Failed to build python-snappy
Installing collected packages: python-snappy, pycryptodome, leechcorepyc, capstone
Attempting uninstall: python-snappy
Found existing installation: python-snappy 0.6.1
Uninstalling python-snappy-0.6.1:
Successfully uninstalled python-snappy-0.6.1
Running setup.py install for python-snappy ... error
error: subprocess-exited-with-error

× Running setup.py install for python-snappy did not run successfully.
│ exit code: 1
╰─> [28 lines of output]
C:\Program Files\Python311\Lib\site-packages\setuptools_distutils\dist.py:264: UserWarning: Unknown distribution option: 'cffi_modules'
warnings.warn(msg)
running install
C:\Program Files\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
warnings.warn(
running build
running build_py
creating build
creating build\lib.win-amd64-cpython-311
creating build\lib.win-amd64-cpython-311\snappy
copying snappy\hadoop_snappy.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy\snappy.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy\snappy_cffi.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy\snappy_cffi_builder.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy\snappy_formats.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy_init_.py -> build\lib.win-amd64-cpython-311\snappy
copying snappy_main_.py -> build\lib.win-amd64-cpython-311\snappy
running build_ext
building 'snappy._snappy' extension
creating build\temp.win-amd64-cpython-311
creating build\temp.win-amd64-cpython-311\Release
creating build\temp.win-amd64-cpython-311\Release\snappy
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Program Files\Python311\include" "-IC:\Program Files\Python311\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcsnappy/crc32c.c /Fobuild\temp.win-amd64-cpython-311\Release\snappy/crc32c.obj
crc32c.c
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Program Files\Python311\include" "-IC:\Program Files\Python311\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpsnappy/snappymodule.cc /Fobuild\temp.win-amd64-cpython-311\Release\snappy/snappymodule.obj
snappymodule.cc
snappy/snappymodule.cc(32): fatal error C1083: Cannot open include file: 'snappy-c.h': No such file or directory
error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe' failed with exit code 2
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
Rolling back uninstall of python-snappy
Moving to c:\users\garci\appdata\roaming\python\python311\site-packages\python_snappy-0.6.1.dist-info
from C:\Users\garci\AppData\Roaming\Python\Python311\site-packages~ython_snappy-0.6.1.dist-info
Moving to c:\users\garci\appdata\roaming\python\python311\site-packages\snappy
from C:\Users\garci\AppData\Roaming\Python\Python311\site-packages~nappy
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-snappy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by digitalisx** [comment]
Hello @Lalo141,
This is because the requirements for installing `python-snappy` have not been met.
Could you refer to these issues?
- #804
