### ISSUE TITLE
KDBG Encrypted

### ISSUE THREAD

**Issue by jsvwiajaba** [volatilityfoundation/volatility3#866]
Does volatility handle an encrypted kdbg tag header in windows? as mentioned in volatility2:
https://github.com/volatilityfoundation/volatility/wiki/Encrypted-KDBG-(Win-8-and-later)

 Volatility search for a KDBG struct in "automagic/pdbscan.py", but doesnt handle the encrypted tag
`def method_kdbg_offset(self,
                           context: interfaces.context.ContextInterface,
                           vlayer: layers.intel.Intel,
                           progress_callback: constants.ProgressCallback = None) -> Optional[ValidKernelType]:
        return self._method_offset(context, vlayer, b"KDBG", 8, progress_callback)
`

I cant find the part of code that handle the decryption of this tag there
The decryption is critical in order to find a valid kernel for windows machines

**Comment by ikelos** [comment]
It doesn't, however, it's not the only technique used to determine the kernel.  We'll probably add it at some point, but so far volatility 3 works effectively on a number of different Windows images using its existing heuristics.  Usually Volatility 3 searches for the PDB header of a loaded kernel and uses that to load the necessary symbols (which can then also help identify the KDBG structure).  Are you in need of a decrypted KDBG structure for some other reason, or was it purely for identifying the OS?

**Comment by paulkermann** [comment]
@jsvwiajaba Have a look at #718 and `get_kdbg_structure` for accessing the KDBG as if it was decrypted.
