### ISSUE TITLE
possible bug in pdbutil.py - incorrect use of .strip()

### ISSUE THREAD

**Issue by paulkermann** [volatilityfoundation/volatility3#867]
https://github.com/volatilityfoundation/volatility3/blob/37c0dd290e27b8b3b03608b4b005c3a9707a72f8/volatility3/framework/symbols/windows/pdbutil.py#L362

using `.strip()` removes characters, not whole substrings. In this case, if the module name ends with the characters p d or b, the end of the module name will also be incorrectly truncated

example:
```python
>>> p="pbdpbpbdpbdpdpbpdpdb.pdb"
>>> p.strip(".pdb")
''
```
I think change the `.strip(".pdb")` to a `p.split(".pdb", 1)[0]` yields the desired result.

**Comment by ikelos** [comment]
Good spot, thanks.  I change it to `replace`, but I'm considering whether we only want to remove characters if they're at the end of the string...
