### ISSUE TITLE
volatiltiy workbench application not opening in small screen

### ISSUE THREAD

**Issue by KhandelwalGK** [volatilityfoundation/volatility3#878]
**Describe the bug**

**Context**
Volatility Version:  
Operating System:  
Python Version:  
Suspected Operating System:  
Command:  

**To Reproduce**

1. Use command '...'
2. See error

**Expected behavior**

**Example output**
Please copy and paste the text demonstrating the issue, ideally with verbose output turned on (`vol.py -vvv ...`).  

Text is preferred to screenshots for searching and to talk about specific parts of the output.

**Additional information**
Add any other information about the problem here.

**Comment by ikelos** [comment]
Please provide the requested information in the template above, the description of the bug doesn't provide any details.  I'll close this off in a few days if no further information is provided...

**Comment by ikelos** [comment]
Hiya, I think you're asking about the "volatility workbench" which isn't made by or supported by the volatility foundation.  I couldn't find a bug tracker on their page, but they did have a contact us page, so I recommend you getting in touch with them.  Closing this off, but feel free to reopen this if the issue you've found is actually within the volatility package and not a third party UI...

https://www.osforensics.com/tools/volatility-workbench.html
