### ISSUE TITLE
document the usage of avml with volatility3

### ISSUE THREAD

**Issue by gogo2464** [volatilityfoundation/volatility3#880]
**Is your feature request related to a problem? Please describe.**
I want to use the avml microsoft project at https://github.com/microsoft/avml on Linux with volatility3. It is well documented for version2 but not 3.

**Describe the solution you'd like**
I would like to have a tutorial on a few command to extract memory from avml.

**Describe alternatives you've considered**
I tried :

```
$ vol -f ./output.dmp windows.pslist.PsList

Volatility 3 Framework 2.4.1

Progress:  100.00		PDB scanning finished                  

Unsatisfied requirement plugins.PsList.kernel.layer_name: 

Unsatisfied requirement plugins.PsList.kernel.symbol_table_name: 



A translation layer requirement was not fulfilled.  Please verify that:

	A file was provided to create this layer (by -f, --single-location or by config)

	The file exists and is readable

	The file is a valid memory image and was acquired cleanly



A symbol table requirement was not fulfilled.  Please verify that:

	The associated translation layer requirement was fulfilled

	You have the correct symbol file for the requirement

	The symbol file is under the correct directory or zip file

	The symbol file is named appropriately or contains the correct banner



Unable to validate the plugin requirements: ['plugins.PsList.kernel.layer_name', 'plugins.PsList.kernel.symbol_table_name']
```

**Additional information**

**Comment by ikelos** [comment]
Thanks, please could you run `vol -vvv` above rather than just `vol`?  AVML uses snappy, meaning you'll need to have that package installed, but if it can't find snappy it should [raise a visible warning](https://github.com/volatilityfoundation/volatility3/blob/02d6dbead7f13bafa2f0b98831d35dffd24cf53d/volatility3/framework/layers/avml.py#L46).  The output from `-vvv` should help identify if there's an issue with the image or whether it was the avml format of the file causing problems...

**Comment by gogo2464** [comment]
(venv3) WHOAMI@debian:~/volatility$ vol -f ./output.dmp windows.pslist.PsList -vvv

Volatility 3 Framework 2.4.1

INFO     volatility3.cli: Volatility plugins path: ['/home/WHOAMI/volatility/venv3/lib/python3.9/site-packages/volatility3-2.4.1-py3.9.egg/volatility3/plugins', '/home/WHOAMI/volatility/venv3/lib/python3.9/site-packages/volatility3-2.4.1-py3.9.egg/volatility3/framework/plugins']

INFO     volatility3.cli: Volatility symbols path: ['/home/WHOAMI/volatility/venv3/lib/python3.9/site-packages/volatility3-2.4.1-py3.9.egg/volatility3/symbols', '/home/WHOAMI/volatility/venv3/lib/python3.9/site-packages/volatility3-2.4.1-py3.9.egg/volatility3/framework/symbols']

usage: volatility [-h] [-c CONFIG] [--parallelism [{processes,threads,off}]] [-e EXTEND] [-p PLUGIN_DIRS] [-s SYMBOL_DIRS] [-v] [-l LOG] [-o OUTPUT_DIR] [-q] [-r RENDERER] [-f FILE] [--write-config]

                  [--save-config SAVE_CONFIG] [--clear-cache] [--cache-path CACHE_PATH] [--offline] [--single-location SINGLE_LOCATION] [--stackers [STACKERS ...]]

                  [--single-swap-locations [SINGLE_SWAP_LOCATIONS ...]]

                  plugin ...

volatility: error: unrecognized arguments: -vvv

**Comment by ikelos** [comment]
Yep, unfortunately to allow plugins to specify their own options, there's a different between volatility flags and plugin flags.  The `-vvv` needs to go before the plugin name.  If you just change `vol` to `vol -vvv` that should work fine...

**Comment by ikelos** [comment]
There's been no additional information provided since December 9th, so marking this as closed.  Please feel free to reopen the issue if you didn't manage to resolve it...

**Comment by gogo2464** [comment]
I am very busy. I should in the future.

**Comment by ikelos** [comment]
No problem, thanks for getting back so promptly, I'm happy to reopen this and leave it sit until you're a bit more free.  5:)
