### ISSUE TITLE
Page error in layer primary in Volatility3

### ISSUE THREAD

**Issue by JerryyyTheDuck** [volatilityfoundation/volatility3#889]
I have this error, try to find the solution on the internet but I cannot do anything. I haved tried lots of time. 
Volatility Version: 3_1.0.0
Operating System: Window10
Python Version: python3.11
Suspected Operating System: Windows 10 x64
Command lead to the error: & C:/Users/Jack/AppData/Local/Programs/Python/Python311/python.exe d:/volatility3-1.0.0/vol.py -f .\memory_image.vmem -o "test" windows.dumpfile --pid 4484
**Error**
![image](https://user-images.githubusercontent.com/100250271/207867658-566c5c0e-37cc-44f5-ac39-c1350d0faf09.png)
**pslist command**
![image](https://user-images.githubusercontent.com/100250271/207868146-54081303-e931-4c9e-b971-db3bba490d6a.png)
![image](https://user-images.githubusercontent.com/100250271/207868223-89e4a232-ebfa-4a32-9f7e-095f8ad4ddf9.png)

**Comment by ikelos** [comment]
I'd suggest testing with a more recent version of volatility3 (version 2.4.0 is now available), although there's no guarantee that this will be resolved.  It may simply be that the structures volatility3 relies on to find the process memory you've requested aren't available or accessible in the image you have.  In those circumstances re-imaging the memory may help.

Please could you try testing with the most recent release of volatility and let us know whether that changes the output at all?  Thanks...
