### ISSUE TITLE
Broken Wiki Link

### ISSUE THREAD

**Issue by thebeanogamer** [volatilityfoundation/volatility3#91]
The repo [Wiki ](https://github.com/volatilityfoundation/volatility3/wiki) is made up of a link to this page on another repo (I'm assuming a private one), which gives a 404: https://github.com/volatilityfoundation/devwiki/wiki/Volatility3

Should this be swapped for a Read the Docs link? https://volatility3.readthedocs.io/en/latest/

I would do this as a PR, but annoyingly, GitHub won't let you make PRs to Wikis.

**Comment by ikelos** [comment]
Thanks for the spot, this should now be resolved!  5:)  Feel free to reopen if you think there's still an issue...
