### ISSUE TITLE
`symbols` directory location

### ISSUE THREAD

**Issue by nopedawn** [volatilityfoundation/volatility3#923]
I have previously installed volatility3 with the commands below, but I don't know specifically where the `/volatility3/volatility3/symbols ` directory is located on my computer.

```
- sudo apt install -y python3 python3-dev libpython3-dev python3-pip python3-setuptools python3-wheel
- python3 -m pip install -U distorm3 yara-python pycrypto pillow openpyxl ujson pytz ipython capstone
- python3 -m pip install -U git+https://github.com/volatilityfoundation/volatility3.git
```

I did not clone from the repository, but installed directly with the above commands.

How can I find the location of the `/volatility3/volatility3/symbols` directory on my device?

**Comment by ikelos** [comment]
It likely ended up in `/usr/lib{,64}/python<python_version>` and then either under site-packages or dist-packages.  You can determine the paths volatility will use for symbols and plugins by running `vol.py -v` and the first few lines should provide information about the current paths.  You can also add a new symbols path using `-s <additional_path>`.  Hopefully this resolves your question.  If you have any other questions, you might get a quicker response on our [slack channel](https://www.volatilityfoundation.org/slack).  I'm going to mark this as closed, but if you're still encountering issues and don't get a response on the slack channel, feel free to reopen this...  5:)

**Comment by nopedawn** [comment]
I've found `symbols` in 2 directories

`/home/users/.local/lib/python3.10/site-packages/volatility3/symbols` & `/home/users/.local/lib/python3.10/site-packages/volatility3/framework/plugins`.

Well Thanks.
