### ISSUE TITLE
Use hivescan get a unreachable physical offset

### ISSUE THREAD

**Issue by status-code-404** [volatilityfoundation/volatility3#926]
When I use the hivescan to scan windows 10 memory dmp file (16GB)  where I want to get the physical offset of the hive struct, the offset is out of the limit, for example:
C:\Users\XXXX>python vol.py memory.dmp hivescan
Volatility 3 Framework 2.4.2
Progress:  100.00               PDB scanning finished
Offset
0xb78cfe45a000
0xb78d05e75000
0xb78cfdd4b000

the location I get , such as b78cfe45a000 , from my view , is 2 ^ 48 and I can't locate it because the memory file size only 2 ^ 34. Is the way I read the offset wrong?

**Comment by eve-mem** [comment]
It looks like the hivescan plugin returns virtual addresses, so they won't relate to an offset in the actual file. 

Using volshell you could access these if you wanted. (Or translate them to a physical address)

e.g. 
```
volshell.py -f <mem> -w
# automagic happens
db(0xb78cfe45a000)
db(0xb78d05e75000)
db(0xb78cfdd4b000)
```

**Comment by status-code-404** [comment]
> It looks like the hivescan plugin returns virtual addresses, so they won't relate to an offset in the actual file.
> 
> Using volshell you could access these if you wanted. (Or translate them to a physical address)
> 
> e.g.
> 
> ```
> volshell.py -f <mem> -w
> # automagic happens
> db(0xb78cfe45a000)
> db(0xb78d05e75000)
> db(0xb78cfdd4b000)
> ```

Sorry, Can you tell me how can I translate to physical address 😂

**Comment by ikelos** [comment]
> Sorry, Can you tell me how can I translate to physical address joy

If you have a virtual layer in a variable (let's call it `memory_layer`), then you can ask it to map to a lower layer in volshell by doing:

```
(virtual_offset, size, physical_offset, size, physical_layer_name) = memory_layer.mapping(<ADDRESS>, <length>)[0]
```

This looks up a mapping of 0 bytes in length on the layer, and will return you a generated list containing (for each chunk of memory maklng up the <length> bytes) the virtual offset the chunk starts at, the size of the chunk in virtual memory, the physical offset it starts at, the size of the physical chunk (these should match except in the cases of layers that do compression or some other strange transformation) and finally the name of the physical layer.  You could then locate the physical layer layer and repeat the same thing (which, if the layer is LiME or some other memory encoding format that isn't raw, will need to be done to find the offset in the underlying file).

Hopefully this will get you where you need to be?  I've marked this as a question and I'm going to close it off, but feel free to reopen it if you feel there's a still problem.  For questions you might get a faster response by joining out [slack server](https://www.volatilityfoundation.org/slack)...

**Comment by status-code-404** [comment]
> > Sorry, Can you tell me how can I translate to physical address joy
> 
> If you have a virtual layer in a variable (let's call it `memory_layer`), then you can ask it to map to a lower layer in volshell by doing:
> 
> ```
> (virtual_offset, size, physical_offset, size, physical_layer_name) = memory_layer.mapping(<ADDRESS>, <length>)[0]
> ```
> 
> This looks up a mapping of 0 bytes in length on the layer, and will return you a generated list containing (for each chunk of memory maklng up the bytes) the virtual offset the chunk starts at, the size of the chunk in virtual memory, the physical offset it starts at, the size of the physical chunk (these should match except in the cases of layers that do compression or some other strange transformation) and finally the name of the physical layer. You could then locate the physical layer layer and repeat the same thing (which, if the layer is LiME or some other memory encoding format that isn't raw, will need to be done to find the offset in the underlying file).
> 
> Hopefully this will get you where you need to be? I've marked this as a question and I'm going to close it off, but feel free to reopen it if you feel there's a still problem. For questions you might get a faster response by joining out [slack server](https://www.volatilityfoundation.org/slack)...

Ok thanks
