### ISSUE TITLE
run volatility3-standalone on esxi 6.*

### ISSUE THREAD

**Issue by git801** [volatilityfoundation/volatility3#927]
I would like to run volatility3-2.4.0 on esxi 6.* ,so i tried to build it to a elf.

OS :  centos 6.10 which GLIBC_2.12 , 
Python : 3.7.0
update zlib1.2.3 -> zlib 1.2.11

now i can pyinstaller vol.spec to volatiltiy3-standalone(one file) and run successfully on centos.

on esxi returns Fatal Python error : initfsencoding: unable to load system codec ModuleNotFoundError:No module named 'encodings'

and build it to a floader not one file ,on esxi it returns ImportError:libbz2.so.1:failed to map text segment from shared object:No space left on device Failed to execute script 'vol' due unhandled exception!

i have tried many ways ,but failed .would anyone give me a hand ,thank you very much.

**Comment by ikelos** [comment]
I'm not sure we can support an operating system with restricted disk space and potentially a non-standard/non-full python installation, so there may not be a solution.

You can probably tinker with the place we use bzip2 the most (which is [here](https://github.com/volatilityfoundation/volatility3/blob/a77a1ae301f9f00a2a073ff4b0eaff6644d732f8/volatility3/framework/layers/resources.py)), but we don't directly import encodings anywhere to my knowledge, so I suspect that an issue with the python installation on ESXi.  Again, you might be able to modify the `vol.spec` file to forcibly include it, but I don't know if there are additional data files that would be needed.  This isn't a bug in volatility specifically, so I'm afraid I'm going to mark this as closed.  You might be able to seek more direct help on our [slack channel](https://volatilityfoundation.org/slack) if you really want to pursue this?  If you really feel as though this is a specific failure in volatility with an actionable fix, then do please reopen it and provide information that might clarify the issue...
