### ISSUE TITLE
Volatility3 doesn't remove stale cache items and --clear-cache doesn't operate correctly

### ISSUE THREAD

**Issue by Havocnl** [volatilityfoundation/volatility3#931]
Volatility seems to try to find a locally stored symbol, even though no such symbol / file exists.
When it tries to use that non-existing file/symbol, it breaks.
It never tries to download the symbol, which it should.
This seems to happen on some machines but not all.

**Context**
Volatility Version:  2.4.0
Operating System:  Win 10 enterprise
Python Version:  3.9.1
Running inside a venv
Suspected Operating System:  windows server 2016
Command:  
(venv) PS C:\Forensic Program Files\volatility3\venv\Scripts> vol.exe -vvvvv -f D:\memory.raw windows.info

Error code:
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0x82c00000
DEBUG    volatility3.framework.symbols.windows.pdbutil: Using symbol library: ntkrpamp.pdb\CE18EBF87B6A4C5CBF77806534BD9478-2
INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
INFO     volatility3.framework.automagic: Running automagic: KernelModule
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
WARNING  volatility3.framework.plugins: Automagic exception occurred: FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Forensic Program Files\\volatility3\\venv\\Lib\\site-packages\\volatility3\\symbols\\windows\\ntkrnlmp.pdb\\1E0FC3A5D22C7752975FA567B2746303-1.json.xz'
Level 9  volatility3.framework.plugins: Traceback (most recent call last):
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\automagic\__init__.py", line 124, in run
    automagic(context, config_path, requirement, progress_callback)
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\automagic\symbol_cache.py", line 419, in __call__
    self._cache.update(progress_callback)
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\automagic\symbol_cache.py", line 282, in update
    timestamp = datetime.datetime.fromtimestamp(os.stat(pathname).st_mtime)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Forensic Program Files\\volatility3\\venv\\Lib\\site-packages\\volatility3\\symbols\\windows\\ntkrnlmp.pdb\\1E0FC3A5D22C7752975FA567B2746303-1.json.xz'

WARNING  volatility3.framework.plugins: Automagic exception occurred: urllib.error.URLError: <urlopen error [WinError 3] The system cannot find the path specified: 'C:\\Forensic Program Files\\volatility3\\venv\\Lib\\site-packages\\volatility3\\symbols\\windows\\ntkrpamp.pdb\\CE18EBF87B6A4C5CBF77806534BD9478-2.json.xz'>
Level 9  volatility3.framework.plugins: Traceback (most recent call last):
  File "C:\python39\lib\urllib\request.py", line 1499, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Forensic Program Files\\volatility3\\venv\\Lib\\site-packages\\volatility3\\symbols\\windows\\ntkrpamp.pdb\\CE18EBF87B6A4C5CBF77806534BD9478-2.json.xz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\automagic\__init__.py", line 124, in run
    automagic(context, config_path, requirement, progress_callback)
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\automagic\pdbscan.py", line 349, in __call__
    self.recurse_symbol_fulfiller(context, valid_kernel, progress_callback)
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\automagic\pdbscan.py", line 105, in recurse_symbol_fulfiller
    PDBUtility.load_windows_symbol_table(
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\symbols\windows\pdbutil.py", line 115, in load_windows_symbol_table
    requirement.construct(context, parent_config_path)
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\configuration\requirements.py", line 378, in construct
    obj = self._construct_class(context, config_path, args)
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\interfaces\configuration.py", line 600, in _construct_class
    obj = cls(**requirement_dict)
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\symbols\windows\__init__.py", line 14, in __init__
    super().__init__(*args, **kwargs)
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\symbols\intermed.py", line 105, in __init__
    fp = resources.ResourceAccessor().open(isf_url)
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\layers\resources.py", line 134, in open
    raise excp
  File "c:\forensic program files\volatility3\venv\lib\site-packages\volatility3\framework\layers\resources.py", line 120, in open
    fp = urllib.request.urlopen(url, context = self._context)
  File "C:\python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\python39\lib\urllib\request.py", line 1477, in file_open
    return self.open_local_file(req)
  File "C:\python39\lib\urllib\request.py", line 1516, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 3] The system cannot find the path specified: 'C:\\Forensic Program Files\\volatility3\\venv\\Lib\\site-packages\\volatility3\\symbols\\windows\\ntkrpamp.pdb\\CE18EBF87B6A4C5CBF77806534BD9478-2.json.xz'>

Unsatisfied requirement plugins.Info.kernel.symbol_table_name:

A symbol table requirement was not fulfilled.  Please verify that:
        The associated translation layer requirement was fulfilled
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.kernel.symbol_table_name']
(venv) PS C:\Forensic Program Files\volatility3\venv\Scripts>

Rather I was expecting this code (which is how it runs as expected, on another machine, same config, same memory dump)

INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf8047f800000
INFO     volatility3.framework.symbols.windows.pdbconv: Download PDB file...
DEBUG    volatility3.framework.symbols.windows.pdbconv: Attempting to retrieve http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/1E0FC3A5D22C7752975FA567B27463031/ntkrnlmp.pdb
DEBUG    volatility3.framework.layers.resources: Using already cached file at: C:\Users\user \AppData\Roaming\volatility3\data_3929e56c75a5157761968f1e50ce28fb728aaf1d93958c4140c9adc4eb2fd175af97941c0ecd9d6af6184d4bc3ad19c05360cd6d89e7268fca78222c3be381e6.cache
DEBUG    volatility3.framework.layers.resources: Using already cached file at: C:\Users\user\AppData\Roaming\volatility3\data_3929e56c75a5157761968f1e50ce28fb728aaf1d93958c4140c9adc4eb2fd175af97941c0ecd9d6af6184d4bc3ad19c05360cd6d89e7268fca78222c3be381e6.cache

I haven't a clue where or why volatlity3 thinks I've got the symbol cached/stored.

This even persists after deleting the venv and creating a new one:
python.exe -m venv <path to venv>
activate the venv
pip install volatility3
run command as mentioned.

any help would be greatly appreciated. I suspect there's some artifact present on my machine that makes volatility3 believe I have the symbol cached when I haven't.

**Comment by eve-mem** [comment]
Can you try using `--clear-cache` to see if that makes any difference at all.

**Comment by Havocnl** [comment]
Unfortunately, that does not make any difference at all.

**Comment by Havocnl** [comment]
When running the plugin isfinfo I get this:

INFO     volatility3.framework.automagic: No plugin category detected
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
INFO     volatility3.framework.automagic: Running automagic: SymbolCacheMagic
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
INFO     volatility3.framework.automagic: Running automagic: LinuxSymbolFinder
INFO     volatility3.framework.automagic: Running automagic: MacSymbolFinder
INFO     volatility3.framework.automagic: Running automagic: KernelModule

URI     Valid   Number of base_types    Number of types Number of symbols       Number of enums Identifying information

file:///C:/Forensic%20Program%20Files/volatility3/venv/Lib/site-packages/volatility3/symbols/windows/ntkrnlmp.pdb/1E0FC3A5D22C7752975FA567B2746303-1.json.xz    Unknown 16      0       42622   322     b'ntkrnlmp.pdb|1E0FC3A5D22C7752975FA567B2746303|1'
file:///C:/Forensic%20Program%20Files/volatility3/venv/Lib/site-packages/volatility3/symbols/windows/tcpip.pdb/B95FBE139374D349E4153F60D59DFA92-1.json.xz       Unknown 0       0       9329    0       b'tcpip.pdb|B95FBE139374D349E4153F60D59DFA92|1'
file:///C:/Forensic%20Program%20Files/volatility3/venv/Lib/site-packages/volatility3/symbols/windows/tcpip.pdb/C8F0C6070D4B2D43B94E2B379436E928-1.json.xz       Unknown 0       0       9152    0       b'tcpip.pdb|C8F0C6070D4B2D43B94E2B379436E928|1'
file:///C:/Forensic%20Program%20Files/volatility3/venv/Lib/site-packages/volatility3/symbols/windows/ntkrnlmp.pdb/1B4A6F5E0766C552C90710C8ACC0295C-1.json.xz    Unknown 16      0       39908   293     b'ntkrnlmp.pdb|1B4A6F5E0766C552C90710C8ACC0295C|1'
file:///C:/Forensic%20Program%20Files/volatility3/venv/Lib/site-packages/volatility3/symbols/windows/ntkrpamp.pdb/CE18EBF87B6A4C5CBF77806534BD9478-2.json.xz    Unknown 15      0       18532   110     b'ntkrpamp.pdb|CE18EBF87B6A4C5CBF77806534BD9478|2'
file:///C:/Forensic%20Program%20Files/volatility3/venv/Lib/site-packages/volatility3/symbols/windows/tcpip.pdb/676C275B8EAE4B50A19255B333A152BA-2.json.xz       Unknown 0       0       7876    0       b'tcpip.pdb|676C275B8EAE4B50A19255B333A152BA|2'
(venv) PS C:\Forensic Program Files\volatility3\venv\Scripts>

however, the directory
C:/Forensic%20Program%20Files/volatility3/venv/Lib/site-packages/volatility3/symbols

does not exist.

running the isfinfo plugin with --validate gives the same error as in the initial post.

Is there a way to remove the cache that isfinfo is using?

**Comment by Havocnl** [comment]
I fixed it by deleting the C:\Users\<username>\AppData\Roaming\volatility3 folder.

I should note that running vol.exe with --clear-cache did not in fact seem to clear the cache.
This is assuming that the identifier.cache file inside this directory is the one that should have been cleared.

**Comment by ikelos** [comment]
Hiya, so I've made a pull request so that clear-cache should now actually clear the cache, but the code for cleaning out the cache *should* have been clearing out missing files regardless?  I've now moved this code earlier in the automagic, to try to ensure it runs before any other cache maintenance, but I'm not sure I see why it wasn't running successfully previously.

Please could you first test whether your issue still occurred with the latest git release of the code and verify that the problem was still present.  If it was, then please test out the pull request I've just made to see if it resolves the issue (it may just be that this is already a problem that was fixed since 2.4.0 was released).

**Comment by Havocnl** [comment]
So I found one of my machines that still had a cache file (that threw the above errors) and did the following:
-dropped into the venv
-uninstalled volatility3
-reinstalled the .whl package from the release page. (assuming you meant this release with "latest git release" https://github.com/volatilityfoundation/volatility3/releases)
-retried running volatility and got the same errors as before.

conclusion: The bug seems to be in the latest release.

I'm not too familiar with git, but saw you changed 2 files in your pull request.
I've replaced those 2 files in my current volatility installation and patched them with yours.

I can confirm this fixes the issue!

I can also confirm that your fix makes it so I don't even get the same error if I don't use --clear-cache.
To test this I removed existing symbols, and replaced the cache with the initial cache file(s) that threw errors and everything still works.
All in all very good fix!

**Comment by ikelos** [comment]
Sorry, by most recent release I meant git not official release (these can be up to four months out of date).  Thanks for testing the recent git changes!  I'm not sure they'll make the current release in a couple of weeks, but they'll definitely be rolled into the next set.  5:)
