### ISSUE TITLE
Volatility yara plugins not working with yara-python 4.3.0

### ISSUE THREAD

**Issue by Heat-Miser** [volatilityfoundation/volatility3#932]
**Describe the bug**
When using the latest yara-python bindings 4.3.0 published in March 27th, vol3 yara plugins are not matching anything.

**Context**
Volatility Version:  2.4.2
Operating System: Linux (Ubuntu)
Python Version:  3.10.6
Suspected Operating System:  Windows 10
Command:  vol -f Complete.dmp windows.vadyarascan.VadYaraScan --yara-file=bob.yar

**To Reproduce**

1. install yara-python 4.3.0
2. write a yara rule matching easily for example one matching {90}
3. test on a ram dump
4. nothing is matched

**Expected behavior**
Match based on the provided yara rule

**Example output**
vol -f Complete.dmp windows.vadyarascan.VadYaraScan --yara-file=bob.yar
Volatility 3 Framework 2.4.2
Progress:  100.00		PDB scanning finished                        
Offset	PID	Rule	Component	Value

**Additional information**
Installing yara-python 4.2.3 resolves the problem

**Comment by tlansec** [comment]
Hi,

I expect this is because the way that yara-python reports matches has changed between versions 4.2.3 and version 4.3.0.

In version 4.2.3 matches the `yara.Match` object contained an attribute `strings` which was a list of Tuples.  In version 4.3.0 (and presumably any future version) the match object contains an attribute `strings` which is a list of `yara.StringMatchInstance` values.

Cheers,
Tom

**Comment by ikelos** [comment]
Hi there, Thanks very much for diagnosing the problem so accurately, it made it very straightforward to produce a fix!  Could you please test out #933 to check that it successfully resolves the problem and returns the results you'd expect?

**Comment by Heat-Miser** [comment]
This works as expected, awesome. Thank you for correcting this so quickly :)

**Comment by kookiecrack** [comment]
Thanks for quick fix! This helped me resolve my mftscan issue due to yara error.

```
vol3@vol3-virtual-machine:~/Desktop/volatility3$ python3 vol.py -vv -f magnetctf.mem windows.mftscan.MFTScan
Volatility 3 Framework 2.4.2
INFO     volatility3.cli: Volatility plugins path: ['/home/vol3/Desktop/volatility3/volatility3/plugins', '/home/vol3/Desktop/volatility3/volatility3/framework/plugins']
INFO     volatility3.cli: Volatility symbols path: ['/home/vol3/Desktop/volatility3/volatility3/symbols', '/home/vol3/Desktop/volatility3/volatility3/framework/symbols']
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
INFO     volatility3.framework.automagic: Running automagic: SymbolCacheMagic
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
DEBUG    volatility3.framework.automagic.windows: Detecting Self-referential pointer for recent windows
DEBUG    volatility3.framework.automagic.windows: DtbSelfRef64bit test succeeded at 0x187000
DEBUG    volatility3.framework.automagic.windows: DTB was found at: 0x187000
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
INFO     volatility3.framework.automagic: Running automagic: KernelModule

Offset	Record Type	Record Number	Link Count	MFT Type	Permissions	Attribute Type	Created	Modified	Updated	Accessed	Filename
DEBUG    volatility3.framework.interfaces.layers: Scan Failure: cannot unpack non-iterable yara.StringMatch object
```

**Comment by ikelos** [comment]
Awesome, glad it helped.  I'll get it merged into the develop branch.  We're already in the freeze for the next release but the one after this should be August so not too long to get it in the main release.

**Comment by tlansec** [comment]
May be worth keeping an eye on:

https://github.com/VirusTotal/yara-python/issues/226

just incase the yara.Match change is reverted in the future.
