### ISSUE TITLE
packaging issue: deployment of tests

### ISSUE THREAD

**Issue by noraj** [volatilityfoundation/volatility3#950]
**Describe the bug**

The issue is that the setup.py is deploying the `tests` folder under the root python path and not under this package one.

So it's end up under `/usr/lib/python3.11/site-packages/tests` rather than `/usr/lib/python3.11/site-packages/[volatility3](https://github.com/volatilityfoundation/volatility3)/tests` and so conflicts with other packages having the same issue.

Anyway usually test are not shipped in a release package so the easiest would just to remove them. Else they should be deployed in the children directory. 

It's explained in ArchLinux packaging guidelines for Python: https://wiki.archlinux.org/title/Python_package_guidelines#Test_directory_in_site-package

**Context**
Volatility Version:  N/A
Operating System:  N/A
Python Version:  N/A
Suspected Operating System:  N/A
Command:  N/A

**To Reproduce**
Steps to reproduce the behavior: N/A

**Expected behavior**

No files deployed on python root path.

**Example output**
N/A

**Additional information**
N/A

**Comment by ikelos** [comment]
Sorry, this still hasn't been resolved, it appears as though python requires all packages listing explicitly for many of its packaging tasks, so we're still investigating the best method of ensuring this is maintainable in the future.

**Comment by ikelos** [comment]
Ok, #1003 landed so this should now be correctly fixed in an upcoming release.
