### ISSUE TITLE
Document: build failed of `readthedocs` page

### ISSUE THREAD

**Issue by digitalisx** [volatilityfoundation/volatility3#953]
# Description
Hello :) 
This issue is a starting from #949. Currently, there is a problem that the `readthedocs` document [page](https://readthedocs.org/projects/volatility3/builds/?page=1) in volatility3 cannot be updated to match the changes. This is probably related to this problem (https://github.com/readthedocs/readthedocs.org/issues/10290). We can offer PR for this, but it would be wiser and faster for the relevant maintainers to resolve it because testing is tough.

**Comment by ikelos** [comment]
Thanks, this should all be resolved and built properly now, thanks for doing the digging to find out what the problem was.  5:)
