### ISSUE TITLE
Is the live dump files of Windows 10 supported?

### ISSUE THREAD

**Issue by February-L** [volatilityfoundation/volatility3#964]
I have installed the package with all dependence required, and have put the windows.zip symbol table in the symbols directory, but the following error occurs when I tries to analyze a live dump generated in Windows 10. This is the first time that I have used Volatility. I'm sorry if the question was inappropriate here.
>Unable to validate the plugin requirements: ['plugins.Info.kernel.layer_name', 'plugins.Info.kernel.symbol_table_name']
```
> python vol.py -vvv -f "C:\Windows\LiveKernelReports\WATCHDOG-20230606-0953.dmp" windows.info
Volatility 3 Framework 2.4.1
INFO     volatility3.cli: Volatility plugins path: ['C:\\Program Files\\Python310\\lib\\site-packages\\volatility3\\plugins', 'C:\\Program Files\\Python310\\lib\\site-packages\\volatility3\\framework\\plugins']
INFO     volatility3.cli: Volatility symbols path: ['C:\\Program Files\\Python310\\lib\\site-packages\\volatility3\\symbols', 'C:\\Program Files\\Python310\\lib\\site-packages\\volatility3\\framework\\symbols']
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info
INFO     volatility3.framework.automagic: Running automagic: SymbolCacheMagic
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DEBUG    volatility3.framework.automagic.windows: Detecting Self-referential pointer for recent windows
DEBUG    volatility3.framework.automagic.windows: Older windows fixed location self-referential pointers
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: TypeError - Layer is not the required Architecture: FileLayer
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
INFO     volatility3.framework.automagic.pdbscan: No suitable kernels found during pdbscan
INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
INFO     volatility3.framework.automagic: Running automagic: KernelModule
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name

Unsatisfied requirement plugins.Info.kernel.layer_name:
Unsatisfied requirement plugins.Info.kernel.symbol_table_name:

A translation layer requirement was not fulfilled.  Please verify that:
        A file was provided to create this layer (by -f, --single-location or by config)
        The file exists and is readable
        The file is a valid memory image and was acquired cleanly

A symbol table requirement was not fulfilled.  Please verify that:
        The associated translation layer requirement was fulfilled
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.kernel.layer_name', 'plugins.Info.kernel.symbol_table_name']
```

**Comment by eve-mem** [comment]
Hi,

Yes a live full memory dump should be supported. You may get issues where things are moving around in memory while the memory dump is created, that's called smear. Imagine taking a picture of a moving car, if it's too fast you just get a blur.

It looks like volatility3 couldn't work out what it needed to use the correct symbols. 

How exactly are you creating the memory dumps for volatility3 to use?

**Comment by February-L** [comment]
Thanks for the information. This 'WATCHDOG-20230606-0953.dmp' file was generated automatically by Windows after a failed waking up from sleep.

**Comment by eve-mem** [comment]
Ah yes, I should have realised based on the file path. 

I personally don't have experience with those, I'm mostly focused on linux. So someone else may be able to chime in with an answer very quickly. 

That said, I might still be able to help. How big is the file that you have compared with the amount of ram the system has? What are the first 32 bytes or so of that file in hex? (You can use cyberchef to get those if you dont have a hex editor)

I'm trying to work out if it's a full physical memory dump or just the kernel for example. 

I'm also trying to work out if it's a Microsoft file type of some kind or compressed in some way.  volatility3 logs show it just chose a FileLayer which would be used for just raw file dumps.

**Comment by February-L** [comment]
The file is 4.39GB in size, and the RAM of the system is 16GB. It seems that the first many bytes are all zero, the first non-zero bytes start from offset 0x99000 and read [E9 4D 06 00 01 00 00 00 01 00 00 00 3F 00 18 10]...

**Comment by eve-mem** [comment]
Thanks for that. It means it's not a full raw memory dump as volatility3 detected it. 

It's not format I recognise, i think it is a microsoft thing, I've not been able to find a spec for it. Looking into it i understand it's possible to have different kinds of memory dumps in that location and it's up to the application to decide what kind is made on an error. 

From what i understand you should be able to do some analysis in windbg with it.

I could be wrong, but i think this format is not currently supported by volatility3. If you're able to share the sample it might be possible to add some support, but i do think that this memory dump will be missing the private memory for most (if not all) of the user processes running.

**Comment by February-L** [comment]
Thanks a lot. I'll try windbg later. I have shared the zip-compressed dump file on Google Drive:
https://drive.google.com/file/d/1cwnXI43XfJY-UL2LHF1VwaHjA-pb6auc/view?usp=drive_link

**Comment by eve-mem** [comment]
I have had a look, but I've not had much luck. I think you will need some help from someone with more windows experience.

The file does appear to contain bits of memory, pointers, strings, etc. It doesn't look like a format I recognize or one that I think vol3 will be able to support. It essentially seems like a raw memory image but with parts missing, I'd be expecting 16-20GB for your device that has 16GB of main ram.  

I have not been able to parse it with windbg either. 

You might be able to answer some questions you have about the contents of the file using tools like bulk extractor, strings, yara, hex editors, maybe even page brute, but I think there is a real change that each page of data won't be in the correct order making file carving files over 4096 bytes impossible. 

Hopefully someone with more windows knowledge can give you more insight.

**Comment by February-L** [comment]
I see. I didn't expect it to be so tricky =.=
Many thanks for your warm help!

**Comment by ikelos** [comment]
Unfortunately as @eve-mem pointed out, that looks like a partial system dump.  Windows can produce full system dumps when it crashes, but it needs configuring to do so.  I don't know that anyone's looked into the partial crash dump support, but depending on what's kept and what's thrown away, Volatility may well not have enough to work with it.  Volatility is designed only to work on complete memory images, and whilst there's been some thoughts on support individual process dumps or similar, so far there's been no forward progress on that front.  I guess windbg is your most likely point to be able to get usably memory from that image.  Otherwise I'd recommend doing a full image with another piece of software (or reconfiguring windows to take full memory dumps at crash time, although this may take up a lot of storage space depending on how often the system crashes).

Please check [this link](https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/memory-dump-file-options#configure-the-dump-type) for more information.  As such I'm afraid I'm going to close this ticket, but if you feel there's more information that's relevant feel free to reopen it.  If you take a complete image and that runs into issues, please open a fresh ticket.  Thanks!  5:)

**Comment by February-L** [comment]
Thank you very much!
