### ISSUE TITLE
ldrmodules does not display the full path of the DLLs

### ISSUE THREAD

**Issue by 35mpded** [volatilityfoundation/volatility3#967]
In volatility 2, as per [Command Reference Mal](https://github.com/volatilityfoundation/volatility/wiki/Command-Reference-Mal#ldrmodules), you can specify the verbose flag -v/--verbose to get the full path of the DLLs found in the 3 PEB lists.  Volatility 3 does not have this functionality, although it sounds to be very valuable in some situations.

**Comment by digitalisx** [comment]
Hello @SubXi, Thank you for writing the issue! :)
Implemented it the same as the original option.
I hope this will help you with the option you want.
