### ISSUE TITLE
PsList seems to break

### ISSUE THREAD

**Issue by Zarq0** [volatilityfoundation/volatility3#989]
**Describe the bug**
PsList seems to break while running the plugin `windows.pslist`. I have tried different memory dumps, to no avail.

**Context**
Volatility Version:  2.4.1
Operating System:  Windows 10 Pro 21H2
Python Version:  3.11.4
Suspected Operating System: Windows 10 Pro 21H2
Command: `vol.py -f <IMAGE> windows.pslist`

**To Reproduce**

   1. Run the above command.

**Expected behavior**
Should output the list of processes running while the memory dump was taken.

**Example output**
PID     PPID    ImageFileName   Offset(V)       Threads Handles SessionId       Wow64   CreateTime          ExitTime            File output
4       0           System              0xfa8000cbc040  85          492     N/A         False   2023-27-07      16:30:12.000000         N/A     Disabled

**Additional information**
[vol.txt](https://github.com/volatilityfoundation/volatility3/files/12181505/vol.txt)

**Comment by ikelos** [comment]
So this was able to identify an IntelLayer and load the symbols for it, but the process list then only contained a single (invalid entry).  I'm afraid this looks like a case of memory smear.  It did take the third heuristic to find a kernel virtual offset that would work, so it's possible that that one isn't correct, and it would in fact be a later one, but that's extremely difficult for us to test/try out.

Please could you trying running the `windows.info` plugin and pasting the results of that in here, so we can see whether the rest of the windows machinery is working correctly (and that might give us a clue as to whether we have the wrong kernel_virtual_offset, or something later on is going wrong)?

**Comment by Zarq0** [comment]
@ikelos Sorry for the delay, I have went to do some real life stuff. Anyway, Here's the result of running the `windows.info` plugin.

Volatility 3 Framework 2.4.1
Progress:  100.00               PDB scanning finished
Variable        Value

Kernel Base     0xf80254000000
DTB     0x1ad000
Symbols file:///C:/Users/Bread/Desktop/vol/volatility3/volatility3/symbols/windows/ntkrnlmp.pdb/87A327C6C356B7E2BAC1D75E77970165-1.json.xz
Is64Bit True
IsPAE   False
layer_name      0 WindowsIntel32e
memory_layer    1 FileLayer
KdVersionBlock  0xf80254c0f388
Major/Minor     15.19041
MachineType     34404
KeNumberProcessors      2
SystemTime      2023-07-27 08:28:20
NtSystemRoot    C:\Windows
NtProductType   NtProductWinNt
NtMajorVersion  10
NtMinorVersion  0
PE MajorOperatingSystemVersion  10
PE MinorOperatingSystemVersion  0
PE Machine      34404
PE TimeDateStamp        Fri Aug 12 19:47:38 2072

**Comment by ikelos** [comment]
Absolutely no problem, we've all got real lives that need us sometimes.  5;D  So the values in that look as though they're correct.  The machine type looks right, as does the system time, so that suggests volatility is getting the accurate data and  the system pid is usually pid 4, so the data it's found all tracks?  It's going to be difficult to figure out what in memory is throwing off it finding any other processes, but sadly the acquisition process can sometimes result in pointers being update and therefore preventing the memory from being traversed properly to find all the data that should be there.  If you're able to acquire the memory again, that might help?

You mentioned you'd tried different memory dumps... was that different dumps of the same machine or was it dumps from different machines and they all exhibit the same issue?

**Comment by Zarq0** [comment]
It was different dumps of the same machine, I don't have ability to memory dump other machines as I just don't have another one.

**Comment by ikelos** [comment]
No problem, it's just interesting that all the images had the same issue.  Did you reboot the system between captures?  I'm trying to figure out if it's an issue with the capture method, or a state the machine got into, or some specific about the version of the OS you're running...

**Comment by Zarq0** [comment]
I did not reboot the system between captures. I can provide the build number of the OS; 19044.2130.

**Comment by ikelos** [comment]
I'd be interested to know if it still didn't capture after a restart.  I suspect it's just memory smear, and there's not much to be done, but if after a reboot it still doesn't capture appropriately it might be something we could look further into (although, we'd likely need a sample image)...

**Comment by Zarq0** [comment]
Also I have seen symbols bugging out before actually making the bug report if thats relevant, I had tried multiple memory dumps though so the output just changed. I cannot provide a screenshot or a log of that though as I just didn't take one yet, it just put a rectangle with a question mark in the middle, following with a %20 then it repeating a bunch of times (it was replacing the offset output).

**Comment by Zarq0** [comment]
I'll try restarting and redoing the memory dump and trying that one.

**Comment by Zarq0** [comment]
Restarting and redoing the dump doesn't seem to help, the output doesn't change.
[vol.txt](https://github.com/volatilityfoundation/volatility3/files/12186095/vol.txt)

**Comment by Zarq0** [comment]
Nevermind, figured it out, was using a bad memory dump program. Switching to winpmem fixed it.

**Comment by ikelos** [comment]
Glad you managed to find a solution!  5;)
